### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by beli3ver** [davidhealey/waistline#1]
Hi

I want to translate this amazing app into German. Which file must I translate?

Thanks for your work.

**Comment by davidhealey** [comment]
Hi, thanks for your interest. Unfortunately this was my first android app and I built it with Cordova, I didn't use any localization library so there is no easy way to translate it. If I find time in the future I could add a localization library but I don't have any plans to at the moment.

So there are two choices, replace every string with the German equivalent to make a separate German version or implement a localization library. If you'd like to try implementing a library I'll help if I can.

**Comment by davidhealey** [comment]
Actually I've thought some more about this and I might be able to implement a solution. Give me a few hours to try something and I'll get back to you

**Comment by davidhealey** [comment]
Yeah I've found a neat solution. I'll upload it tomorrow probably and give you some instructions to make a translation.

**Comment by davidhealey** [comment]
Ok I've implemented a localisation library - might be very buggy so I will do much testing before adding it to a release. You can find the locale files here - https://github.com/davidhealey/waistline/tree/master/www/locales

To make one for German just duplicate the locale-en.json file, rename it locale-de.json. It's in the standard JSON format, the text on the left of each row is the variable name (don't touch that) and the text on the right is what you edit. The only messy bit is the user guide, I haven't found a better way to do it yet so it's just in HTML tags <h3></h3> and <p></p>. Just make sure everything is kept on a single line for these and it should be fine. Once you've made your changes you can ask me to merge them into the repo or just send me the file and I'll check it over, test it, and add it to the repo. Let me know if you have any questions.

**Comment by davidhealey** [comment]
A German translation was merged yesterday

**Comment by Aloha68** [comment]
Hi,

I use this closed subject to not open a new one. According to pull request #24, we have to wait for you to release version 2 to start the translation. As this version is available now, can we start translating your application? 

Ah, and do you know how it will work? It will be automatic from the system language or we will have the choice in settings?

Thank you for all your work ;-)

**Comment by davidhealey** [comment]
Yes you can translate now, thanks! It switches automatically based on the system language.

**Comment by Aloha68** [comment]
Okay thanks, I'll try to add french translation in the next few days.

**Comment by davidhealey** [comment]
Excellent, if you have any questions please ask.

**Comment by achimwagenknecht** [comment]
Hi, the german translation does not show up on my device. How can we solve this issue?

**Comment by davidhealey** [comment]
What is your language/locale set to on your device?

**Comment by achimwagenknecht** [comment]
german

**Comment by davidhealey** [comment]
Sorry I just checked the release and commit history. The German translation was added after the last release so it won't be available until the next release.

**Comment by davidhealey** [comment]
Hi,
A review would be great. I was planning to add some more updates before a new release but I guess I could push an intermediate release sooner. I'll put one out today or tomorrow after I've done some more testing

**Comment by davidhealey** [comment]
I've just pushed a new release - https://github.com/davidhealey/waistline/releases/tag/2.3.8

**Comment by achimwagenknecht** [comment]
And here is the review. It is published on the web and sent to 100.000 subscribers by mail.
https://www.computerwissen.de/freeware-open-source/android/artikel/abnehmen-mit-open-source.html?rss2snl=1&cHash=8d37fa05723c1551684aad7ae1aca4d8&utm_source=NL_81072_20181204&utm_medium=email&utm_campaign=20181204+Open+Source+Secrets_1011376&utm_content=24

**Comment by davidhealey** [comment]
Thank you for the review! Hopefully we can get all of the translations more complete. Although as I'm still adding new features there will be new material to translate for some time to come.
