### ISSUE TITLE
New meal and recipe systems

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#101]
I've been imagining a system where food items and recipes (called meals maybe?) are abstracted into a tree structure so a food item can either be a single item or a recipe (list of items).

Then you could add a recipe to the diary and it would show up as the sum of all the nutritional values, but you could also scale it by units/portions at that level.  This would be useful to add a recipe for say, soup, based on the ingredients you use to make the soup, but still be easily scaled when you serve yourself a bowl.

Another benefit would be the ability to add a recipe to another recipe.  This would be useful if you make recipes for things that are later used as ingredients in other recipes.  Maybe a roast dinner or something?

Also, when you add something to your diary you could search in a combined list of single food items and recipes, which might be a little faster.

Anyway, that's really off-topic, but if you do want to run any of your ideas by me, let me know.

Cheers

_Originally posted by @corngood in https://github.com/davidhealey/waistline/issues/84#issuecomment-441491170_

**Comment by davidhealey** [comment]
So recipes will be what you have suggested. A food item that is a collection of food items and when added to the diary it will appear as a single item. So if you have a recipe for a cake you can just add the cake to the diary, you won't see or be able to edit all of the "ingredient" food items. However there will be a recipe editor that is accessible from the food list.

Recipes in recipes sounds interesting. It shouldn't be too difficult to add in principle but how far down the tree will you be able to edit from within a single recipe will have to be thought about. Maybe I'll keep it simple and say you can add a recipe to a recipe but you can't edit the sub-recipe from within the parent recipe.

Now the meal system will essentially be what we currently call the recipe system. So you can have a list of food items that appear as a single item in the meals list, and when you add them to the diary they are added as separate items. And meals will be able to contain recipes.

One other thing I would like to add is to be able to quickly add the previous days meal to the diary. So you can select to add yesterday's breakfast as today's breakfast etc. I think this might become part of the meal system.

I've already begun the implementation on a new branch btw.

**Comment by corngood** [comment]
Maybe instead of changing the data structures, we could accomplish a lot of these things using new features in the existing screens.  For example, we could allow multi-selection of items in the diary, and have a button to create a recipe from the selection, or add them to a meal on the current day.

Some other random thoughts:
- option of adding a recipe as a single item (collapsed), or individual parts
- add a recipe to a recipe (by collapsing it to a single item, so no data structure change)
- duplication of items in diary, items in recipes, and recipes themselves

Along with #84, this would help me avoid abusing temporary recipes for meals, especially when meals are similar, but with slight variations.

**Comment by davidhealey** [comment]
Some good suggestions there. As I develop the new recipe system I'll see what makes sense to implement.

**Comment by corngood** [comment]
That's just based on my experience, and using temporary recipes is the only thing that feels a bit clunky.  What sort of things bother you about the way it currently works?

**Comment by davidhealey** [comment]
Well nothing particularly bothers me but I like to refine things, the points I made a couple of weeks ago above are the main things I want to tackle and they have some crossover with your suggestions too.

**Comment by davidhealey** [comment]
I've not implemented the first attempt at a recipe system - needs more real-world testing before I release it.

On the foods page there are now 3 tabs along the bottom - foods, meals, recipes.

Foods: Exactly the same as previous behaviour
Meals: Almost the same as previous behaviour except I removed the notes
Recipes: Very similar to meals but also requires a quantity and unit. Adding a recipe to the diary inserts it as a single item (just like foods).

Todo: Once this has been tested and I'm happy it's working as it should be I'll implemented a way to add recipes to meals. This won't be too difficult but I like to do one thing at a time :)

**Comment by davidhealey** [comment]
I've just added a feature so that the previous days meals show up in the meals list and are updated automatically each day. This list item can't be edited or deleted.
