### ISSUE TITLE
Glitch with using OpenFoodFacts account

### ISSUE THREAD

**Issue by caligari87** [davidhealey/waistline#102]
When I try to add my Open Food Facts credentials in the settings, the screen closes as soon as I press on the text field. I can "cheat" it by holding on the field and pasting some value, but pressing anywhere on the screen aborts so it's nearly impossible to enter an account.

I did finally get my credentials entered in on the page, but the app doesn't appear to use them. I added a product to the database successfully but it doesn't show on my account. It would be nice if the app indicated whether the account is successfully being used (such as incorrect username/password, or displaying which account the product was added with).

**Comment by davidhealey** [comment]
I think you must be the first person to have tried this feature. It was rushed and hasn't been properly tested. I'll look into. Thanks for reporting.

**Comment by davidhealey** [comment]
This should be fixed in the next update, let me know

**Comment by PopeRigby** [comment]
It's still happening for me

**Comment by davidhealey** [comment]
> It's still happening for me

Latest version?

**Comment by PopeRigby** [comment]
2.4.1

**Comment by davidhealey** [comment]
It might be fixed in 2.4.2 but I don't remember... I'll test this myself and fix it once and for all before the next update.

**Comment by mo5h** [comment]
Still seeing this issue on 2.4.2

**Comment by EmilJunker** [comment]
As of version 3.0.1, I can successfully log in with my OFF credentials (including special characters in the password), so I suggest you close this issue now.
