### ISSUE TITLE
Feature request: macro support

### ISSUE THREAD

**Issue by jaduncan** [davidhealey/waistline#11]
I'd love to use this as my tracker, but would need macro (as in protein/fat/carbs) support. Is that something that is planned?

**Comment by davidhealey** [comment]
Hi, no I don't plan to include that. I just wanted a simple weight/calorie tracker.

**Comment by davidhealey** [comment]
Oh I'm happy to merge it with my existing code, that will be super useful to many! I'm actually working on a native android version in which I intend to include this feature but it won't be ready for months as I only have limited time to work on it. I'm excited to see what you've got, does it make use of the Open Food Facts DB?

**Comment by lobneroO** [comment]
Yes, I basically copied a bit of your calorie code and extended it to proteins, fats and carbohydrates. I have yet to look into actually storing it and displaying it for daily goals, but the simple "read" after scanning a bar code works.

**Comment by davidhealey** [comment]
Yeah all the display and database stuff is what put me off implementing it myself in this version :) You'll need to add some more entities to the log, diary, and food list tables in the database.

**Comment by lxp** [comment]
@lobneroO I noticed your branches. Does it already work?
I would be interested in helping with development and beta-testing.

**Comment by davidhealey** [comment]
I've started adding this feature in the onsen-ui branch but it's not yet usable. My general rule is if it's in the master branch it's almost usable :)

**Comment by davidhealey** [comment]
This is now implemented in the onsen branch so I'll close this issue.
