### ISSUE TITLE
Waistline cordova development workflow

### ISSUE THREAD

**Issue by oliexdev** [davidhealey/waistline#115]
@davidhealey First of all, I am new in developing with cordova. How do you personally developing waistline with cordova? I get to run it with Android Studio `cordova platform add android` after I checke out your repository but if I change something in the www folder it seems it doesn't compile!? Can you maybe describe shortly your developing workflow? Do you use only a text editor or an IDE? I already read the [cordona doc](https://cordova.apache.org/docs/en/8.x/guide/platforms/android/index.html). I also managed to create an [android cordova plugin](https://cordova.apache.org/docs/en/8.x/guide/platforms/android/plugin.html) (which was really painful btw) but currently I can't test it.

**Comment by davidhealey** [comment]
Are you able to run it in the browser?

`cordova run browser`

**Comment by oliexdev** [comment]
yes to run in the browser works but I want to implement an Android cordova plugin ;)
But I figure it out, the `cordova platform add android` is out to date and messed up the build script for the new android studio version. :angry: 

I have to add the repo

```
maven { url 'https://jitpack.io' }
mavenCentral()
jcenter { url "http://jcenter.bintray.com/"}
maven { url "https://maven.google.com" }	
```

to android/CordovaLib, android/app and android

and changed the classpath to 

`classpath 'com.android.tools.build:gradle:3.1.0'`

the cordova toolchain is really buggy it is like to use the toolchain for programming a FPGA

But thanks I will try to get something to run. Need to refresh my java script skills.
Btw how do you store your data? How can I access your database to read/write? Which file do I have to look into?

**Comment by davidhealey** [comment]
The DB stuff is handled by dbhandler.js it's in the www/app/ folder
