### ISSUE TITLE
Getting new products back on Open Food Facts

### ISSUE THREAD

**Issue by teolemon** [davidhealey/waistline#12]
Can you make it possible for users to get new products back on Open Food Facts when they don't exist ?
We have a WRITE API that allows to do that seamlessly, and you can create a global account for all users to avoid them having to create an account.

You can also self-invite to the OFF Slack :
https://slack-openfoodfacts.herokuapp.com/

**Comment by davidhealey** [comment]
Hi, yes this would be a good feature to have. I'm short on time at the moment but I would definitely like to add this in the future. Do you have a direct link to the write api documentation? What is slack?

**Comment by teolemon** [comment]
Slack is the chat system we use.
For the API : https://en.wiki.openfoodfacts.org/API/Write

**Comment by davidhealey** [comment]
Thanks I'll check it out

**Comment by natrius** [comment]
That would be amazing. So would not need to create a account for adding something new and i don't need 2 different apps on my cellphone.

**Comment by davidhealey** [comment]
I will include this in my native android rewrite

**Comment by teolemon** [comment]
We have a native app from which you can freely steal code (APACHE licenced)
https://github.com/openfoodfacts/openfoodfacts-androidapp

**Comment by davidhealey** [comment]
Well this was easier than I thought in many ways but took way longer than I would have liked. But it's done... I hope :D
