### ISSUE TITLE
Cryptocurrency donation address?

### ISSUE THREAD

**Issue by kayront** [davidhealey/waistline#122]
Been looking for an open source app just like this for quite some time, and just a few days ago after refreshing fdroid, lo and behold! It's finally come.

I'd like to set a reminder for donating to your app.

Are you familiar with [Monero](https://getmonero.org) ?

See [here](http://blog.l0cal.com/2017/12/14/update-on-crypto-currency-donations-at-videolan/) for why I'm skipping Bitcoin altogether; you can easily convert from Monero to Bitcoin later anyway if that's more of your cup of tea.

I realize that making a github issue out of this is probably a bit offtopic, but as it says on the README, it's your preferred way of being contacted - so here!

If you're interested, just make a wallet, back the seed words up carefully and let me know, I make a point of supporting developers of apps that I frequently use & that add value to my life, and your app has just joined that list.

Then, simply let me know your Monero address, and I'll set a reminder to donate a little bit every now and then.

And thank you for working on the app, it's really useful.

**Comment by davidhealey** [comment]
Hello,

I don't know much about Crypto Currencies but I'll look into Monero and report back

**Comment by davidhealey** [comment]
I've been through the Monero website, user guide, and wikipedia article. From what I gather I have to install some app which will hold the virtual coins and to convert them into money I have to sell the coins at an exchange.

At the moment I don't have time to dig into the details and workout exactly how useful this is to me and although I appreciate your desire to donate very much I'm not going to setup a wallet for the time being. If I get a bunch more requests for this then I'll take the time to look into it properly but I'm not so concerned with receiving donations as I work on this project for myself primarily.

**Comment by kayront** [comment]
Hey David, great feedback.

To clarify, you don't actually have to convert them to fiat money, it's possible to spend the Moneroj directly.

See https://www.getmonero.org/community/merchants/ for a partial list.

Furthermore it is possible to easily convert Monero to Bitcoin using this site: https://xmr.to - which means you can pay for anything in Bitcoin seamlessly as well - this opens up a wider range of opportunities, such as flights (cheapair.com) or accomodation (9flats.com).

It's also possible to buy domains, virtual machines, and dedicated servers with Bitcoin.

Just wanted to clarify these points. Of course, ultimately it's your choice, and either way I'm very thankful for your work. If you ever do set this up just ping me and I'll send $20 worth of Monero every one and then.
