### ISSUE TITLE
No Interface (screen just white)

### ISSUE THREAD

**Issue by Avispa** [davidhealey/waistline#126]
Not much more to say. Loading the app and just getting a white screen with version 2.4.2 (from f-droid). Checking on applications-list, app seems to run just fine -- or at least it didn't crash. However renders it useless, literally.

Also tried to downgrade to v 2.3.7 and seeing at least a splash screen but the acutally app is just empty resp. white again.

__System:__
Android 5.0
Samsung Galaxy S5 (dual sim)

**Comment by davidhealey** [comment]
Have any of the previous versions worked for you or is this the first time you've installed it?

**Comment by Avispa** [comment]
Now I tried also version 2.10 which doesn't work as well but 1.02 works perfectly fine as far as I can tell.

**Comment by davidhealey** [comment]
Version 2 and above uses a completely different GUI library so at least that narrows it down to something with that library which I can investigate.

**Comment by Kadano** [comment]
Same problem here. Installed the app for the first time today on Galaxy S5, Android 4.4, app is pure white. Sometimes I get the splash screen, but most of the time, not even that.

**Comment by davidhealey** [comment]
hmmm maybe this is a Galaxy S5 only issue

**Comment by stettberger** [comment]
Moto G3 with CM13, Android 6.0. same Problem.

**Comment by davidhealey** [comment]
Hi guys,

I'm attaching a debug build for a new version I'm working on. It's very much a pre-alpha version so expect bugyness (and please don't report the bugs). I'm hoping that this version doesn't have the white-screen problem. Your screen may flash completely green when changing between pages, this is fine, the debug build runs tests and a green flash means everything's working.

[app-debug-apk.zip](https://github.com/davidhealey/waistline/files/3199634/app-debug-apk.zip)

**Comment by stettberger** [comment]
Everything is white. What I got from the logcat is only the following:

    05-20 22:23:05.019 19768 19804 I ActivityManager: Displayed com.waist.line/.MainActivity: +189ms
    05-20 22:23:06.042 13828 13828 I Finsky  : [1] cua.<init>(1): com.waist.line is installed but certificate mismatch

**Comment by stettberger** [comment]
Ok. after properly reinstalling it via adb i get (logcat 2>&1 | grep waist -C 3)

````
--
05-20 22:40:51.244 19768 19966 D IpReachabilityMonitor: probing ip=192.168.178.1%52
05-20 22:40:51.245 19768 19966 D IpReachabilityMonitor: probing ip=fe80::f2b0:14ff:fea0:e980%52
05-20 22:40:51.797 19768 20874 I ActivityManager: Killing 22521:com.android.documentsui/u0a41 (adj 15): empty #17
05-20 22:40:51.860 19768 20874 I ActivityManager: Killing 22797:com.waist.line/u0a197 (adj 9): remove task
05-20 22:40:51.986 19768 20573 I WindowState: WIN DEATH: Window{f237bea u0 com.waist.line/com.waist.line.MainActivity}
05-20 22:40:51.986 19768 20460 D GraphicsStats: Buffer count: 10
05-20 22:40:53.339 22826 22826 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
05-20 22:40:53.360 19768 22825 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0x11
--
05-20 22:40:59.478 22826 22826 D wpa_supplicant: nl80211: Drv Event 103 (NL80211_CMD_VENDOR) received for wlan0
05-20 22:40:59.478 22826 22826 D wpa_supplicant: nl80211: Vendor event: wiphy=11 vendor_id=0x1374 subcmd=19
05-20 22:40:59.479 22826 22826 D wpa_supplicant: nl80211: Ignore unsupported QCA vendor event 19
05-20 22:40:59.869 19768 20872 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.waist.line cmp=com.waist.line/.MainActivity} from uid 10015 on display 0
05-20 22:40:59.943 13828 13828 I AppLifecycleTracker: onActivityPaused: 
05-20 22:40:59.962 19768 22312 I ActivityManager: Start proc 23164:com.waist.line/u0a197 for activity com.waist.line/.MainActivity
05-20 22:40:59.970 23164 23164 I art     : Late-enabling -Xcheck:jni
05-20 22:41:00.003 19768 19768 I ActivityManager: Killing 22536:com.android.externalstorage/u0a11 (adj 15): empty #17
05-20 22:41:00.150 19768 20573 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.trimApplications() from ActivityManagerService.java:19903 waiters=2 for 145ms
05-20 22:41:00.151 19768 22313 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.trimApplications() from ActivityManagerService.java:19903 waiters=5 for 141ms
05-20 22:41:00.232 13828 17471 D OpenGLRenderer: endAllStagingAnimators on 0x8d567700 (LayerDrawable) with handle 0x9c4edda0
05-20 22:41:00.233 19768 19779 I art     : Background partial concurrent mark sweep GC freed 70315(4MB) AllocSpace objects, 16(520KB) LOS objects, 29% free, 38MB/54MB, paused 12.209ms total 306.813ms
05-20 22:41:00.277 23164 23164 W System  : ClassLoader referenced unknown path: /data/app/com.waist.line-1/lib/arm
05-20 22:41:00.300 23164 23164 I CordovaLog: Changing log level to DEBUG(3)
05-20 22:41:00.300 23164 23164 I CordovaActivity: Apache Cordova native platform version 7.1.4 is starting
05-20 22:41:00.300 23164 23164 D CordovaActivity: CordovaActivity.onCreate()
--
05-20 22:41:00.750 23164 23203 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
05-20 22:41:00.814 23164 23188 W chromium: [WARNING:data_reduction_proxy_config.cc(423)] SPDY proxy OFF at startup
05-20 22:41:00.848 23164 23203 I OpenGLRenderer: Initialized EGL, version 1.4
05-20 22:41:00.932 19768 19804 I ActivityManager: Displayed com.waist.line/.MainActivity: +981ms
05-20 22:41:00.962 23164 23164 D CordovaWebViewImpl: onPageDidNavigate(file:///android_asset/www/index.html)
05-20 22:41:00.966 23164 23164 W BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 23164
05-20 22:41:01.032 13828 13828 I AppLifecycleTracker: onActivitySaveInstanceState: 
```

**Comment by davidhealey** [comment]
Thanks for that. I just googled "Cannot call determinedVisibility()" and it's coming up with results about white screen issues. So I think we may have found the source of the problem. I'll keep researching and hopefully there is a known solution :D

**Comment by davidhealey** [comment]
Well 6 minutes of research :p tell me that it's possibly a HTML syntax problem. So I've validated the main index.html file and corrected a couple of minor things. Let's see if this build gets us any further. I'll install an HTML linter into my editor to help pick up these little things.
[app-debug-apk2.zip](https://github.com/davidhealey/waistline/files/3199872/app-debug-apk2.zip)

**Comment by stettberger** [comment]
I have an interface. Although it started with a white screen. However, there is a swipe menu and buttons. However, the "Add food/meals" context buttons don't do anything. The logcat stays clear with apk2.zip

**Comment by davidhealey** [comment]
Good news :) we're making progress. When you say context buttons do you mean the + buttons in the bottom right corner?

Hopefully it's just a case of cleaning up more HTML which I'll do before release.

**Comment by stettberger** [comment]
> Good news :) we're making progress. When you say context buttons do you mean the + buttons in the bottom right corner?

Exactly.

**Comment by Mavpt** [comment]
I have the same issue on version 3.0.2 when installed with F-Droid on an Asus Zenfone 5. It works when installed with PlayStore though.

**Comment by davidhealey** [comment]
I'm noticing a pattern here. F-Droid. Anyone having this issue with the version from Play (which is the version I made)?

**Comment by davidhealey** [comment]
I'm going to close this issue because we have the same thing being discussed in a fresher thread - https://github.com/davidhealey/waistline/issues/293
