### ISSUE TITLE
Feature Request: Add support for micronutriments

### ISSUE THREAD

**Issue by vilhelmgray** [davidhealey/waistline#127]
The Open Food Facts database contains data on many micronutriments (vitamins, amino acids, etc.). I believe the micronutriments data may be accessed the same way the macronutriments data is. It would be nice to have access to this data in Waistline, especially for those with restrictive diets that require nutrition tracking.

Since many users are only concerned about macronutriments (total protein, carbs, fats, etc.) the micronutriments information could be toggled visible or not. This way there could be a simple view of just the macronutriments, while still supporting the more complex breakdown of micronutriments for those who are interested.

**Comment by davidhealey** [comment]
Yes this info is available from OFF, the main thing would be coming up with a good way to access the data in the UI (which is in need of some other improvements). I'll add this to the list of feature requests but it's not something I'll be working on in the near future unless something else I'm doing relates to it. But I guess it will get added eventually, by me or someone else.

**Comment by davidhealey** [comment]
Done. Micronutrients appear below the macro nutrients for food items, meals, recipes, and diary entries. Will be available in the next update.
