### ISSUE TITLE
Before a country is chosen search does not work

### ISSUE THREAD

**Issue by mo5h** [davidhealey/waistline#130]
Steps to reproduce:
Fresh install of waistline with no existing data
Attempt to log a food diary entry
Search for "oil"

Expected result:
At least one search result for oil
Actual result:
No search results

**Comment by davidhealey** [comment]
Thanks, I'll add it to the list

**Comment by davidhealey** [comment]
Fixed in master branch - https://github.com/davidhealey/waistline/commit/d20ee2d99f9e9b69b670e3590f090f897098b726
