### ISSUE TITLE
Feature request: option to track weight in lbs

### ISSUE THREAD

**Issue by spenme** [davidhealey/waistline#132]
For US users, it would be convenient to have the option to enter weight data as lbs rather than kg.

**Comment by davidhealey** [comment]
Yeah that seems reasonable. Would also be useful for British users to have it in Stones.

**Comment by davidhealey** [comment]
Done

**Comment by longestmt** [comment]
> Done

Where is the kg/lbs toggle? I dont see it in the latest f-droid version.

**Comment by davidhealey** [comment]
It hasn't been released yet, it will be available in the next release
