### ISSUE TITLE
option to show macronutrient totals on Diary screen

### ISSUE THREAD

**Issue by JackElsey** [davidhealey/waistline#133]
Hey, cool app! I look forward to deleting MyFitnessPal and using this exclusively.

Many diets out there for weight loss, strength training, etc. stipulate a daily intake of protein, fat, and carbohydrates. It would be great if the app had the option of displaying running totals for some or all of these macronutrients on the Diary screen. 

It is currently only possible to view these totals if you go to the Statistics screen, decrease the time window to a week, select the macronutrient(s) in question, and then tap the most recent data point.

These totals could be shown on the bar at the bottom of the Diary screen and/or they could be shown for each individual meal.

**Comment by davidhealey** [comment]
Yes this has been requested before and will make it in to the at some point

**Comment by wokawoka** [comment]
+1 , I'm also waiting for this feature in order to free myself from myfitnesspal. Thanks for the great job you are doing

**Comment by davidhealey** [comment]
You'll be please to hear that I've added this now in the latest update I'm working on. It's not on github yet and is still a few weeks away probably from being published. But just wanted to tick this one off the list :)

It will be possible to display micro-nutrients here too.

![Peek 2019-05-05 00-36](https://user-images.githubusercontent.com/14021202/57185943-dc9ae300-6ecd-11e9-8b10-deb2e7be7bde.gif)
