### ISSUE TITLE
Minor Bug: System Date Format Ignored in Statistics

### ISSUE THREAD

**Issue by pyramid3d** [davidhealey/waistline#134]
While the diary page correctly uses the system date setting, this is not the case on the statistics page. The statistics page always uses the (somewhat illogical) american date format. 
My suggestin is to make the statistics page use the date format set by the system.

**Comment by davidhealey** [comment]
Yup that's a good idea

**Comment by davidhealey** [comment]
This should be fixed in the next release, let me know

**Comment by EmilJunker** [comment]
It doesn't use the American date format on my phone, so I believe this is fixed and you can close this issue.
