### ISSUE TITLE
Feature Request: Make OFF Uploading Optional

### ISSUE THREAD

**Issue by ubergeek77** [davidhealey/waistline#138]
Currently, the app will automatically upload food data to Open Food Facts whenever you add a food. There doesn't appear to be a way to disable this functionality.

This should be entirely optional. Myself and a lot of other people like to keep track of homemade recipes or other such nutrients that aren't really appropriate to upload to OFF. I'm sure the contributors of OFF would appreciate any measures to reduce spam on their platform.

Rather than disable it entirely, the app should prompt the user if the recently-added food should be uploaded to OFF. This way, custom recipes can be added for tracking purposes, but regular food can still be uploaded to OFF if it is missing.

**Comment by davidhealey** [comment]
Hi, foods are only uploaded when using the barcode scanner. If you want to just add a food locally you can press the + button on the food list page.

**Comment by ubergeek77** [comment]
Oh, ok. Sorry, I didn't see anything that said that, so I just assumed it was the same for anything that was added.

**Comment by davidhealey** [comment]
The user guide needs a lot of improvements and I will be sure to mention this in it when I get around to it.
