### ISSUE TITLE
Would you like a contributors guide document?

### ISSUE THREAD

**Issue by HarryHeights** [davidhealey/waistline#140]
Hello! It's been a long time. Glad to see the project still active. I've since been expecting an upgrade, but it doesn't seem forthcoming though. 
Well, I just wanted to ask if you'll be needing a contributors guide document. This will help prospective contributors and collaborators make proper contributions to the project.

**Comment by davidhealey** [comment]
A guide document is always useful. At the moment I'm refactoring a lot of the code and trying to eliminate little bugs. Development is slow at the moment as I don't have as much free time but the project is very much alive.

**Comment by HarryHeights** [comment]
Oh okay. Great to know that the project is still very much alive. I'll work on the Contributor's guide and send a PR.

**Comment by davidhealey** [comment]
Thanks! I got your PR. I'm holding off merging it until I've finished the latest update I'm working on.
