### ISSUE TITLE
Sodium uploaded to Open Food Facts in grams rather than milligrams

### ISSUE THREAD

**Issue by ogrefriend** [davidhealey/waistline#142]
When submitting to Open Food Facts from the app, submissions reflect sodium in grams rather than the entered milligrams. The units aren't matching up somewhere. Have encountered this issue on all the items I've submitted and gone to the website to fix the entry.

**Comment by davidhealey** [comment]
Thanks. I'm working on a major update at the moment. I'll fix this while I'm at it.

**Comment by davidhealey** [comment]
Done
