### ISSUE TITLE
Back button behavior

### ISSUE THREAD

**Issue by wesaphzt** [davidhealey/waistline#145]
Thank you for all your work on this app, I believe there's a need for a good MyFitnessPal FLOSS alternative.
However, I do find the navigation a bit frustrating as it is.

If you're on a level deeper than one of the main menu items e.g. Foods > Add, the back button works as I'd expect it to, i.e. exiting back to the 'Foods' page.

If I, for example, go to 'Foods', then select 'Diary' and press the back button, I expect it to go back to 'Foods', which I believe is consistent with Android guidelines. Instead, I constantly exit the app accidentally due to habit with all other apps I use.

Looking back through issues, I came across this issue which seems to have reverted common app behavior guidelines:
https://github.com/davidhealey/waistline/issues/21

I believe it's good practice for apps to create a new main activity for each page and temporary activities (e.g. adding a food) with a fragment, or whatever it is these days. So pressing back only goes through the main activities and not every little thing as he mentions in the issue.

If this isn't possible due to onsen or as I think you mentioned, being almost a webapp rather than a native Android app, or as a middleground, can I suggest pressing the back button bring up the menu to prevent unintentional exit, with a subsequent back button press to exit the app?

**Comment by davidhealey** [comment]
Yes with it being a web-app the usual Android architecture (activities) isn't available to me directly. However I should be able to do something about this behaviour.

**Comment by davidhealey** [comment]
This is now resolved in the develop branch and will be available in the next version.
