### ISSUE TITLE
Food thumbnails

### ISSUE THREAD

**Issue by wesaphzt** [davidhealey/waistline#149]
Apologies for the barrage of posts lately, but I feel it's good to add things as I think of or come across them for future development. I'd try and contribute myself if my programming skills were better.
A thumbnail in food lists would improve UX and make it easier to find different foods at a glance.

**Comment by davidhealey** [comment]
I've thought about this too but I don't know how to do it while keeping data usage low. Maybe we could have thumbnails up to a certain data limit or something.

**Comment by wesaphzt** [comment]
Perhaps the default could be to only download them over WiFi, then users could toggle this in the settings if they want to download over their data connection. And maybe cache them on the device to save on data.

**Comment by davidhealey** [comment]
Actually I shouldn't have said data. I meant storage space on the device. I don't know how much storage 100 thumbnails for example would take but I've had complaints before when the app increased in size by a few megabytes...!

**Comment by wesaphzt** [comment]
Retrieving data from OFF they have a variety of image sizes available, the smallest one could be picked for thumbnail use.
A few mb increase in storage space can't be an issue these days! Unless you've got thousands of foods added to your list for some reason I just can't see it being an issue.
Maybe there could be a cache size limit option in the settings menu, say 5-10mb default.

**Comment by davidhealey** [comment]
Yeah a limit setting would be good. I'll look into it

**Comment by davidhealey** [comment]
Thumbnails have now been added, they are only shown when connected to the internet, there is also a setting to only show them when using wifi.
