### ISSUE TITLE
Meal-selector shows JavaScript command instead of label in v1.0.2

### ISSUE THREAD

**Issue by maste9** [davidhealey/waistline#15]
![croppedimage_1528476002852](https://user-images.githubusercontent.com/4653372/41170420-91e6a05e-6b4c-11e8-8e28-204c69b7f4aa.png)
The select field in item view doesn't show proper option label but JavaScript command.

**Comment by davidhealey** [comment]
Hmm that's not happening on my device but I think it's something to do with the new multi-language stuff I added. Is the same thing happening with the menu on the statistics page? What language is your phone set to?

**Comment by davidhealey** [comment]
Thanks. I've fixed the bug now and pushed the change to github. It will be available in the next update on f-droid. I won't make a new release for this just yet, I'll wait to see if any more bugs are found in the current version first. I'll probably push the new release on Monday.

**Comment by maste9** [comment]
Don't get into haste. It's no major bug, app doesn't crash, dialogue works. But the way you develop the app is great. especially looking forward to dark ui :)
