### ISSUE TITLE
Time Stamps timestamps

### ISSUE THREAD

**Issue by ran88dom99** [davidhealey/waistline#152]
I need to track exactly when I ate each food. More granularity allows better statistics. I intend to track glucose and heart rate so the exact time I ate a food matters. Please add feature that instead of snack or dinner write current time date.  Also allow editing the timedate. Set the time to universal time or one specific timezone for users who travel.

**Comment by davidhealey** [comment]
That's quite a specific use case :) I can add a timestamp display to the diary items but it won't be possible to edit the timestamps.

**Comment by davidhealey** [comment]
I've implemented this now, it will be available in the next release. Date and time will be displayed below each diary entry - this has to be enabled in the diary settings and is off by default. You can't change the time stamp but if you edit an entry the time stamp will update to the time the edit was made.

**Comment by ran88dom99** [comment]
This will affect exported data?

**Comment by davidhealey** [comment]
Yeah

**Comment by ran88dom99** [comment]
Is  this a limitation on the Cordova framework?

**Comment by davidhealey** [comment]
> Is this a limitation on the Cordova framework?

Is what a limitation?

**Comment by ran88dom99** [comment]
Editing timestamps. Cordova makes this impossible or is it just alot of work?

**Comment by davidhealey** [comment]
Oh it's totally possible but I haven't implemented. I might do it at some point in the future.

**Comment by ran88dom99** [comment]
line 34 www/activities/diary/views/edit-item.html 
<p><ons-input type="time" id="timeDate" step="any" required="true" placeholder="Time" float ></ons-input></p>

**Comment by davidhealey** [comment]
?

**Comment by ran88dom99** [comment]
When you add time editing this is where it should go.

**Comment by davidhealey** [comment]
Oh ok
