### ISSUE TITLE
Small offline database [Feature Request]

### ISSUE THREAD

**Issue by ran88dom99** [davidhealey/waistline#153]
The entire OFF database is 2.2 GB as SS. What if only key columns were kept for offline search? By key I mean columns that helped search, identify the entry in the larger database, and help user determine if this is the item they meant.  Specifically barcode, name, OFF id, country and maybe manufacturer. also serving size to help logging. About 10% of the whole size. Then when phone went online update each food item and entry. 

By the way is it possible to download the entire OFF database and just store it somewhere and not have the app ever call the online database?

**Comment by davidhealey** [comment]
Hi,

I haven't attempted to use OFF as an offline database so I don't know how big it will be or what is required for implementation. But even 10% of the whole database is a waste of space in my opinion. Most people seem to eat the same things every week, we're creatures of habit :) so once you've scanned all your regular products and built your personal database you don't need to scan things that often and having 10% of a massive database that you probably only require a specific 1% of doesn't seem like a good use of space. But.... there have been a few requests for an offline version so maybe this will happen in the future but I doubt I'll implement it.

**Comment by ran88dom99** [comment]
Hi, 
I suppose you are right.  I could just take a few pictures and a memo.  
However, I am working on a project to quantify as much health data as possible. While you did add micronutrients, I want to track more data off FOO including manufacturer, ingredients, allergens etc. Most of your users will not need that.  So I guess I code my program to fill in all the details from the full online database.

**Comment by davidhealey** [comment]
Yeah it sounds like you need a more specialized application. If you plan to write your app in HTML + Javascript you would probably find the Waistline foodlist.js class helpful.

**Comment by teolemon** [comment]
We have the same issue with the official app :
we have considered segmenting by : country, popularity of product, removing all non essential fields.
For instance, we manage to store NOVA, Nutri-Score, name and brand in around 40mb
