### ISSUE TITLE
Add support for USDA food database

### ISSUE THREAD

**Issue by vilhelmgray** [davidhealey/waistline#154]
The United States Department of Agriculture provides a large database of food nutrient facts based on agricultural and experimental research. It is one of the most comprehensive sets of nutrition data available, and released entirely in the public domain.

- This database may be accessed from the FoodData Central portal: https://fdc.nal.usda.gov/

- An API is provided for developers: https://fdc.nal.usda.gov/api-guide.html

- Alternatively, an offline version of the database is also provided: https://fdc.nal.usda.gov/download-datasets.html

The USDA food database would be an important addition to the Waistline app by providing a food nutrient database derived from academic peer-reviewed research -- something OpenFoodFacts currently lacks unfortunately.

**Comment by davidhealey** [comment]
Yes this looks like it would be useful. I'll see how it can be incorporated into the next version of Waistline alongside OFF.

**Comment by davidhealey** [comment]
Well that API is fiddly. First you have to search for foods, then you have to make individual requests for each food to get the nutritional data. But, I've added it :) and it will be available in the next release, with a setting to turn it on/off

**Comment by vilhelmgray** [comment]
Kudos, that was an incredible turnaround time, less than 24 hours to implementation. :)

**Comment by ran88dom99** [comment]
Wasn't USDA's data inside OFF?

**Comment by vilhelmgray** [comment]
It looks like someone did import the USDA data back in 2017: https://world.openfoodfacts.org/contributor/usda-ndb-import

However, there is still any advantage to having direct access to the database via the FoodData Central API, since we can now have the latest data and updates available direct from the source rather than depend on a copy of it from OFF (which can quickly become out-dated).

**Comment by davidhealey** [comment]
As far as I know all items in OFF have to have a barcode, but not all items in USDA do.

**Comment by dugite-code** [comment]
~~Is this currently implemented at all or been removed? I can't find the setting to enable the USDA API~~

Just realized there hasn't been a release yet since you did work on it. Really looking forward to having the generic foods in the USDA database available.
