### ISSUE TITLE
[bug] adding multiple food does not always work

### ISSUE THREAD

**Issue by MauroMombelli** [davidhealey/waistline#155]
When i select to add to my dinner some food, if i select many, it works fine. but if i select many, then make a search and select another one, click add, and only the one showing in the search result will be added.

This is particularly annoying as I tend to mix up different food in different combinations along the week.

**Comment by davidhealey** [comment]
This is the expected behaviour. If you do a search then the previous list is of foods is replaced with the list of search results so anything you selected in the previous list no-longer exists. I might be able to improve this by attaching the existing list to the search results, but things might get messy if multiple searches are performed one after another. I'll have to look into it.

**Comment by MauroMombelli** [comment]
> but things might get messy if multiple searches are performed one after another

unfortunately this is exactly my use-case.
You may get around it by creating a parallel list of "selected food"; it may get a bit messy the synchronization, i guess if I clean the search box, food in the "selected" list will come on top, as a "fast review" of all you selected. Also by using unique ID and a map instead of a list, may become easy to avoid duplicate.

just some random trough, no idea of the language and architecture you are using

**Comment by davidhealey** [comment]
Ah a separate list of selected foods sounds like a more practicable solution. But this may create another issue, when you do a search the foods returned don't exist as food items, it's just a formatted list of the results from OFF, unlike foods in you local DB. So if you were to select some of these pseudo foods and then do another search things get messy again. I think the solution here would be to temporarily store selected searched foods when another search is performed. I'll have to play around with this.

**Comment by EmilJunker** [comment]
This feature was implemented in version 3.0.0, so I think this issue can be closed now.
