### ISSUE TITLE
[Feature request] when an item is scanned, add it immediately to the meal list

### ISSUE THREAD

**Issue by MauroMombelli** [davidhealey/waistline#156]
when i scan an item, due to bug #151 nothing really happen; i GUESS it would put it on top of the list, to be selected.

I would like instead that it get automatically added to the meal.

**Comment by davidhealey** [comment]
#151 is fixed already for the next release :)

When you scan an item it will open the item editor (so you can check that the results from OFF match the product in your hand). Then you click submit and it will add it to the top of the food list. From there you can add it to your meal/recipe/diary.
