### ISSUE TITLE
[Feature request] better portion handling

### ISSUE THREAD

**Issue by MauroMombelli** [davidhealey/waistline#157]
I often change my recipe and mix different food in different quantity;
editing every time the food (especially because of bug #151 , the values are not updated until you exit and reopen the add food view) is painful, would be so much easier if there was a little popup for each food to ask for the porting you want, or maybe an editable field in the list.

This is similar to #51 but want to improve as I basically edit the portion every lunch

**Comment by davidhealey** [comment]
This will be improved in the next release
