### ISSUE TITLE
[Feature request] Ability to "create" recipe by scanning ingredients back to back 

### ISSUE THREAD

**Issue by serpico** [davidhealey/waistline#161]
![Screenshot_2019-06-05-19-59-03](https://user-images.githubusercontent.com/1227077/58978912-288ebf80-87cd-11e9-8846-9c055907a50c.png)

I might have missed something though, could be a duplicate/enhancement of #156, #151...

Add the scanning button to this view or somewhere after tapping the + button and in the "recipe creating workflow" allow the user to scan one product --> enter the amount --> validate --> scan the next product --> rinse and repeat for all the ingredients of the recipe.

It might be much faster, less tedious than looking up each and every one of the ingredients in the search bar.

**Comment by davidhealey** [comment]
I don't think this is a duplicate. I'll label it as a feature request.

**Comment by serpico** [comment]
Great!!! kudos for the work btw :)
