### ISSUE TITLE
Location assumption can be wrong when VPN active

### ISSUE THREAD

**Issue by wdbm** [davidhealey/waistline#163]
Hey there, love the app! I noticed on uploading to the Open Food Facts database that Waistline makes the assumption that the item is available at the location it detects via the internet connection of the device. While running a VPN connection (which I do continuously) this results in incorrect location data being submitted to the database. A workaround just now is to disable the VPN before adding the item for upload, but it would be good for your app to make a guess at the location and then add this to a pre-filled field on the "Add Food" page so that a user can change or remove the location manually if necessary. Thanks!

**Comment by davidhealey** [comment]
Hi,

Actually Waistline doesn't upload any location info, I think this is done automatically by OFF when they receive an upload request. However the next version of Waistline will allow you to specify an upload country.

**Comment by davidhealey** [comment]
Done https://github.com/davidhealey/waistline/commit/2ea48e6fb14e4d18b5482cd002ef1da356b298b3
