### ISSUE TITLE
Set up translation with fastlane support?

### ISSUE THREAD

**Issue by comradekingu** [davidhealey/waistline#165]
There are a few apps of similar type on Hosted Weblate, would be happy to contribute.
Having changelog/translations/description set up helps with inclusion in "Latest" on F-Droid :)
https://weblate.org/hosting/free/
http://docs.weblate.org/en/latest/formats.html
https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy

**Comment by davidhealey** [comment]
I'm not working on Waistline at the moment, but when I get back to it I'll look at those links

**Comment by yarons** [comment]
Hey @comradekingu!
There's already a Crowdin integration but it's not perfect so it could be a refreshing change when it'll be discussed again.

BTW @davidhealy, seriously? What happened? Your app leads many great contributors into open food facts and these guys love your project!

**Comment by comradekingu** [comment]
@yarons 
Heia, I refuse to use Crowdin, at all. :)

**Comment by davidhealey** [comment]
> BTW @davidhealy, seriously? What happened? Your app leads many great contributors into open food facts and these guys love your project!

I'm just busy with other projects at the moment (the ones that pay the bills ;) ) but I did about three weeks of dedicated work on Waistline last month on this branch - https://github.com/davidhealey/waistline/tree/v2.5

It's still very buggy and needs some more features adding. As soon as I have free time I will continue with it.
