### ISSUE TITLE
[Feature request] Ability to quickly add one time calorie consumption

### ISSUE THREAD

**Issue by serpico** [davidhealey/waistline#167]
In something similar to "Quick add" ( don't know exactly the designation in the English UI - see screenshot ) already present which allow user to add a specific calorie intake straight up with an amount ( no food, no meal, no recipe, just a calorie amount ).

User could specify an "extra" calories "expenditure" due to a specific workout, many apps, services provide such a number ( Strava, AAT,... ) after completing a physical activity ( bike ride, run, walk....) 

![Screenshot_2019-06-19-02-24-46](https://user-images.githubusercontent.com/1227077/59728542-d0c76e00-923a-11e9-9b17-3fd78430d763.png)

**Comment by davidhealey** [comment]
I think you can already do this, just enter a negative amount. Like -100.

**Comment by serpico** [comment]
@davidhealey that'd be nifty, :D unfortunately I don't have the minus sign on the numeric keypad, as you can see in the screenshot above.
I also tried to copy -350 and 350- from two different calculator apps and and paste them on the field but the - ( minus sign ) won't be pasted ( 350 only...)

I'm using a Samsung SM-G361F
Android 5.1.1 if it matters

**Comment by davidhealey** [comment]
No minus sign, that's weird :p I could add a check box or something to make the value negative.

**Comment by serpico** [comment]
> No minus sign, that's weird :p I could add a check box or something to make the value negative.

Yeah, whatever works for you.
I don't know how accurate/significant those values provided by fitness apps are but if I ride for two hours/run a few kms it must amount for something in my energy consumption...it'd be cool to be able take that into consideration in waistline.
Thanks

**Comment by ran88dom99** [comment]
You might want a more proper app specifically for exercise.

**Comment by kevinkoster** [comment]
I use this feature quite often, but it would be nice if it were possible to edit the name. :)
I.e. renaming the "Nan Quick Add"  to whatever you like.

**Comment by davidhealey** [comment]
> I use this feature quite often, but it would be nice if it were possible to edit the name. :)
> I.e. renaming the "Nan Quick Add" to whatever you like.

Already implemented in the development branch and will be available in the next release.
