### ISSUE TITLE
Food Edit not working

### ISSUE THREAD

**Issue by lobneroO** [davidhealey/waistline#169]
When going to the Foods tabs, holding own on a food, changing the unit and then hitting the tick in the upper right corner, the changes aren't saved.

Specifically I had the entry ", ml" in there, out of which I wanted to remove the comma and the whitespace to just have "ml" left.

The item was originally entered through the OpenFoodFacts database, but I assume that doesn't really matter, once it was added to one's food list.

**Comment by lobneroO** [comment]
Apperantly, the changes were safed, but it was only displayed after I left the Foods tab once and went to another tab. Then back at the food tab everything is as it should be.

**Comment by derivator** [comment]
Can confirm, edits and even newly added foods only appear after reopening the foods tab.

**Comment by h-h-h-h** [comment]
Yeah, this is the bug that needs to be solved. After adding or editing a food, the displayed list must be refreshed.

Currently, as a workaround, however, it's enough for me, being in the food view, to tap the food view entry. No need to visit another view intermediately.

**Comment by davidhealey** [comment]
Noted. I think this bug is already fixed in the development branch.

**Comment by theErikss0n** [comment]
When do you plan on releasing this fix?

**Comment by davidhealey** [comment]
The next release will be a major upgrade. I'm using a new GUI library and replacing a lot of the old code to bring performance increases and additional features. When will it be released is a question I don't have an answer for. I work on this in my spare time, usually at weekends, but development has been very slow over the last year as I haven't had much free time. I hope to get a new release ready over the summer.

**Comment by davidhealey** [comment]
This bug is fixed and will be available in the next release sometime in the next few weeks - months.
