### ISSUE TITLE
App Crashes when Abort Barcode Food Scan 

### ISSUE THREAD

**Issue by PaintFoxV** [davidhealey/waistline#170]
How to Reproduce:

1. Open Waistline
2. Go to Food
3. Tap the Barcode Symbol
4. Abort the Scan by tapping Back on the Phone

= App Crashes

**Comment by davidhealey** [comment]
Thanks for the report, I'll fix it for the next release.

**Comment by davidhealey** [comment]
Should be fixed in next release, but let me know if it works on your device

**Comment by EmilJunker** [comment]
I cannot reproduce this in the latest version, so it seems to be fixed indeed.
