### ISSUE TITLE
Food servings + details

### ISSUE THREAD

**Issue by PaintFoxV** [davidhealey/waistline#173]
Hi,

i tested the app so far but i miss the feature to add servings to the food. 
As Example you eat an Apple and now the Apple has a weight of 40g, but the local database has just the entry for 100g you have to re-enter the whole food just because it has another portion. It would be nice if it would be possible to add Servings to foods as Example for Milk 1 Glass, 1 Bottle etc. 
Also i miss to view Details of the Food.

**Comment by davidhealey** [comment]
If you tap and hold on a food item you can view its details and edit it. If you want it to say 1 apple then you can do that.

**Comment by PaintFoxV** [comment]
Yes  but you cant edit the Item in the Diary.
Example: 
You have in your Food List 250ml of Milk. 
Then you drink 300ml. You cant enter 300ml of Milk to your diary. You can only edit the base item(in Food List) or work with 100ml and enter 3 Servings/Portions. But what about 375ml?

**Comment by davidhealey** [comment]
3.75 servings @ 100ml :p

I understand the issue. This has actually been solved already in the source code and will be available in the next release.

**Comment by PaintFoxV** [comment]
yeah but im to stupid to remember all servings :D 

When is the new Release planned?

**Comment by davidhealey** [comment]
When it's ready. I work on it in my spare time so I can't say exactly when. It's almost complete but will require another couple of weeks of work I think, but at the moment I'm not working on it as I'm too busy. Hopefully I'll get back to it in the next few months.
