### ISSUE TITLE
[feature] food tastiness tracking

### ISSUE THREAD

**Issue by ran88dom99** [davidhealey/waistline#176]
Sometimes what I really want to do is record how much i liked a specific food. 0-9. Auto default rating is most common rating for that food .Automatically set to 5 if user did not set any ratings for that food.

**Comment by PopeRigby** [comment]
That's kind of an interesting idea. To add on, I commonly get acid reflux, and a way to track which meal or food potentially triggered it would be helpful. Maybe a custom setting for foods or something like that could help with cases like this?

**Comment by davidhealey** [comment]
How about a smiley/frowny face?

**Comment by ran88dom99** [comment]
Your specific problem would be better served by notes. Such as acid-3 for acid reflux of strength 3. no note means no reflux. Analysis should outside the app imho. Better export to Py R as writing the code to show this info would take about 10 minutes.

**Comment by PopeRigby** [comment]
Smiley/frownies could work. Then you could have multiple sets of them for different things "acid reflux triggering, tasty, etc."

**Comment by ran88dom99** [comment]
Tastiness at least needs greater granularity.

**Comment by PopeRigby** [comment]
So you could have multiple types of trackers. Maybe a face one and a 1-10 scale one.

**Comment by davidhealey** [comment]
Yeah I'm sure something along those lines is possible

**Comment by ran88dom99** [comment]
Please do no think this is more important than a "notes" feature. Like I showed this feature and a bunch of others not yet thought of can be clumsily performed by a "notes" section and exporting to some R Py code.

**Comment by seniorm0ment** [comment]
This could be implemented with a Custom Fields option so users could input their own interests.
