### ISSUE TITLE
[Feature request] Ability to add custom fields to food items

### ISSUE THREAD

**Issue by wdbm** [davidhealey/waistline#178]
When adding a food item, there are various fields for specification of nutritional content, such as fat, carbohydrates, protein etc. Since these fields don't cover many characteristics of foods I think it would be useful to be able to add custom fields with custom units, e.g. grams of alcohol.

This might be workable only for local and JSON export use, as there could be limitations for uploading to the Open Food Facts database (or perhaps such fields could be excluded from upload to OFF).

Adding a custom field could potentially be used for feature requests #41 and #176 too.

**Comment by davidhealey** [comment]
The current develop branch has almost all of the nutriments available in OFF, with their corresponding OFF units.

"calories", "proteins", "carbohydrates","fat", "saturated-fat", "monounsaturated-fat", "polyunsaturated-fat", "trans-fat", "omega-3-fat", "cholesterol", "sugars", "fiber", "sodium", "salt", "potassium","vitamin-a", "vitamin-d", "vitamin-e", "vitamin-k", "vitamin-c", "vitamin-b1", "vitamin-b2", "vitamin-b6", "vitamin-b9", "vitamin-b12", "chloride", "calcium", "iron", "magnesium", "zinc", "caffeine", "alcohol", "sucrose", "glucose", "fructose", "lactose"

How do you envision the custom fields being applied, would it be for every food item or you can add a custom field to individual items if you want?

**Comment by wdbm** [comment]
Ah, thanks for the details on the develop branch. That actually covers much of what I'd want to record so I look forward to it.

Regarding a custom field, I had envisaged it as something that could be part of a page like the "Edit Food" page, like after the "Salt (g)" field. There could be two approaches to it.

A more elaborate approach could be to have a heading like "Custom measurement (local only, not uploadable to Open Food Facts)" and then under it *three* fields: "Name", "Value", "Unit". This custom measurement gets saved as a characteristic of the food item.

A simpler approach could be to have a "Note" field, which is basically just a string of text that gets saved to the food item, would be exported to JSON etc.

The second approach is arguably better because it could be used for #41 and #176 and, in my case, I could actually put a number of measurements into the note string and then it's my job to parse them from the JSON.

**Comment by ran88dom99** [comment]
I would like notes to also be by the eating not only the food. I will want to track things other people do not care about.

**Comment by davidhealey** [comment]
> I would like notes to also be by the eating not only the food. I will want to track things other people do not care about.

I don't quite understand. Could you give me an example?

**Comment by ran88dom99** [comment]
I like almonds of a specific brand and buy them from only one store. Notes on almonds the food would include brand if its not already in the name and the store as well.  At other times I need something unique to this set of almonds like they fell on the floor.

**Comment by davidhealey** [comment]
Brand is already there, but I suppose store could be added. I'm definitely leaning more towards a generic notes field for this.

**Comment by prysm1** [comment]
i second the generic notes field. I have been using the Serving Unit field to show volume to weight conversion example instead of just "g" for grams. I put "g (1cup/158g)"

**Comment by davidhealey** [comment]
I've added a generic notes field to the food editor now (haven't tested it with uploading, but it should just be ignored) https://github.com/davidhealey/waistline/commit/5be7c43fc9933e12c7818016d41c9bb864877b96
