### ISSUE TITLE
More thorough goals display

### ISSUE THREAD

**Issue by norcimoix** [davidhealey/waistline#179]
It would be helpful if todays nutrient goals are more completely displayed. Currently you can only really see your calorie goal and how many remaining calories you have left. It's very hard to keep track of your macros only from the displayed graph in statistics.

Ideally I'd like to see fat/carbs/protein so far today and remaining towards the goal. Perhaps display only those goals that are configured. The information could be hidden by default until you swipe the current calorie goal display in dairy up and permanently visible in the statistics window?

This issue is related to #88 which seems to be a similar request.

**Comment by davidhealey** [comment]
This is already implemented in the develop branch and will be available in the next release. It will look something like...
![Peek 2019-08-12 17-30](https://user-images.githubusercontent.com/14021202/62881152-ffd3fa80-bd26-11e9-9e0a-629006b4bdf7.gif)

**Comment by norcimoix** [comment]
That is really nice and pretty much exactly what I was talking about. I guess this issue can be closed then. Is the development branch available somewhere? I wouldn't mind compiling and testing it out locally.

**Comment by davidhealey** [comment]
Ya - https://github.com/davidhealey/waistline/tree/v2.5

It's quite buggy and missing lots features that the stable version has as I'm replacing all the jQuery stuff with vanilla JS.
