### ISSUE TITLE
Logo Proposal For Waistline

### ISSUE THREAD

**Issue by mayowadavid** [davidhealey/waistline#18]
Hello @davidhealey 
I  came across this application on play store, it is a wonderful app. I intend to contribute to the project after i noticed it is an open source application. Below is what i came up with, i believe it will help communicate what waist line application is all about. If you like it, i will send both editable and other size you need. Incase you want a different color, i will provide it as soon as possible.
![icon-calorie-counter-1](https://user-images.githubusercontent.com/34623610/41418673-1ed86606-6fe8-11e8-8993-51c23943316c.png)
![icon-calorie-counter-block](https://user-images.githubusercontent.com/34623610/41418696-2fa5500c-6fe8-11e8-9f51-6f6b9e6ece8e.png)

![icon-calorie-counter-gray-1](https://user-images.githubusercontent.com/34623610/41418106-f904e978-6fe6-11e8-9558-48af4637eee7.png)
![icon-calorie-counter-block-2](https://user-images.githubusercontent.com/34623610/41418128-032a1018-6fe7-11e8-9019-2c8719276b17.png)

**Comment by davidhealey** [comment]
Hi,
Thank you for your enthusiasm :) I've actually just had the logo and splash screen redesigned, I haven't updated the play store yet but the version on F-Droid has the latest graphics.

![96x96](https://user-images.githubusercontent.com/14021202/41420214-df134da2-6feb-11e8-976d-326f8560c0ae.png)

**Comment by mayowadavid** [comment]
am glad you already made a new design
