### ISSUE TITLE
Feature request: option to measure energy in kilojoules (kJ)

### ISSUE THREAD

**Issue by ikanakova** [davidhealey/waistline#180]
It would be great to have the option to measure energy in units of kilojoules (kJ) rather than calories.

**Comment by davidhealey** [comment]
Seems a reasonable suggestion and should be easy to implement. I'll add it to the list.

**Comment by SpaceyPuppy** [comment]
I'd love to see this change as a settings option. Here in Aus almost everything is kJ/100g rather than kcal.

**Comment by davidhealey** [comment]
I've added this now in the develpment branch. Both Kilojoules and KCalories are recorded in the food editor and you can choose which one you prefer to see displayed in the diary and foodlist. It's also possible to set kJ as a goal.
