### ISSUE TITLE
Hard to search in different country (language)

### ISSUE THREAD

**Issue by mmm4m5m** [davidhealey/waistline#181]
I would like easy way to search in different language or country. 

For example in "foods" screen, next to "search food" box, I would like a "country" box. Simply a check-box "all countries" could be easy and could help but it will not be good enough.

If my country is Russia, if search do not have good results, if my food product is imported from another country, then it is hard to 1) change country, 2) search by English food name and 3) restore country back to Russia.

Thanks!

**Comment by davidhealey** [comment]
Hi,,

This feature is already implemented in the develop branch and will be available in the next release.
