### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by darkhamaus** [davidhealey/waistline#182]
Can't make the app work. Be it adding calories or food it doesn't work. Not sure where the issue comes from, maybe a missing library or something ? I'm running LineageOS 14.1 (Android 7.1.2) without Gapps or alike.

**Comment by davidhealey** [comment]
I'll need more information. Can you share a video demonstrating what happens when you try to log a food item?

**Comment by darkhamaus** [comment]
Of course, here you are ! (Put the .mp4 in a .zip archive in order for it to be attached directly)
[recording.zip](https://github.com/davidhealey/waistline/files/3587686/recording.zip)

**Comment by davidhealey** [comment]
Thanks for sending the video.

I wasn't able to tell the problem with the quick add calories from that video but with adding a food it looked like you were just adding the food to the food list and not to the diary. Once the food is in the food list you just need to tap it to add to the diary, you don't need to edit it. Have a look in the user manual and see if that explains it better.

**Comment by darkhamaus** [comment]
Be it the diary or the food list doesn't make a difference, the input doesn't appear either way

**Comment by davidhealey** [comment]
What make/model is your phone?

**Comment by darkhamaus** [comment]
Sony Xperia M / C1905 / Nicki

**Comment by davidhealey** [comment]
I'm not sure how to resolve this as I don't have access to that device. The next update, when it comes out, will have some significant changes so hopefully it will work on your device too.

**Comment by darkhamaus** [comment]
Okay thanks anyway, I'll make sure to test it when it comes out ! Nobody's gonna make me go back to MyFitnessPal and alike

**Comment by davidhealey** [comment]
I'm pushing test version to this issue - https://github.com/davidhealey/waistline/issues/217 - so if you want to test I suggest you download from there. A new release should be out soon though.

**Comment by davidhealey** [comment]
I'm closing this issue now. If the problem persists for you please make a new issue.
