### ISSUE TITLE
Option for switching off barcode scanning sound

### ISSUE THREAD

**Issue by mahlzahn** [davidhealey/waistline#183]
Loud beep is unexpected for such an app and might be annoying …

**Comment by davidhealey** [comment]
Note to self - https://stackoverflow.com/questions/40984987/how-to-disable-beep-on-phonegap-plugin-barcodescanner-meteor-and-cordova

**Comment by davidhealey** [comment]
https://github.com/davidhealey/waistline/commit/64ab332ea6fa50b95d4bc34ad7f833d01bc54e3d
https://github.com/davidhealey/waistline/commit/c5c9fb8e64df093eb95d5a66a8203c4712b6dbe5
