### ISSUE TITLE
[feature-request] Partial loading of foods

### ISSUE THREAD

**Issue by faan11** [davidhealey/waistline#184]
I use quite often this application since 1 year. I find it useful and I added many types of foods. Right now if I open the food list, it takes time. It might be useful to load partially the list of foods.

**Comment by davidhealey** [comment]
Yeah I hit the same issue. The latest development version does what's called lazy loading where it only loads the items that are being displayed, this greatly speeds things up. It will be available in the next release (whenever that might be).

**Comment by davidhealey** [comment]
This is now fully implemented in the framework7 development branch and will be available in the next release (2021)
