### ISSUE TITLE
Can't connect OFF account

### ISSUE THREAD

**Issue by kevinkoster** [davidhealey/waistline#193]
If I go to settings -> open food facts accounts, I expect a keyboard popup to enter my username and password. Instead, when I click the user ID entry, it returns to the main settings menu.
Long pressing the entry is possible, but this way I can only select "paste" (from my clipboard?).

**Comment by davidhealey** [comment]
I think this is broken in the latest release but it has been fixed in the current develop branch (which hasn't been released yet because it's not finished).

**Comment by kevinkoster** [comment]
Ok, just wanted to let you know.

**Comment by natrius** [comment]
I hope there will be a new version soon :)

Thanks for your work.

**Comment by davidhealey** [comment]
> I hope there will be a new version soon :)

As soon as I get some free time :)
