### ISSUE TITLE
[feature-request] Amount in grams vs portion size

### ISSUE THREAD

**Issue by kevinkoster** [davidhealey/waistline#194]
It behaves a little bit weird with respect to portion sizes.

For example I added 8718906821934, which doesn't have a portion size listed on OFF, so 1 portion = 100 g. I ate 40g, so enter 0.4 servings. Does the job, but the option of entering the amount in either grams or portions, whichever the user prefers, would be cleaner.

When the item has a portion size listed, it becomes more annoying. E.g. item 8718265831179 had portion size 125g. I ate 200g, so I have to calculate 200 g / 125 g = 1.6 portions and enter that. It would be easier if I could choose to between entering enter 200g directly or a certain number of portions.

Also regarding portion sizes: when adding food to OFF trough waistline, I'd like to enter the nutritional info per 100 g or ml, so I enter units 'ml' and size '100', but now it implies that one serving is also 100 ml, even if a normal serving size would be 250 ml, so I suggest to keep the units and size for nutritional info, but adding a separate entry for the serving size and units.

**Comment by davidhealey** [comment]
I think these issues have been resolved in the develop branch, but I will check next time I'm working on it.

**Comment by kevinkoster** [comment]
Cool, keep up the good work!
Are you planning on releasing a new version soon or should I look into how Cordova and OnsenUI work and try to make an apk myself? Is it the v2.5 branch?

**Comment by davidhealey** [comment]
I'd like to get it released before Christmas but it's unlikely that will happen as I have too much work on at the moment, so probably not until next year. Yes it's the 2.5 branch although I'm not sure if I've pushed all my local commits to it yet. It's still on Onsen but the reason I stopped development when I did is because I hit a roadblock with Onsen and was waiting for the Onsen devs to find a solution and when they got back to me they basically said it won't be resolved. So I'm going to transfer to a different UI framework, probably framework 7.

**Comment by rendeko** [comment]
I'd like to bump this. I know you are currently rewriting with a new framework, but imo is this a necessary feature. Waistline is fantastic and can almost completely replace proprietary food tracking apps, but the extra equation I need to do per-ingredient is the one thing holding me back. Aside from that it is everything I could want in a food tracking app.

Very excited for the new release!

**Comment by davidhealey** [comment]
The portion/serving thing is resolved in the latest develop branch, the portion vs nutritional info is still on my todo list but probably won't be something in the next release, but the release after that.

**Comment by davidhealey** [comment]
The portion/nutrition thing will be in the next release, in fact it's already in the development version. I just copied the system from the open food facts app so you can select whether the nutrients are per serving or per 100g.
