### ISSUE TITLE
[feature-request] speed up flow

### ISSUE THREAD

**Issue by kevinkoster** [davidhealey/waistline#195]
After scanning a barcode, it adds the food to my local database. Now to add the food to my diary, I have to search for the food by using the search box. It would be nice to combine these two, e.g. by adding a checkbox "add to diary" to speed things up. For example:

Scan barcode -> 
If already in local DB -> instantly add to diary (done!)
else if in OFF db -> Show 'add food' menu + checkbox 'add to diary' -> done!
else -> Show 'product not found', 'add to OFF db' popup -> enter nutritional info and photo's + checkbox to 'add to local foods' + checkbox to 'add to diary' -> done!

Right now if a product doesn't exist yet, the process is: scanning -> adding to OFF, scanning again -> adding to local db, searching in searchbox -> adding to diary; quite a lot of steps.

**Comment by davidhealey** [comment]
Yep, already solved in the develop branch too :)

**Comment by kevinkoster** [comment]
Awesome!
