### ISSUE TITLE
persistent graph settings in statistics

### ISSUE THREAD

**Issue by gck0** [davidhealey/waistline#196]
when in statistics, you can select 'calories' 'protein' 'carbohydrates' etc. to show the related values on the chart.
after that, when you go back and open statistics again or switch between the time interval, it always resets the chart and shows only 'calories', so you have to change it every time to see the other stats on the chart.

it is possible to have it to be persistent?

**Comment by davidhealey** [comment]
Good idea. I'll add it to the list.

**Comment by davidhealey** [comment]
Done
