### ISSUE TITLE
Adding food on foodlist doesn't work

### ISSUE THREAD

**Issue by kodeblacc** [davidhealey/waistline#2]
#### Expected behavior
Foodlist can be manually created. It is expected that after a food type and adequate information of the food has been inputted and saved, it'll be available for latter utility.
#### Actual behavior
After the form filled with details of the food to be added has been saved, it doesn't appear on the food list. 
#### How to reproduce
- Launch [Waistline app
-  Select foodlist 
-  click the + sign at the top right to add a food to the foodlist
- enter food information and click save <hr>
* App name/App version: Waistline v1.0.0
* Operating system:  Android 7.0
#### Recording Of The Bug
https://youtu.be/mwcH4Vqjqq0

**Comment by davidhealey** [comment]
Hi, thanks for the video. I'm running Android 7 too but this bug isn't present for me. Let's see if more people report this. Also the code has been updated since that version so I imagine an update will be available on fdroid soon, although I'm not sure how it will affect this particular issue.

**Comment by kodeblacc** [comment]
Okay. I'm expecting the update.

**Comment by kylesorkness** [comment]
I am experiencing the same issue. I am running Version 1.0.2 on Android 5.1.1.

**Comment by davidhealey** [comment]
I've pushed the latest version to play and it should be on f-droid in the next few days. Please let me know if this issue is resolved

**Comment by davidhealey** [comment]
I'm going to close this issue since no-one else has reported it with the new version, will reopen if someone finds it's still happening.
