### ISSUE TITLE
All data disappeared

### ISSUE THREAD

**Issue by marclebrun** [davidhealey/waistline#201]
My mate's using version 2.4.2 for logging his daily weight and calories, and today all his data disappeared from the app.
He doesn't have any backup of it.
Is there something I can check on his phone to try and restore his data ?
Phone is Huawei P20 Lite.
Thanks

**Comment by davidhealey** [comment]
Hi,
I wonder what caused the data to be wiped. Did he do an update or install a new app? Or clear the app's data?

You can check the app's directory to see if there is any backup data in there, just in case, but other than that I can't think of another solution. 

Maybe I'll add an auto-backup feature that will run once a week or something.

**Comment by marclebrun** [comment]
No, he says he didn't update or install anything today.
Is the data stored in a browser's IndexedDB ? I've been looking for a way to recover that but i have no experience with that. I don't know how Cordova works...
What's the path to the app's directory ?

**Comment by davidhealey** [comment]
I don't know if it stores it in the generic browser's DB or if it will use it's own internal browser DB.

The data location is Android/data/com.waist.line/files/

**Comment by DenisInChelmsford** [comment]
Strange, all my data just disappeared too, about the same time -  never happened before. Like first poster, I didn't install or update anything before. The only thing in my data location is my last backup several months ago. I guess I'll back up more frequently.

**Comment by chk1** [comment]
Same thing for me, I tried restoring a backup from April with Titanium Backup but the app just starts up empty.
One of my recent app updates, according to Google Play, includes the Android Webview. No other system app updates. Xiaomi Redmi 4X, LineageOS 16 (Android 9.0)

**Comment by davidhealey** [comment]
> edit: Found this: "Issue 1033655: localstorage or websql unexpectedly cleared" https://bugs.chromium.org/p/chromium/issues/detail?id=1033655
> Does it apply here?

I think you've solved the mystery. Can you check your chrome/webview version?

Waistline doesn't use MySQL it uses IndexedDB (and local storage for non critical settings), but that bug report you linked to says it also affects IndexedDB data and people are complaining about their Cordova app's data being wiped. So it seems this problem has been caused by a recent update. 

I haven't experienced the issue on my phone yet, probably because I use an older version of Android and don't have the latest updates to web view.

I'll be sure to include an auto-backup system, or one click backup reminder, in future versions of Waistline, and I'll see if I can get the backup placed in a more user friendly file location.

**Comment by chk1** [comment]
My app info screen in settings shows version `79.0.3945.79` for `com.google.android.webview` (I don't use the standalone Chrome browser app)
![image](https://user-images.githubusercontent.com/828496/70866938-ddb9e580-1f6f-11ea-9ce7-e809a4f431bd.png)

**Comment by chk1** [comment]
Over at the cordova-android issue tracker dpesch posted a workaround: https://github.com/apache/cordova-android/issues/885

Following this, to work around this issue at this point, you can move some files around to make the app work again. This is unfortunately probably not possible for people who don't have rooted their phones.
In `/data/data/com.waist.line/app_webview` create a folder `Default`. Move `databases`, `Local Storage` and `IndexedDB` into the newly created `Default` folder.

**Comment by davidhealey** [comment]
That confirms it. The bug report says it is caused by v79 on Android 9 and 10. Also explains why I haven't experienced it.

It seems Google are working on a solution. I think the problem has been caused because they've changed the way the data is accessed, but it hasn't been wiped (although I could be wrong).

**Comment by davidhealey** [comment]
> Over at the cordova-android issue tracker dpesch posted a workaround: [apache/cordova-android#885](https://github.com/apache/cordova-android/issues/885)
> 
> Following this, to work around this issue at this point, you can move some files around to make the app work again. This is unfortunately probably not possible for people who don't have rooted their phones.
> In `/data/data/com.waist.line/app_webview` create a folder `Default`. Move `databases`, `Local Storage` and `IndexedDB` into the newly created `Default` folder.

Excellent, this proves the data is still there :) so hopefully when Google issue a fix everyone's data will reappear.

**Comment by dpesch** [comment]
> […]. This is unfortunately probably not possible for people who don't have rooted their phones.

My patch does not need root access, if the app copies the data! The app (Android MainActivity) can copy the files, because they are in the app's data directory.

**Comment by chk1** [comment]
@dpesch Thanks for chiming in and for the patch :)
What I wanted to say is that root is required if you want to edit files and folders in `/data/data` manually (if you don't want to or can't wait for a patch). 
Yes applying the patch to the app and then using that should work for everyone.
