### ISSUE TITLE
Auto-backup

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#202]
Implement an auto xml backup at a set interval, triggered by the app being opened.

**Comment by natrius** [comment]
Please let us choose the location on our own or at least get a specific folder so i can add it to autoupload to my nextcloud instance, for example. Thanks for your work.

**Comment by davidhealey** [comment]
Autobackup has been added now. Every time you open the app it will make a backup of the database. This is now saved in /home/waistline (or whatever the android equivalent of that is).
