### ISSUE TITLE
search bar in "food" does not search in OpenFoodFacts 

### ISSUE THREAD

**Issue by fl0r1s** [davidhealey/waistline#205]
When searching for a food it only searches locally (and I don't have any entries yet). I can scan to search OpenFoodFacts.

Phone: xiaomi mi8se
OS: Pixel Experience

**Comment by davidhealey** [comment]
I think you need to select a country in the settings screen otherwise it doesn't know which locale to search.

**Comment by fl0r1s** [comment]
Thanks. Can this maybe be added to the readme.md file? Nice app!

**Comment by Ferk** [comment]
> otherwise it doesn't know which locale to search

I might be saying something wrong.. but wouldn't it be possible to use the locale from the Android system? (ie. `getResources().getConfiguration().locale`)

**Comment by davidhealey** [comment]
We could use that as default but it also has to have a manual setting because you might move between different countries.

The next version will have a setup screen for first time use and will prompt you to select a search locale.
