### ISSUE TITLE
Bug: Fails to detect internet availability

### ISSUE THREAD

**Issue by Blechpirat** [davidhealey/waistline#208]
When Waistline was running in the background for a while (lineageOS 16.0 with micro-G) using the barcode scanner tells me that there is no internet available. Restarting the app solves that problem.

BTW: Great app, thank you, love using it!

**Comment by davidhealey** [comment]
Thanks for the report, I'll add it to the list.

**Comment by davidhealey** [comment]
I haven't been able to recreate this, do you have the steps to reproduce it reliably?

**Comment by davidhealey** [comment]
I'm closing this issue since I can't reproduce it and therefore can't confirm any fixes I attempt.
