### ISSUE TITLE
Back navigation hell

### ISSUE THREAD

**Issue by AeliusSaionji** [davidhealey/waistline#21]
This is a problem with Android's design philosophy in general, but the problem is particularly painful in this app.

When I press the system back button, I expect to navigate up a level in the flow of your app. Instead, it navigate to every single sub page that I have visited in the course of using the app, even in orders that don't make sense, even bring me back to edit pages that I should not be seeing again.

You have a main page and you have (iirc) one layer of subpages. From any subpage in the app, the back button should bring me back to the main page, and from the main page, the back button should exit the app.

Thanks!

**Comment by davidhealey** [comment]
I agree, it is very frustrating. As far as I know there is not much I can do about it, but I will look into it further. Basically my app is just a webpage pretending to be a native app so much of the standard android behavior has to be recreated in a hacky kind of way.

**Comment by davidhealey** [comment]
This is fixed in the onsen-ui branch - which will be merged into the master branch at the next release.
