### ISSUE TITLE
[Feature Request] Macro counter (Protein / Carbs / Fat)

### ISSUE THREAD

**Issue by longestmt** [davidhealey/waistline#210]
I would appreciate the ability to view daily macros in a 'countdown' format so I can track that I'm hitting my goals. The current view in the statistics section with the column chart, while great for viewing trends over time, does not help when trying to hit daily goals. I have to add up the macros individually. A daily tracker would be a beneficial enhancement for people monitoring macros.

Suggestion for how to implement: It would be great to have an option on the daily diary page to toggle between the 'Goal / Used / Remaining' calorie footer and a similarly designed 'Protein / Carbs / Fat' footer. For the macros the numbers could be green if they are yet to be consumed and turn red if there is an overage.

Thank you for this app. While MFP has more features I want to support a libre alternative. I'm not a developer but I have experience in UX design. Let me know if I can help in anyway.

**Comment by davidhealey** [comment]
See #209

Thanks for the offer regarding UX. Let's see what happens with the next version
