### ISSUE TITLE
Support generic foods, such as fruit

### ISSUE THREAD

**Issue by jangop** [davidhealey/waistline#222]
[Open Food Facts](https://openfoodfacts.org/) (to my knowledge) only stores branded products, and, as such, only those can be found through Waistline.

However, the US Departments of Agriculture, which has (as far as I know) contributed much to Open Food Facts, offers its own service including an API: [FoodData Central](https://fdc.nal.usda.gov/).

It would be terrific if we were able to access that data and, for example, find that in [100 g of Banana 🍌](https://fdc.nal.usda.gov/fdc-app.html#/food-details/1102653/nutrients), approximately 89 kcal, 1.9 g of protein, and 2.6 g of dietary fiber are contained. 😊

**Comment by davidhealey** [comment]
USDA is already in the development version which will be available in the next release.
Also #86 #154
