### ISSUE TITLE
Can not add foods to recipes nor meals

### ISSUE THREAD

**Issue by ttimeless** [davidhealey/waistline#224]
When trying to add a component to a meal or recipe it is possible to mark it in the list but the tickmark in the upper right corner wont work and therefore the selection can not be confirmed.

**Comment by davidhealey** [comment]
Is this with meals you've already created?

**Comment by ttimeless** [comment]
I experienced this with entirely new meals. I havent created any so far
(or just empty ones).

David Healey wrote:

**Comment by davidhealey** [comment]
Very strange. Well it's already fixed in the development branch as I've completely rewritten the meal and recipe system and it's now more robust, so it will be working in the next release.
