### ISSUE TITLE
Allow users to look up food from Open Food Facts in app and import them into Waistline

### ISSUE THREAD

**Issue by disobeyedtoast** [davidhealey/waistline#225]
I could have sworn this was a feature in the past, but I may be thinking of a different application. It would be very helpful if you allowed users to look up and import foods from the OFF database by searching for them in the app instead of having to scan a barcode or input it manually.

**Comment by davidhealey** [comment]
Yeah you can do that already, just type it in the search box.

**Comment by disobeyedtoast** [comment]
Oh, then this is a bug.

**Comment by davidhealey** [comment]
Try changing the search country in the foodlist settings.

**Comment by disobeyedtoast** [comment]
ah, that worked. sorry about this
