### ISSUE TITLE
Allow entry of weight or volume when adding an item to diary

### ISSUE THREAD

**Issue by goblin** [davidhealey/waistline#227]
If I see it correctly, currently when adding a food item to your diary, you can only enter the number of servings (which seems to default to 1). This can be tricky when you just weigh how much of each food you eat, as serving sizes can be pretty arbitrary and you have to do tough math in your head.

It would be nice if instead of number of servings you could just input the weight or volume of the consumed food.

**Comment by davidhealey** [comment]
I can't remember how it works in the release version, but in the upcoming version you can adjust but serving size and number of servings.
