### ISSUE TITLE
What is preferred way to translate 2021? 

### ISSUE THREAD

**Issue by huuhaa** [davidhealey/waistline#229]
I checked at crowdin and there seems to be nothing to translate, also many languages at 0%. So what is preferred way to translate your app in 2021?

**Comment by davidhealey** [comment]
Somebody else setup the Crowdin thing and I don't know how it works. But for the time being no-one should be doing any translation until v3 is ready, there will be a lot of differences with the previous version.

**Comment by yarons** [comment]
I'm here, I'm open for modifications if it's not working, I think I've made some mistakes while setting it up.

@davidhealey when can we talk?

**Comment by davidhealey** [comment]
@yarons Send me a message, I'm always around :)

**Comment by huuhaa** [comment]
OK I'll wait here to see if there was some problem which got solved. @yarons you probably will update information here? When everything solved, I will start translating.

**Comment by yarons** [comment]
You can start working, your work will be directly contributed to the repo anyway.

**Comment by davidhealey** [comment]
@huuhaa Don't do any translating until V3 is released. 

@yarons david@librewave.com

**Comment by huuhaa** [comment]
OK, thanks for information, I'll wait for V3 then.

**Comment by huuhaa** [comment]
Just double checking.. I got email couple days ago that there are new strings to be translated at Crowdin, is it based V3 language file or should I still wait and ignore that email?

**Comment by davidhealey** [comment]
> Just double checking.. I got email couple days ago that there are new strings to be translated at Crowdin, is it based V3 language file or should I still wait and ignore that email?

Yes, it's now V3. @yarons helped me set it up. The strings are still subject to change but it should be mainly adding new ones now rather than removing any, so feel free to start translating.
