### ISSUE TITLE
Feature reguest: Add Fineli open data as data source

### ISSUE THREAD

**Issue by huuhaa** [davidhealey/waistline#230]
I think it would be great if Fineli Open Data could be added as data source.

https://fineli.fi/fineli/en/avoin-data

Information about Fineli:

https://fineli.fi/fineli/en/tietoa-palvelusta

Benefits of adding this:

User wouldn't need always scan barcode and going throught the hassle of adding new food. I know this is possible now too, but even then you have to know nutrients of food. By using Fineli as a source, you could just write search word, ex. apple, coffee, chiken etc. and it would find informationd for you and offer list of options including that search word. This together with Open Food Facts would offer wide selection of foods.

Sure as a Finn whos goal is to translate your app to finnish, if Fineli would get added I hope iformation would be searched with language user uses, if there will be some language specific informations.

**Comment by davidhealey** [comment]
Currently you don't "have" to scan a food, you can type in the search as you've suggested. I'm not opposed to adding another data source though. Does Fineli have a web API or is it an offline only database?

**Comment by huuhaa** [comment]
Hmm.. Strange. Now search seems to work, but previously I couldn't find anything, if I writed general item like coffee etc. For that reason I thought search was available only for foods added to local food database.

Anyway I did ask from Fineli about web API.

**Comment by huuhaa** [comment]
I continue this for 2 reasons.

1) I got reply from Fineli and 
2) Eventhought search now does work, Fineli data would still be extremely useful at least in my country (Finland).

**First of all I just place terms of use here first.**

 The use of the material is governed by the terms and conditions specified by license: Creative Commons Attribution 4.0 (CC-BY 4.0). When used, the material or the service including or utilising the material must be accompanied by information on the original source and the date of the current version as follows: National Institute for Health and Welfare, Fineli.

Fineli is registered trademark of National Institute for Health and Welfare. National Institute for Health and Welfare holds the copyright to the Fineli web site and the Fineli database.

**Then to the API case**

Actually there are some simple APIs available, I didn't notice those first cause those are mentioned at Finnish page, not English one which i linked cause I was thinking there's not much use to link Finnish page. Following is my translation of the text atFineli's Finnish page regarding APIs below:

**Fineli API**

Fineli has a few very simple APIs to extract the data it contains

Fineli's nutritional factors https://fineli.fi/fineli/api/v1/components/
Fineli's foods per keyword, e.g. https://fineli.fi/fineli/api/v1/foods?q=apple
Finel foods per food identifier (id),  https://fineli.fi/fineli/api/v1/foods/11060
