### ISSUE TITLE
Diary groups won't show when Diary is set to Start Page

### ISSUE THREAD

**Issue by jfaltis** [davidhealey/waistline#233]
Since commit https://github.com/davidhealey/waistline/commit/c0ceb5346a24092ba8dcbb74f1ae6faaabd67927 the diary groups won't show when the diary is set as Start Page. They only show again when changing the date back and forth.

This is due to splitting the initialization logic into `app.f7.on("init", async function(event) {})` and `document.addEventListener('deviceready', function() {})`

Removing the newly added lines
```
});

document.addEventListener('deviceready', function() {
```
fixes the problem.

**Comment by davidhealey** [comment]
Thanks for the report, I'll fix this before the next build

**Comment by jfaltis** [comment]
I also noticed that in this commit the minSdkVersion changed from 23 to 27. Is this just a temporary/accidental change or whats the reason for only supporting Android 8.1 and above?

**Comment by davidhealey** [comment]
It's temporary. I was having trouble getting the dev version running on one of my devices, but the release version was working fine. The last release version had the minSdk set to v27 so I changed the dev version also to eliminate another variable while I'm debugging the issue.

**Comment by davidhealey** [comment]
Fixed
