### ISSUE TITLE
[Feature Request] Proper support for bilingual products

### ISSUE THREAD

**Issue by 31j** [davidhealey/waistline#239]
When using the bar-code scanner the app arbitrarily picks French in place of English for the name of the product, while this isn't a problem in my case as French is my second language it could be problematic for people in Canada who only speak English (This problem most likely also exists in other multilingual countries). 

Ideally I would either like to have two separate title fields (i.e "Title EN:" and "Titre FR:") similar to how most packaging has both official languages, it would also be nice if the app could add additional titles for some products that also have Chinese, Arabic etc. I am however unsure if this is a fault of the database you're using for the app or if the app is picking a language randomly?

**Comment by davidhealey** [comment]
What did you set your search country to?

**Comment by 31j** [comment]
I set it to Canada. I also attached some examples. Is there any way to handle the language automatically? The other thought I had is basing it off of the system language so the user is presented with data in the proper language instead of showing both languages on the package.

![Screenshot_20210506-122546_Waistline](https://user-images.githubusercontent.com/32624322/117334029-115d1e80-ae89-11eb-874a-69964ca1f2e7.jpg)
![Screenshot_20210506-122636_Waistline](https://user-images.githubusercontent.com/32624322/117334033-115d1e80-ae89-11eb-8643-8a7e0ad93ee6.jpg)

**Comment by davidhealey** [comment]
I'll have to check but I think the search country only applies to manual searches, not scans. I'll see which is more suitable, either applying the search country to scans or the phone's language, or perhaps a combination of the two.

**Comment by jfaltis** [comment]
If the search language is also applied to scans it has to be ensured that the user has set it to his country (e.g. by auto detection or by an onboarding process). Otherwise a user who has not changed the search language can't find any products through scanning, because he is in a different country than the default and I don't think he will go into the settings to check for such setting.

**Comment by davidhealey** [comment]
I've added an dropdown list in the settings page where you can choose your preferred search lanuage. However I suspect a lot of items in the OFF database only have the details in a single language. For example your nutritional yeast is actually in the database with a French name listed as English.

![image](https://user-images.githubusercontent.com/14021202/120892986-c4e03c80-c608-11eb-9fe8-57378d703f5b.png)
