### ISSUE TITLE
[Feature request] Show day in Diary

### ISSUE THREAD

**Issue by bernharl** [davidhealey/waistline#242]
I get really confused while planning the coming week since only the date and not the day is displayed. Often my breakfast is the same every day of the week, so I mix up dates and add the wrong dinner to the wrong day etc...
Would be nice to have an option to show the name of the day (Mon - Sun).

**Comment by jfaltis** [comment]
This is already implemented but no in the release yet, see https://github.com/davidhealey/waistline/pull/237.
