### ISSUE TITLE
[New app version] Issue with capital letters in food/meal/recipe/brand names

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#254]
In the names of food items, meals, and recipes, and also in brand names, capital letters in the middle of words are displayed as lowercase letters.

For example, if I add a food item named "Kokos-Reis-Drink mit Mandeln" of the brand "BioBio", it is displayed as "Kokos-reis-drink mit Mandeln" and brand "Biobio".

**Comment by davidhealey** [comment]
Fixed
