### ISSUE TITLE
[New app version] Hitting phone's back button can lead to unexpected behavior

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#256]
The dialog box "Are you sure you want to delete this item?" cannot be dismissed by hitting the phone's back button.

When doing a search in the Foods menu, pressing the phone's back button exits the entire app instead of just closing the search.

**Comment by davidhealey** [comment]
Done https://github.com/davidhealey/waistline/commit/568332c697a32d145770731db4f4c37c53f57302

**Comment by davidhealey** [comment]
And done the searchbar clearing thing - https://github.com/davidhealey/waistline/commit/e1f4e5be21fad0c806febd0fb10c3c7ec0e0f93e
