### ISSUE TITLE
[New app version] Item names with non-ASCII characters imported from previous version are not searchable

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#257]
The previous (or should I say current) verson of the app had problems handling non-ASCII characters (such as ü). For example, if I added a food item called "Schokomüsli" and then tried to search for it by entering "schokomü", it wouldn't show up in the search results (it would show up when I just search for "schoko" though).

In the new app version, this issue seems to be fixed. Adding new food items with non-ASCII characters is working fine now. They are displayed correctly and they are searchable.

However, items imported from the previous version whose names contain non-ASCII characters are still not searchable. It would be nice if this could be fixed. Interestingly enough, when I select to edit such a food item and then immediately save (without making any changes), the item becomes searchable, so it appears to be an encoding issue.

**Comment by davidhealey** [comment]
Done - https://github.com/davidhealey/waistline/commit/a40ce415526b091969f91c1f8119d3c34be326a3
Also fixed UTF8 header for uploads - https://github.com/davidhealey/waistline/commit/67a08591d0723336a84a959eb67b8339b8f1e035
