### ISSUE TITLE
[New app version] Too many nutrients

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#258]
While it's great that the new version supports a wider variety of nutrients (such as mono and poly fat and many vitamins), I must say that 99% of the time I only care about the 8 standard ones:

- Calories
- Fat
- Sat fat
- Carbs
- Sugars
- Fiber
- Proteins
- Salt

Note that I prefer them exactly in this order because this is how they are listed on products in the EU.
-> see https://www.fsai.ie/uploadedFiles/Nutrition%20Labelling%20FIC%20V2.pdf

This is especially annoying when adding new food items or importing ones from Open Food Facts, because now there are so many input fields when I really only care about 8 of them. This wouldn't be such a big problem if the 8 important input fields were listed first (and in the right order), but unfortunately this is not the case.

To fix this, please consider adding an option to hide the additional input fields and only show the ones I want (in the order I want). Maybe you could also add a button to the add/edit food screen that allows me to show/re-hide the additional input fields as needed.

On a related note, if I select Calories as my preferred energy unit in Settings, I would expect the input field for Kilojoule to be hidden (and vice versa).

By the way, this issue also applies to the chart in the Statistics section. Selecting the desired nutrient for the chart is a lot more cumbersome than in the previous version, because the list of nutrients in the dropdown menu is so long now. Maybe you could list the important ones first; or instead of a dropdown menu you could let the user swipe left/right on the chart to change the displayed nutrient more easily.

**Comment by davidhealey** [comment]
I've implemented this now, except for the ability to re-order them which would require additional work which I'm not going to do any time soon. I suggest making a separate issue specifically for the re-ordering feature.

There's now a list in the settings page to choose which nutriments are displayed in the food editors, this doesn't affect the stats screen. I've added a button to each item in the goal editor where you can choose which items you'd like to appear in the stats page, this also affects the stats entry (button in top right corner of the diary page) - weight will always be shown in the stats entry regardless of if it's shown in the statistics page, I have my reasons :)
