### ISSUE TITLE
Add some way to donate 

### ISSUE THREAD

**Issue by f1reflyyyylmao** [davidhealey/waistline#261]
I'm using the old f-droid version of your app regularly and it helped me a lot with getting my eating habits under control. I'd like to donate some money to you to show my appreciation, but I don't see any way to do so. I saw that you decided to not publish a monero address a while ago, but it'd still be great if you could maybe give your users an alternative.

**Comment by davidhealey** [comment]
Thanks, I'm glad you've found it helpful! There is a [paypal link](https://www.paypal.me/healeyd) near the bottom of the readme in this repo.

**Comment by f1reflyyyylmao** [comment]
Oh right, sorry. Must've missed it.
