### ISSUE TITLE
Order of nutrients

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#263]
Different countries have different regulations for nutrition labelling. For example, in the European Union, nutrients are always listed in this order:

- Kilojoules / Calories
- Fat
- Sat fat
- (Monounsat fat)
- (Polyunsat fat)
- Carbs
- Sugars
- (Fiber)
- Proteins
- Salt
- (Vitamins, minerals etc.)

However, the order in other countries may vary.

Currently, Waistline uses a fixed order for the text fields on the add/edit food page. But when the oder of the text fields doesn't match the order on the product, it becomes unnecessarily difficult to enter/verify the values.

So please add a way to customize the order, either with presets for different countries or with the option to re-order them manually.

**Comment by davidhealey** [comment]
I'm going to make the master list sortable and the order you set there will be used everywhere else.

![Peek 2021-07-18 11-36](https://user-images.githubusercontent.com/14021202/126064095-d7800025-a451-48dd-b85b-6267179ce4e8.gif)

**Comment by davidhealey** [comment]
Done https://github.com/davidhealey/waistline/commit/1bbfe5a56cef80c86ac6e43d66a3e9e83ce9af8a
