### ISSUE TITLE
USDA API link not working

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#269]
On the USDA API settings page, it says "You can request a free API Key by clicking _here_" but nothing happens when I tap on the link.

**Comment by davidhealey** [comment]
Should be fixed now but needs to be tested on Android device - https://github.com/davidhealey/waistline/commit/70f5a33ab441f2de252a1c1827136ba6381f495d

**Comment by EmilJunker** [comment]
Successfully tested it on my phone. The link works now 👍
