### ISSUE TITLE
Diary date picker sometimes doesn't close

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#271]
Sometimes the date picker in the diary does not close after I selected a date. Steps to reproduce:

1. go to the diary
2. click the + button for any category
3. add some food (or immediately navigate back to the diary, it doesn't matter)
4. now open the date picker
5. select a date
6. -> the diary navigates to the selected date, but the date picker is still shown

**Comment by davidhealey** [comment]
This is a weird one, but I can replicate it exactly by following your instructions so shouldn't be too hard to resolve.

**Comment by davidhealey** [comment]
Fixed https://github.com/davidhealey/waistline/commit/09a5f63970efa473eb8138ea953ae2d065df84df
