### ISSUE TITLE
Unable to modify nutritional info for scanned items 

### ISSUE THREAD

**Issue by longestmt** [davidhealey/waistline#275]
Thanks for the new app version! There are issues but I'll try to keep them documented separately with steps to recreate as best I can.
---
Just updated to the new version of the app and noticed that I'm unable to modify the nutrional information for an item after scanning the barcode. What's odd is I'm getting different results than I would have previously. Could this have something to do with the USDA integration? 

Steps to recreate:

1. Scan barcode
2. Product appears (albeit with different results than I would have previously received -- I uploaded the right data to OFF on the old app version)
3. I modify the nutritional information so that it matches my version of the product (i.e. 2 tbsp serving, 70kcal...)
4. Tap the checkmark in the top right
5. Product disappears and is not added to my foods
6. When I rescan the old product information appears again

Device: S21 Ultra 
Android version: 11
App version: 3.0

**Comment by longestmt** [comment]
Also what does the hyperlink icon in the top right during food editing indicate?

**Comment by longestmt** [comment]
![Screenshot_20210728-114931_Waistline.jpg](https://user-images.githubusercontent.com/1509654/127356190-4504445e-b7f3-4774-9d03-9d70aa95d940.jpg)

**Comment by davidhealey** [comment]
> Also what does the hyperlink icon in the top right during food editing indicate?

Please see the release notes - https://github.com/davidhealey/waistline/releases/tag/3.0.0

> unable to modify the nutrional information for an item after scanning the barcode

This isn's something that came up during testing so I don't have much info to go on with solving it. It could be device specific or some Android 11 issue.

> Could this have something to do with the USDA integration?

No, the barcode scanner only searches OFF. What is the difference in the data that you're seeing between the old and new versions?

**Comment by longestmt** [comment]
> What is the difference in the data that you're seeing between the old and new versions?

On the older version when I scanned the same product I'd get a result that exactly matched the nutritional information. I've tested a few regional items that I presumably added to the DB and they work fine. 

This is an example of a popular item that seems to have a conflict though. The serving size should be 2 Tbsp but instead it's bspg (??), the calories are incorrect etc. It would even be fine if the item remained incorrect in the database if I could make a local copy and modify it but I can't.

I DID end up finding a workaround for this item by searching for it without the barcode. I found the item with an incorrect name, renamed it and it saved the change in that instance.

**Comment by chk1** [comment]
> The serving size should be 2 Tbsp but instead it's bspg (??)

OFF product [0897922002829](https://world.openfoodfacts.org/product/0897922002829/peanut-butter-all-natural-protein-powder-pb-fit) lists the serving size as `2 Tbsp (12 g)`, I guess Waistline does some magic here to derive the serving calories from the 100g values, and misinterprets the serving size. Serving size is a free-text field on OFF, I guess values like this will get wrong results if it's not just in the form of `12 g` or very similar, I have seen this happen with other "weird" serving sizes before

**Comment by EmilJunker** [comment]
@longestmt 

> What's odd is I'm getting different results than I would have previously

Someone edited the OFF product entry on April 23, 2020 and changed the nutrition data (see [here](https://world.openfoodfacts.org/product/0897922002829/peanut-butter-all-natural-protein-powder-pb-fit#data_sources)). That's why you are getting different results. It has nothing to do with Waistline.

> unable to modify the nutrional information for an item after scanning the barcode

It's defintely possible to edit the nutritional information after scanning a barcode. But it only affects the entry in your local Waistline database. Maybe you were referring to updating/correcting the values on OFF? That isn't possible, nor should it be.

> The serving size should be 2 Tbsp but instead it's bspg (??)

When importing info from OFF, Waisline parses the serving size string and removes everything except for lowercase letters (a-z). That's why `2 Tbsp (12 g)` becomes `bspg`.

**Comment by davidhealey** [comment]
> When importing info from OFF, Waisline parses the serving size string and removes everything except for lowercase letters (a-z). That's why `2 Tbsp (12 g)` becomes `bspg`.

That smells bad, I'll look into a fix.

**Comment by longestmt** [comment]
> > When importing info from OFF, Waisline parses the serving size string and removes everything except for lowercase letters (a-z). That's why `2 Tbsp (12 g)` becomes `bspg`.
> 
> That smells bad, I'll look into a fix.

Semi-related - Ive noticed that items like bread where a serving is "one slice" is showing up as 1g. I can tell that it means one slice but it's pretty confusing.

**Comment by longestmt** [comment]
![Screenshot_20210810-154743_Waistline.jpg](https://user-images.githubusercontent.com/1509654/128925333-68bdc4da-16d9-443d-ade5-452796e7ef21.jpg)

You can see at the the bottom that the crackers have a weird notation.

**Comment by EmilJunker** [comment]
@longestmt The issues you mentioned all have the same cause.

The bread entry in OFF has the serving size set to `1 SLICE (28 g)` which only leaves `g` after parsing:

https://world.openfoodfacts.org/product/0013764027121/thin-sliced-bread-good-seed-dave-s-killer-bread

The crackers have a portion size of `4 crackers (14 g)` which becomes `crackersg` after parsing:

https://world.openfoodfacts.org/product/0059290573220/table-water-crackers-carr-s

**Comment by prysm1** [comment]
maybe just dont do a any parsing? serving unit will be "4 crackers (14 g)" so a 1 unit of "4 crackers (14 g)".
this seems to be how fatsecrets is doing it.

**Comment by longestmt** [comment]
> maybe just dont do a any parsing? serving unit will be "4 crackers (14 g)" so a 1 unit of "4 crackers (14 g)".
> this seems to be how fatsecrets is doing it.

This makes much more sense to me.

**Comment by davidhealey** [comment]
I'll implement a solution at the weekend

**Comment by davidhealey** [comment]
This should be resolved now - https://github.com/davidhealey/waistline/commit/cce2bb0917bd1ede2284305da118cf248a7cf62c - 

It's not as simple as removing the parsing entirely, while this improves the output for some of the examples given in this thread it negatively affects other items. The fix I've implemented should work in most cases. I'm sure someone will find another edge case where the parsing isn't ideal, if you do please let me know.

**Comment by EmilJunker** [comment]
@davidhealey Looks good to me, but shouldn't you update the regex in line 138 as well?
https://github.com/davidhealey/waistline/commit/cce2bb0917bd1ede2284305da118cf248a7cf62c#diff-0ed1f87c4bd55b3b7dc115a6cbb8ac0419d51d8d925018423201c46146e0e9e0R138

I'm actually not sure whether the "If all else fails" case is even reachable, but if it is then the regex there should be updated too.

**Comment by davidhealey** [comment]
> @davidhealey Looks good to me, but shouldn't you update the regex in line 138 as well?
> [cce2bb0#diff-0ed1f87c4bd55b3b7dc115a6cbb8ac0419d51d8d925018423201c46146e0e9e0R138](https://github.com/davidhealey/waistline/commit/cce2bb0917bd1ede2284305da118cf248a7cf62c#diff-0ed1f87c4bd55b3b7dc115a6cbb8ac0419d51d8d925018423201c46146e0e9e0R138)
> 
> I'm actually not sure whether the "If all else fails" case is even reachable, but if it is then the regex there should be updated too.

Possibly, but I think I added that to fix some very rare edge cases (I can't remember) so unless someone has a specific example where it causes a problem I'd like to just leave it alone for now.
