### ISSUE TITLE
Add the ability to contribute financially

### ISSUE THREAD

**Issue by longestmt** [davidhealey/waistline#277]
As a long time user of the app I'd appreciate the ability to... well... show my appreciation! Something as simple as BTC, ETH and XMR donations would be great because you'd just have to post a wallet address. Fiat donations would be great too but would likely require a little more overhead as far as development goes.

**Comment by davidhealey** [comment]
Thanks! I have a PayPal link on the [homepage](https://github.com/davidhealey/waistline#developer). I code post wallet addresses there too. I don't want to add it into the app itself though.
