### ISSUE TITLE
Update F-Droid version

### ISSUE THREAD

**Issue by Sokom141** [davidhealey/waistline#279]
Hi,
First of all thank you for your work on this app.

I was wondering if the F-Droid version could be updated now that there is the 3.0.0 release available. 
It would be helpful to people that do not want to use the google alternative, thanks!

**Comment by davidhealey** [comment]
You'll have to ask the folks at F-Droid. They have a system that should automatically pull the latest version from github, I don't know how often it does this.

**Comment by Sokom141** [comment]
Okay, thank you for your quick response!

**Comment by davidhealey** [comment]
I think the release was missing some files that fdroid needs to do its auto-building. I'll push a new release at the weekend with the missing files and a few other fixes/updates.
