### ISSUE TITLE
Tag latest release for F-Droid

### ISSUE THREAD

**Issue by dharwood** [davidhealey/waistline#289]
I noticed that F-Droid still hasn't picked up the update yet, so I went poking through things on their side. Looking at the [metadata for Waistline](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.waist.line.yml) and the docs for [UpdateCheckMode](https://f-droid.org/en/docs/Build_Metadata_Reference/#UpdateCheckMode), my guess is that F-Droid's updater is looking for the most recent version-tagged commit with the AndroidManifest.xml and the build.gradle files. Since the most recent tag is 3.0.0 and it doesn't have those files, the updater fails and never checks later commits because it doesn't see a tag for a new version.

I want to stress that this is only a _guess_ about the problem. I'm not sure how to test this short of building half of the F-Droid project (and I don't have that kind of time), so there might be something else going on as well. For now, though, it looks like F-Droid is expecting a tag that isn't there. Next time you bump the version number, could you tag it and see if that gets it picked up? Thank you!

**Comment by davidhealey** [comment]
https://github.com/davidhealey/waistline/issues/283
https://github.com/davidhealey/waistline/issues/279

I'll leave this issue open to (hopefully) stop other people asking the same thing :p

**Comment by davidhealey** [comment]
F-droid seems to be updating again now so I'm going to close this
