### ISSUE TITLE
Can't add photos

### ISSUE THREAD

**Issue by DonPicciotto** [davidhealey/waistline#291]
LineageOS4MicroG 18.1, Redmi Note 5. When I try to add a photo to upload a food to the OFF database, even if I shot the photo the app give me an error or simply don't add it, actually prohibiting me to upload a new entry. Do you think it could be possible to add the option to choose the image from internal memory? This way I can shoot the photo with another app and then choose it with waistline

**Comment by davidhealey** [comment]
> give me an error or simply don't add it,

What is the error?

> Do you think it could be possible to add the option to choose the image from internal memory?

I don't know, but I can investigate it.

**Comment by DonPicciotto** [comment]
After I shoot the photo, it automatically force me to edit the photo with a gallery app: with stock gallery app (after the "editing") the photo simply doesn't appear on the food page, with Simple Gallery (another gallery app) the error "failed to edit the photo" show up and it's impossible to continue

8 ago 2021, 13:25 da ***@***.***:

**Comment by longestmt** [comment]
I can confirm this bug as well. The app forces an edit via the gallery and then errors out.  

S21U - Android 11

**Comment by davidhealey** [comment]
I've added a setting to toggle image editing https://github.com/davidhealey/waistline/commit/7c316de4720398709f0a9b73914de964346c2b28

This is set to false by default. Let me know if this fixes the issue (I'll be pushing a new release today or tomorrow).

**Comment by DonPicciotto** [comment]
Thanks! I'll test it :)

14 ago 2021, 16:36 da ***@***.***:

**Comment by davidhealey** [comment]
@DonPicciotto It's live - https://github.com/davidhealey/waistline/releases/tag/3.1.0

**Comment by DonPicciotto** [comment]
> @DonPicciotto It's live - https://github.com/davidhealey/waistline/releases/tag/3.1.0

Awesome, thanks a lot, it works :)
