### ISSUE TITLE
feature request: show average for the selected period in statistics view

### ISSUE THREAD

**Issue by prysm1** [davidhealey/waistline#292]
version 3.0.2 has been working great for me on my android 8.1 lg phone. so now i'm just nit picking :)

**Comment by prysm1** [comment]
yes, maybe just above the graph showing Average: <some value> or maybe above the timeline so that it does not clutter the screen.

**Comment by EmilJunker** [comment]
Maybe you could also show the average as a horizontal line in the diagram. I don't know if that's possible, but I think it would be useful. Perhaps it could look something like this:

![Screenshot_20210813-001055](https://user-images.githubusercontent.com/19289477/129276619-6b1da161-ff6e-4714-9ab1-e07ef019c08f.jpg)

**Comment by davidhealey** [comment]
@EmilJunker I like this idea. In addition it might also be good to show a line indicating the goal (if any)

**Comment by davidhealey** [comment]
Done https://github.com/davidhealey/waistline/commit/41a1de11cbbdb26c7a70a68c2258434952819ec5
