### ISSUE TITLE
Total calories in diary no longer updates

### ISSUE THREAD

**Issue by prysm1** [davidhealey/waistline#295]
Ver 3.1.0 git hub apk rel 28

Adding an food item under any category breakfast, lunch or dinner. Adds the items calories in the diary view. 

Changing number of serving or servings in diary view does not change total

Changing servings or calories under thee food table view also no longer change the total

**Comment by prysm1** [comment]
![Capture+_2021-08-14-15-15-24](https://user-images.githubusercontent.com/88405330/129459034-26b657b6-d38a-4a3d-8c74-5f3f801a7fc0.png)

**Comment by davidhealey** [comment]
To be clear, this only happens when you set the number of servings to 0, correct?

**Comment by prysm1** [comment]
Nope it started at some value then i changed it to lower value. I tried changing both servings and number of servings. I later set it to zero to see if it would zero out

**Comment by davidhealey** [comment]
Can you give me specific steps to reproduce? Currently I can only reproduce it by setting serving to 0.

**Comment by prysm1** [comment]
I was installing the new apk on top of the old version, which migh have caused the problems. Delete cache and data then reinstall seems to fix it.  

However even after a reinstall, setting number of serving to zero seems to not zero out calorie count.

**Comment by davidhealey** [comment]
Yes I can recreate the issue when setting to 0 so I'll fix that.

**Comment by davidhealey** [comment]
Done https://github.com/davidhealey/waistline/commit/27b0c4a7dff02f8b9d9c5d6f58c9ec4f1e8f4e6b
