### ISSUE TITLE
new update deleted all my data

### ISSUE THREAD

**Issue by coliflor** [davidhealey/waistline#296]
One year worth of data, every single day, every ration with all the details of every single meal, hundreds of manually scanned items and all gone.
Long time ago i entrusted a similar application as yours with personal data, the typical application with fancy GUI super cool tool but the stupid piece of shit wiped all my data because of a stupid glitch, the application spawned a corrupted process and the corrupted process thought that the application launched for the first time and created its root dir by deleting it, it wiped hundreds of files.
I dont really care what caused the data lost, its irrelevant because the relevant part is that you can't entrust JavaScript and fancy GUIs with anything data related. My old rule was to never use anything besides plain text and battle tested applications. Trusting you guys was as literal waistoftime.

**Comment by davidhealey** [comment]
The update shouldn't "delete" any data, it just transfers it to the new format. Did you backup your data before updating?
