### ISSUE TITLE
Dairy calorie problems when adding a recipe

### ISSUE THREAD

**Issue by pablob127** [davidhealey/waistline#300]
I have just found the following issue in version 3.1.1:

I added a recipe to the list of foods, which I set as 1 serving of "full dish", and has a total number of calories of 1575 kcal.

When I add this to my Diary, the calorie count goes wrong. If I had 849 calories before adding it, when I add it (as 1 serving) my total calorie count in the top bar goes to 51145 (instead of the expected 2424). If I change to half a serving, the calories now become 50357 (instead of the expected 1636.5). The Dinner sub-total looks right, though.

The Statistics graph seems to plot the wrong number. Other nutrients seem to be similarly affected.

Please let me know what additional information I can give to help solve this.

**Comment by pablob127** [comment]
I have done more tests, and it gets weird!

I re-constructed the recipe, and at the second reconstruction (using the same ingredients and quantities) it worked well, adding only the proper amount of calories to the total.
The old recipe, even though it looks the same, when added to the same day makes the calorie count inflate by a few tens of thousands (as described above). If I add either the new or old recipe to a new day (it does not matter on what meal), it seems OK (without other food items, only copies of these two recipes in a kind-of-random configuration).

It is a weird thing, and I guess it will need more detective work. If I can give you more information let me know how and I'll try to do it. It is "work-aroundable" though, so it is possible to leave with it.

**Comment by pablob127** [comment]
I snooped around in the exported database, and I found that the entry that causes the issues seems to be the following one:
`
    {
     "portion": "100",
     "id": 5,
     "type": "food",
     "dateTime": "2021-08-18T21:02:42.604Z",
     "quantity": "1",
     "category": "0"
    },
`
which does not have the "unit" field. I don't know if that could cause a huge miscalculation in the calories, since I cannot easily upload a modified backup right now.

**Comment by davidhealey** [comment]
I've just made a fix for #301 I'll push a release later today, let me know if it solves this issue also.

**Comment by pablob127** [comment]
No, this issue is still there. The database in my report for #301 has this issue (it appears on August 18, 2021). I was able to work around it, and I haven't encountered it anymore. But if I try to add those two items (one recipe and one food item) I still get the crazy numbers. 
For simplicity, I am attaching an updated database that has the two offending items on August 29, 2021, as well as a screenshot.
[db.zip](https://github.com/davidhealey/waistline/files/7071384/db.zip)
![Screenshot_20210828-154308](https://user-images.githubusercontent.com/25541487/131229209-9960ec6f-3476-4f27-b7fa-a5be3ca615bd.jpg)

**Comment by EmilJunker** [comment]
@pablob127 Do I understand it correctly that you created this recipe some time ago (in the old app version pre 3.0) and the issue started appearing after the migration to the new version? You mentioned that re-constructing the recipe using the same ingredients and quantities fixes the problem.

I too had an old recipe that started behaving weirdly after I upgraded to the new version. I also was able to solve the problem by re-constructing the recipe from scratch.

If I'm right, this could be an issue with the migration of recipes from the old version to the new one.

**Comment by pablob127** [comment]
> @pablob127 Do I understand it correctly that you created this recipe some time ago (in the old app version pre 3.0) and the issue started appearing after the migration to the new version? You mentioned that re-constructing the recipe using the same ingredients and quantities fixes the problem.
> 
> I too had an old recipe that started behaving weirdly after I upgraded to the new version. I also was able to solve the problem by re-constructing the recipe from scratch.
> 
> If I'm right, this could be an issue with the migration of recipes from the old version to the new one.

No, this happened with a recipe written from scratch in version 3.x . 
I had the recipe written in the old 2.4.2 version, but my database was lost in the "white screen debacle" with the F-Droid version. :-)
