### ISSUE TITLE
"Ghost" calories in a dairy entry after deleting everything.

### ISSUE THREAD

**Issue by pablob127** [davidhealey/waistline#301]
I am giving Waistline a workout! (version 3.1.1 from Github)
I was trying to add some foods to the database, and somehow (I did not see exactly what happened, my phone moved and there were some uncontrolled presses), I ended up with 32 phantom calories in the day's list. The individual meals do not add up to the total shown in the top bar, there are an extra 32 calories. I deleted all entries, and the 32 calories (and an assortment of other nutrients) were still there (see attached screenshot).
I exported the database, to look a bit, and I see some entries with the corresponding date (2021-08-18), even though there should be none left.
I think this has to do with recipes, since I had added two recipes to the day, and could be related to issue #300 
![Screenshot_20210818-165751](https://user-images.githubusercontent.com/25541487/129973557-fce58051-b4fc-4b18-ab99-cf2fb7f01e1e.jpg)
[db_export.zip](https://github.com/davidhealey/waistline/files/7010231/db_export.zip)

**Comment by davidhealey** [comment]
Thanks I'll check it out, sounds fun :p

**Comment by pablob127** [comment]
I looked up a JSON parsing util, and I found out a part of the problem: One of the items I added ("Green onions, raw" id 28), got added into as an entry into the day, but without anything shown to the user.
This is what the database export says about the day:

```
  {
   "dateTime": "2021-08-18T00:00:00.000Z",
   "items": [
    {
     "id": 28,
     "portion": "100",
     "unit": "g",
     "type": "food",
     "dateTime": "2021-08-18T20:51:18.926Z",
     "quantity": 1
    }
```

There are two related questions:

1. How did this got added? (that I cannot reproduce, unfortunately, as it was a random series of manipulations)
2. How can we remove this "invisible" entry? One way could be implementing some kind of database purge (which could also purge hidden foods, meals, and recipes).

**Comment by davidhealey** [comment]
> 2\. How can we remove this "invisible" entry?

I think a better thing would be to find out why it's invisible.

**Comment by pablob127** [comment]
> > 2. How can we remove this "invisible" entry?
> 
> I think a better thing would be to find out why it's invisible.

That is a perfect 3rd question! :-)

**Comment by prysm1** [comment]
similar to item #295 

i opted to clear the cache and data and re-install. seem to have worked for me.
WARNING: deleting cache/data will delete backup json also

**Comment by davidhealey** [comment]
Fixed https://github.com/davidhealey/waistline/commit/876725f23830b06df41042a060206121f87d5a96
