### ISSUE TITLE
Statistics and charts

### ISSUE THREAD

**Issue by eldaran** [davidhealey/waistline#305]
Hi !
Thanks a lot for this great application, it really helped me to lose weight :) 

Not a bug but still really annoying:
- the stats diagram available in the dairy is totally useless since you compare different quantities (ie : grams of macro nutriments and kcal of energy count)
- the stats charts that draws weight, kcal, fat... Etc along the time should imho not be scaled starting from 0 (zero). I think it was ok in the previous release. At least, could you provide the mean to change the vertical axis scale and origin ?

Again, thx a lot, 👍🏻 and nice work 👏🏻👏🏻👏🏻

**Comment by davidhealey** [comment]
> * he stats diagram available in the dairy is totally useless since you compare different quantities (ie : grams of macro nutriments and kcal of energy count)

Tap on the calories legend to hide it

**Comment by EmilJunker** [comment]
> the stats charts that draws weight, kcal, fat... Etc along the time should imho not be scaled starting from 0 (zero). I think it was ok in the previous release. At least, could you provide the mean to change the vertical axis scale and origin ?

I prefer it the way it currently is (with the scale starting from 0). So please keep this as an option, if possible.

**Comment by davidhealey** [comment]
> * At least, could you provide the mean to change the vertical axis scale and origin ?

What wouild you change it to?

**Comment by eldaran** [comment]
Hi !
Thx for the answers :)
I would like to be able to start vertical axis with a different value. 

> > * he stats diagram available in the dairy is totally useless since you compare different quantities (ie : grams of macro nutriments and kcal of energy count)
> 
> Tap on the calories legend to hide it

Yes :) I noticed the on/off option, but still I think the current circular diagram is not useful at all.

**Comment by davidhealey** [comment]
> with a different value.

Can you give me an example so I can see its purpose?

**Comment by eldaran** [comment]
> > with a different value.
> 
> Can you give me an example so I can see its purpose?

Here on attached picture, the vertical axis starts at 66 instead of 0. Thus, the variable changes are much more easy to read. 
![jpeg_1625940454000](https://user-images.githubusercontent.com/2682993/130686927-85bda3b8-e91c-4e8a-acfa-aa094c098b00.jpg)

**Comment by davidhealey** [comment]
Aha I understand now, thanks

**Comment by eldaran** [comment]
My apologies for the lack of clarity then :)


> > * he stats diagram available in the dairy is totally useless since you compare different quantities (ie : grams of macro nutriments and kcal of energy count)
> 
> Tap on the calories legend to hide it

Sorry to insist, but showing calories and macro nutriments in the same diagram makes no sense since units are different. 

I would suggests instead to show macro nutriments breakdown with a bit more details, that is : including sat-fat (which is part of fat), sugar (which is part of carbs), fiber, salt, and of course protein, carbs, fat.

Please carry on with your nice and good work on that app !

**Comment by davidhealey** [comment]
> Sorry to insist, but showing calories and macro nutriments in the same diagram makes no sense since units are different.

Well the update I put out a couple of hours ago removed the energy values from the pie chart :) https://github.com/davidhealey/waistline/releases/tag/3.1.3

**Comment by davidhealey** [comment]
> I would like to be able to start vertical axis with a different value.

Done https://github.com/davidhealey/waistline/commit/ea90530223495d8fc8e59d0056b3a3005f5fd84a

**Comment by eldaran** [comment]
> > I would like to be able to start vertical axis with a different value.
> 
> Done [ea90530](https://github.com/davidhealey/waistline/commit/ea90530223495d8fc8e59d0056b3a3005f5fd84a)

Thanks ! Looking forward to test it :)

**Comment by davidhealey** [comment]
> I would suggests instead to show macro nutriments breakdown with a bit more details

Done, all nutriments set to visible in Settings will be displayed in the pie chart https://github.com/davidhealey/waistline/commit/6aebc077c16119e277a877aae758c82934da374b

**Comment by eldaran** [comment]
> > I would suggests instead to show macro nutriments breakdown with a bit more details
> 
> Done, all nutriments set to visible in Settings will be displayed in the pie chart [6aebc07](https://github.com/davidhealey/waistline/commit/6aebc077c16119e277a877aae758c82934da374b)

Nice ! But in my case, the option seems to work for the "calorie" stat only. Not for weight, fat, ...ie other stats.
Could you look into that ? Thanks 🙏🏻

**Comment by davidhealey** [comment]
Are you using the version I put out today?

**Comment by eldaran** [comment]
> Are you using the version I put out today?

Yes 3.1.4, I got it from github

**Comment by eldaran** [comment]
> > > I would suggests instead to show macro nutriments breakdown with a bit more details
> > 
> > 
> > Done, all nutriments set to visible in Settings will be displayed in the pie chart [6aebc07](https://github.com/davidhealey/waistline/commit/6aebc077c16119e277a877aae758c82934da374b)
> 
> Nice ! But in my case, the option seems to work for the "calorie" stat only. Not for weight, fat, ...ie other stats.
> Could you look into that ? Thanks 🙏🏻

I was referring to the zero of the y-axis. Sorry for the lack of clarity.

**Comment by davidhealey** [comment]
> the option seems to work for the "calorie" stat only

Which option are you using? It should be the nutriments settings which don't include calories.

**Comment by davidhealey** [comment]
> I was referring to the zero of the y-axis. Sorry for the lack of clarity.

Oh right, that's a different matter. I just tested and it's not working on my phone at all :) so I have something to fix

**Comment by davidhealey** [comment]
@eldaran Actually it does seem to be working for me. When the setting is off it will start the scale from the the lowest value recorded. So if you recorded 0 for one of the days it will start the scale at 0 still. Can you check if this is what you're seeing?

**Comment by eldaran** [comment]
> @eldaran Actually it does seem to be working for me. When the setting is off it will start the scale from the the lowest value recorded. So if you recorded 0 for one of the days it will start the scale at 0 still. Can you check if this is what you're seeing?

Hi,
No way to make it work except for the "calorie" variable. I checked with activate / deactivate in the options in case there would be some kind of initialisation, but not to avail. 
![Screenshot_20210829-075659_Waistline](https://user-images.githubusercontent.com/2682993/131240379-1738e51d-ac84-4792-8ee2-2486d552ce16.png)

**Comment by eldaran** [comment]
Variable "calories" with the same options
![Screenshot_20210829-081415_Waistline](https://user-images.githubusercontent.com/2682993/131240656-31616cf1-20ac-4182-a03d-fa2730672727.png)

**Comment by davidhealey** [comment]
It's working here. I entered a value of 50 for weight everyday for a week.

![Screenshot_20210829-114223](https://user-images.githubusercontent.com/14021202/131247569-27612004-9006-4939-ba48-2c8ac8283bf5.png)

**Comment by eldaran** [comment]
> It's working here. I entered a value of 50 for weight everyday for a week.
> 
> ![Screenshot_20210829-114223](https://user-images.githubusercontent.com/14021202/131247569-27612004-9006-4939-ba48-2c8ac8283bf5.png)

Well, doesnt work for me 😕

**Comment by EmilJunker** [comment]
@eldaran The screenshot you posted has the range set to "1 Month" but the leftmost data point is from August 19. So I conclude that you only have weight data for the last 20 days and the older values are (invisibly) assumed to be zero. That's probably why it's not working for you.

To check my hypothesis, could you try setting the range to "1 Week" and see if this fixes it?

**Comment by eldaran** [comment]
> @eldaran The screenshot you posted has the range set to "1 Month" but the leftmost data point is from August 19. So I conclude that you only have weight data for the last 10 days and the older values are (invisibly) assumed to be zero. That's probably why it's not working for you.
> 
> To check my hypothesis, could you try setting the range to "1 Week" and see if this fixes it?

Nice try ... But not. By thé way, it works well for the calories, but not for every other stat
![Screenshot_20210829-181659_Waistline](https://user-images.githubusercontent.com/2682993/131257568-bb60163e-2ae9-4902-bd1d-92189470729f.png)

**Comment by davidhealey** [comment]
@eldaran There's something strange going on there with the Average too

**Comment by eldaran** [comment]
> @eldaran There's something strange going on there with the Average too

Right, average result is NaN so maybe a division by zero somewhere ?

**Comment by EmilJunker** [comment]
@eldaran Is the weight average result the only one that's NaN? Or does this happen for other stats too? If yes, which ones? Maybe the issues are related.

**Comment by eldaran** [comment]
> @eldaran Is the weight average result the only one that's NaN? Or does this happen for other stats too? If yes, which ones? Maybe the issues are related.

As far as I can see, only for weight.

**Comment by eldaran** [comment]
Hi ! Since 3.1.5 y-axis issue seems to be cleared, but the Nan weight average is still there.

**Comment by EmilJunker** [comment]
The broken average is tracked in #319, so I think we can close this issue here since the y-axis problem has been fixed.
