### ISSUE TITLE
After splash screen, I am stuck on a white screen

### ISSUE THREAD

**Issue by mrhebisan** [davidhealey/waistline#306]
After updating to 3.1.1, I can no longer access the app on my phone.  I see the new splash screen, but then when it fades to white the app does nothing else

Phone : Pixel 3a
OS : Graphene OS 
OS Build number : RQ3A.210805.001.A1.2021081822

**Comment by FabHof** [comment]
Same for me: Pixel 4

**Comment by davidhealey** [comment]
https://github.com/davidhealey/waistline/issues/293
