### ISSUE TITLE
White blank screen on startup 

### ISSUE THREAD

**Issue by brimwats** [davidhealey/waistline#309]
Samsung Galaxy S10, Android 11, just manufacturer updates. installed through f/foxy droid

screenshot

![Screenshot_20210827-160046_Waistline](https://user-images.githubusercontent.com/49103046/131196596-d39e9af2-45b2-4c69-8834-27e43769742e.jpg)

**Comment by brimwats** [comment]
have tried relaunching, restarting, reinstalling

**Comment by davidhealey** [comment]
Duplicate

**Comment by azzamsa** [comment]
https://github.com/davidhealey/waistline/issues/293
