### ISSUE TITLE
Quantity popup

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#310]
When adding a single item to the diary/meal/recipe prompt for the quantity. Also add a setting to disable this.

**Comment by EmilJunker** [comment]
Maybe a bit more difficult to implement, but when adding multiple items at once, the app could prompt for the quantity of each one by one. Just an idea...

**Comment by davidhealey** [comment]
Shouldn't be too difficult to implement, just a single command vs a loop I think. I'll add an option to toggle that though because some people might not want it.

**Comment by h-h-h-h** [comment]
Could this be extended with a calories textbox? Not only would this allow you to quickly make a rough estimate what amount of the food you're allowed to consume ("Would 2 cookies be okay? Would 3 cookies be okay?"), but you could also enter a calorie value and, e.g., get the weight you can eat. See also what I wrote [here](https://github.com/davidhealey/waistline/issues/337#issuecomment-1016026648) about fraction-based food (this dialog would then adhere to the default linking defined for the food).

If this dialog would add calories, it so neatly would contain all the centrally important values.
