### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by AdrienDSlone** [davidhealey/waistline#312]
Hello,

Where can I contribute to translate waistline in french ?

Thx for the 3.1.4 release :)

**Comment by davidhealey** [comment]
https://crowdin.com/

**Comment by AdrienDSlone** [comment]
I see, but I will cost money wont it ?
Weblate offers for free hosting opens source translation :
https://weblate.org/en/

What do you think ?

**Comment by davidhealey** [comment]
Crowdin doesn't cost anything. I don't know the details of how it works.
@EmilJunker Will probably be able to advise you better than I can

**Comment by AdrienDSlone** [comment]
> 
> 
> Crowdin doesn't cost anything. I don't know the details of how it works.
> @EmilJunker Will probably be able to advise you better than I can

Ok, if it s free I ll wait EmiJunker advises and then will start translation :D

**Comment by EmilJunker** [comment]
@AdrienDSlone Here's a direct link to the project: https://crowdin.com/project/waistline/fr

**Comment by davidhealey** [comment]
I think the French translation is complete at the moment - except for a few additions I made today

**Comment by AdrienDSlone** [comment]
Ok, I ll check the link :) 

i proposed because french is not reachable in settings waistline.

**Comment by yarons** [comment]
@EmilJunker @davidhealey I really like Crowdin but at the time we set this up there was a long waiting list for Weblate, now it's a little different (grace period).

Anyways, I like Weblate a lot and I'm an active contributor but we might need some more prep work done before we can move to Weblate.

BTW, there's still no Crowdin link in the README file?

**Comment by davidhealey** [comment]
> BTW, there's still no Crowdin link in the README file?

Want to add one? :)

**Comment by AdrienDSlone** [comment]
I didnt know that I could find links in readme file, apologies

Anyway, tell me if you need a french guy

**Comment by davidhealey** [comment]
> I didnt know that I could find links in readme file, apologies

You can't. There isn't one yet, that's what Yarons saying :)

**Comment by AdrienDSlone** [comment]
> 
> 
> > I didnt know that I could find links in readme file, apologies
> 
> You can't. There isn't one yet, that's what Yarons saying :)

I see but even in other projects since I learnt taht today I will look inside for translation and stuff haha

**Comment by yarons** [comment]
> > BTW, there's still no Crowdin link in the README file?
> 
> Want to add one? :)

Sure, why not bb996a6a11e2125cbf1186ef1df6433647bfb8b8
