### ISSUE TITLE
Add Android Adaptive icon

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#313]
Android 8.0 introduced the concept of Adaptive icons. The idea is to split the app icon into a background and a foreground instead of just providing a single static app icon with a predefined shape. This way, the Android launcher can apply a consistent shape to all icons on the home screen for a more uniform look and feel. Some launchers can even animate the icons using a parallax effect where the background and foreground are sort-of "shaken" independently from each other. For more information see [the docs](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).

Cordova has built-in support for Adaptive icons, see [here](https://cordova.apache.org/docs/en/latest/config_ref/images.html#android). All you need to do is provide the `background` and `foreground` images in addition to the `src` image in the `config.xml.` file.

The current Waistline app icon looks like this:

![xxxhdpi](https://user-images.githubusercontent.com/19289477/131230122-dd9ce597-c1ae-45b7-b684-abd6e0165a42.png)

I would suggest to split this into a background and foreground as follows (This is just a sketch. I'm not a designer, as you can probably tell 😅)

The background consists of a solid red background with the scale printed on it:

![bg](https://user-images.githubusercontent.com/19289477/131230219-fe858bd6-1602-47a5-a32b-fea5fb1b4966.png)

The foreground is mostly transparent with the letter W in white and the pointer in red:

![fg](https://user-images.githubusercontent.com/19289477/131230221-7b722a29-cd99-4418-b0e9-451d511a59c1.png)

Put the background and foreground together and you get the following. If the icon was animated (i.e. parallax effect) this should hopefully give an interesting result with the pointer moving along the scale.

![icon](https://user-images.githubusercontent.com/19289477/131230301-184ed499-4082-4f8c-9134-2f141ea4568c.png)

With a round icon shape applied, it would look like this (the black portion gets removed):

![circle](https://user-images.githubusercontent.com/19289477/131230343-da111c5d-e777-4e74-bff7-087a4e304fc1.png)

With a "squircle" icon shape applied, it would look something like this (again, the black portion gets removed):

![squircle](https://user-images.githubusercontent.com/19289477/131230326-042e4023-63a4-4309-874c-977d42b2c66a.png)

This way, the app icon could adapt to different icon shapes (whichever shape the launcher is using) and thus would fit in better with other Adaptive icons on the home screen.

**Comment by davidhealey** [comment]
I do have the original SVG for the logo from the designer so I should be able to do this

**Comment by EmilJunker** [comment]
@davidhealey 
Hey, if you want you can send me the SVG and I'll try to do this myself.

**Comment by davidhealey** [comment]
Thanks! If you want to fix the landscape splashscreen issue too don't let me stop you :)

[Master File.svg.zip](https://github.com/davidhealey/waistline/files/7123710/Master.File.svg.zip)

**Comment by EmilJunker** [comment]
Okay, with the help of Inkscape and my very basic SVG editing/design skills, I was able to create new icons.

Problem is: For some reason, the app doesn't build with these adaptive icons. I've created a comment about this for a similar issue in the Cordova repository, see https://github.com/apache/cordova-android/issues/942.

You can see my edits at the `android-icons` branch in my fork: https://github.com/EmilJunker/waistline/tree/android-icons.
You can try it out if you want. Maybe the build works on your machine 🤷

I also added landscape splashscreen images (#331) and although it looks a bit distorted on my phone, it does work!

**Comment by EmilJunker** [comment]
Some good news! After upgrading to the latest Android SDK (version 30), the build works. The adaptive icon is working too, but it doesn't look quite right on my phone, so I have to do a bit more work.

![Screenshot_20210909-164353](https://user-images.githubusercontent.com/19289477/132707419-2ae84176-f3a9-4344-bce9-2c58eb5f36ba.jpg)

**Comment by davidhealey** [comment]
> Android SDK (version 30)

Will this still work on older phones?

**Comment by EmilJunker** [comment]
It should. For older phones that don't support adaptive icons, a fallback icon is specified in the `src` attribute in the `config.xml` file.
