### ISSUE TITLE
Feature Request: show images in food list

### ISSUE THREAD

**Issue by prestidigitonium** [davidhealey/waistline#317]
Hello, it could be useful to show food images also in food list and not only in diary tab.

**Comment by davidhealey** [comment]
Sounds reasonable

**Comment by prestidigitonium** [comment]
Could you add mini-images also in food search (like open food tracker does)? It's not so comfortable to open&close each food to see if the image is what we are looking for, and return dozens of times from the item to the list.

**Comment by davidhealey** [comment]
> Could you add mini-images also in food search

I thought that's what you were asking for in your original post, no?
