### ISSUE TITLE
Stats average not working properly

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#319]
Something fishy here

**Comment by davidhealey** [comment]
Haven't been able to recreate the issue reliably yet

**Comment by EmilJunker** [comment]
Only the weight/neck/waist/etc. averages are broken (i.e. the body measurements). The averages for the macronutrients are working fine.

But there appears the be a more fundamental problem with the body measurements. I'm normally not using this feature, so I didn't have any weight values stored. To test it, I entered weights 68, 69 and 70 for the last three days, and now it shows an average of 228990:

![Screenshot_20210905-093054](https://user-images.githubusercontent.com/19289477/132119566-43a6496b-0b6d-41be-8bf4-74b311c0052b.jpg)

I also noticed that the diary always displays the most recently entered weight value in the Today's Stats popup for all dates, including all dates in the past, all dates for which I actually entered different weight values, and all future dates as well. But I guess this is just how you decided to implement it and it's not relates to this issue. I just found it to be a bit confusing at first.

Finally, another probably unrelated point, but still a bit weird: the weight stat is the only one that shows up in the diary regardless of my goal settings. The other body measurement stats only show up in the diary when I choose to "Show in Statistics" in the goal editor. I was just wondering if this is intended.

**Comment by davidhealey** [comment]
> But I guess this is just how you decided to implement it and it's not relates to this issue. 

Yes, the idea is for example, on Monday you enter your weight of 75kg, on Wednesday you enter your weight again, well it's probably going to be 75kg or somewhere close so we'll show the last weight you entered. I suppose I could make it show it shows the most recently entered weight based on the selected date though.

> I was just wondering if this is intended.

Yes. I should probably remove the show in statistics option for this one and make it a permenant thing. I also need to remove the same goal every day thing for these non-nutriment goals.

**Comment by davidhealey** [comment]
Stats average issue is resolved - https://github.com/davidhealey/waistline/commit/c34547e998f631aa9c5dea489ffaa69d28919cf2
