### ISSUE TITLE
Bug: change portion size while adding new food from search

### ISSUE THREAD

**Issue by prestidigitonium** [davidhealey/waistline#322]
Hello, I've the latest application 3.1.4 installed from f-droid (on crdroid 6.x).

**Problem**: In the food tab, when I search a food (using the online openfoodfacts database), if I change the portion size before tapping the checkmark button, then nutrients are not recalculated for the new size. So after adding the product I get a food with a custom portion size but nutrients are not referred to the current size.
**How to reproduce the problem**: food tab > search a food online > open a food > edit portion size > add food
**Expected behavior**: nutrients should be recalculated after any edit before adding a food

**Comment by davidhealey** [comment]
> installed from f-droid

You don't get the white screen of death issue?

Thanks for the bug report, I'll check it out at the weekend.

**Comment by prestidigitonium** [comment]
yes I got the white screen but I solved it in this way:
- remove waistline 3.1.4
- install waistline 3.0.0 from github
- use waistline for 1 day (add food, change settings..)
- update waistline from 3.0.0 to 3.1.4 using fdroid update

**Comment by davidhealey** [comment]
> update waistline from 3.0.0 to 3.1.4 using f-droid update (re-enabled f-droid updates for waistline)

I don't get it, you can't update Waistline from f-droid if you have the github version installed. The two version are incompatible, you'd have to uninstall the github version first.

**Comment by prestidigitonium** [comment]
sorry, it was 3.0.0 from f-droid

**Comment by davidhealey** [comment]
I can't confirm this issue, changing the serving size in the food editor before adding to the db works as expected in the latest version.

**Comment by EmilJunker** [comment]
I just tested it and I can't recreate this issue either. Changing the serving size before tapping the checkmark button works as it should. Obviously, the link button at the top must be enabled for this to work (it is disabled by default when importing items from OFF). Maybe that was the problem?

**Comment by davidhealey** [comment]
> Maybe that was the problem?

Serving size should still change even with the button off, it just won't update the other stats

**Comment by EmilJunker** [comment]
@prestidigitonium wrote:
> if I change the portion size before tapping the checkmark button, then nutrients are not recalculated for the new size

So the original issue was that nutrients are not recalculated when the serving size gets changed. The way I interpret it, there was never a problem with the serving size not being saved.

But as I said, I can't confirm this issue. The serving size is saved, and (if the link is active) the other nutrients are recalculated too.

**Comment by davidhealey** [comment]
Thanks, I think the issue can be closed.
