### ISSUE TITLE
Bug: food disappears if I add and delete the same food

### ISSUE THREAD

**Issue by prestidigitonium** [davidhealey/waistline#323]
Hello, I've the latest application 3.1.4 installed from f-droid (on crdroid 6.x).

**Problem**: In the food tab, when I search a food (using the online openfoodfacts database), if I add a food, then delete it, and adding again the same food, it doesn't appear anymore in the food list.
**How to reproduce the problem**: Food tab > search a food online > add a food X. Delete the food X. Food tab > search the food X online > add the food X.
**Expected behavior**: If I delete a food and I add it again, it should be shown in the food list.

**Comment by davidhealey** [comment]
Confirmed

**Comment by davidhealey** [comment]
Fixed https://github.com/davidhealey/waistline/commit/716f2d1773ad009ce007fcbfdb126d762f73beb8
