### ISSUE TITLE
additional database sources

### ISSUE THREAD

**Issue by prysm1** [davidhealey/waistline#326]
maybe same approach as the usda db by using individual api key 
https://www.nutritionix.com/business/api
https://platform.fatsecret.com/api/default.aspx?screen=rapih

**Comment by davidhealey** [comment]
I'm hesitant to promote fat secret, I'd rather people add to the OFF database.

What I gather from the first one is it would require me to buy a license rather than individual users getting a free license.

**Comment by prysm1** [comment]
Ok. I agree lets just push to make OFF better and more complete. thanks

**Comment by GeoffreyCoulaud** [comment]
Hey, sorry to dig up old issues but not having integration with fatsecret is kind of a big deal in my opinion, I often find myself going to the website and just transcribing the data into Waistline.

Why not provide both for users and just favor OFF? 

Thanks for the amazing app anyway!

**Comment by davidhealey** [comment]
> Why not provide both for users and just favor OFF?

Each user would need an API key, because Waistline is open source I can't just get a key and embedded it in the app, otherwise anyone could use it. It doesn't look like they offer API keys to individuals.

You can use the USDA database with Waistline if you get an API key.
