### ISSUE TITLE
Issue with loading the app

### ISSUE THREAD

**Issue by RyokoUmbra** [davidhealey/waistline#336]
Having an issue with starting the app. On opening the app the splash screen comes up and shows that it is loading and then loads to a blank white screen. After leaving it for 10 minutes to see if it just needed time to load properly the screen is still white. I have uninstalled and reinstalled via F-Droid with no success in solving the issue. I'm currently on the most recent version, 3.1.5, with Android 11 on a Pixel 2 XL. 
![Screenshot_20210907-200630](https://user-images.githubusercontent.com/90293904/132429343-fe28c353-edcf-4fd6-8e80-516bc6bb6179.png)
![Screenshot_20210907-200637](https://user-images.githubusercontent.com/90293904/132429349-eff753cb-c120-4a0e-9c0c-fca8d25cf0fb.png)

**Comment by davidhealey** [comment]
https://github.com/davidhealey/waistline/issues/293

**Comment by RyokoUmbra** [comment]
Thanks! Just didn't look far enough back. Got it up and running now!
