### ISSUE TITLE
Updated linked values in realtime

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#337]

**Comment by h-h-h-h** [comment]
It's indeed annoying having to intermediately focus another textbox, when I want to figure out which amount of a food I can consume, given that a certain amount of calories can be spent.

The realtime updating should also work when editing the calorie textbox (or any nutrient textbox).

When consumption of a food is weight-based, editing the calorie textbox correctly changes the portion size value that's associated with the "g" unit. But some foods are fraction-based, like drinking half of a 750-ml juice bottle. (Personally, I use fractions in 10% or 0.1 increments.) In this case, one cannot find out what fraction to consume by editing the calorie textbox.

How about letting the user control whether it is "Portion Size" or "Portion Count" that's linked with the nutrient textboxes? Maybe a checkbox/switch when defining the food in the food list that specifies how linking in the diary should behave. Or might it be desirable to be able to change the linking behavior per diary entry? There still should be the same default for every new diary entry, though, depending on whether the food was defined as fraction-based.

**Comment by h-h-h-h** [comment]
What do you think about linking the nutrient textboxes (most importantly calories) not to "Portion Size", but "Portion Count" for fraction-based food like beverages?

**Comment by davidhealey** [comment]
> What do you think about linking the nutrient textboxes (most importantly calories) not to "Portion Size", but "Portion Count" for fraction-based food like beverages?

How would it know which one to use for which item?

**Comment by h-h-h-h** [comment]
You'd need to be able to define it, e.g., by a tri-state link button at the top (with informational toasts about the state), or by a switch in the nutrients section.

This linking definition could then also be used in the [quantity popup](https://github.com/davidhealey/waistline/issues/310#issuecomment-1016305235), if a calorie textbox is added there, which would also be very useful.
