### ISSUE TITLE
Feature request: split daily graph between macro and micro nutrients

### ISSUE THREAD

**Issue by prestidigitonium** [davidhealey/waistline#338]
Hello, in the Diary tab there is a pie chart in the top right corner and it shows all tracked nutrients in 1 graph only. In my opinion it should be organized in macro and micro nutrients. In this way is not so easy to compare percentages of macronutrients (and they are important over all other nutrients). For example:
a top chart: macronutrients only
a bottom chart: micronutrients only

So my proposal is:
- split the graph in macro/micro (at least)
- add percentages inside the graph near the absolute value of each nutrient, or at the bottom of the page (or both) because to see each percentage we need to tap in the pie and we can't see all percentages at the same time.
- any other improvement in the graph view is well accepted, for example different views for each graph (for example it could be useful to see the macro in pie chart and the micro as a textual list)

**Comment by EmilJunker** [comment]
I'm currently working on this feature. How would you like the following implementation?

The pie chart always shows the macro nutrients fat, sat-fat, carbs, sugars and proteins (regardless of settings). Below the pie chart, you can see the percentages (here fat includes sat-fat and carbs includes sugars).

![Screenshot 2021-09-29 183723](https://user-images.githubusercontent.com/19289477/135312130-fa8446b9-2322-4701-b1f8-efd28ccb75b8.png)

Below the macro nutrients, all other tracked nutrients are shown in a list with their absolute values:

![Screenshot 2021-09-29 183916](https://user-images.githubusercontent.com/19289477/135312148-a63e2649-dac9-4a88-b56f-9568240a151c.png)

I could also add a second pie chart for the other nutrients, but I'm not sure if this would make sense.

**Comment by EmilJunker** [comment]
Since no one replied yet, I've just opened a pull request anyway: #362

@prestidigitonium @vilhelmgray @prysm1 Please let me know if this works for you.

**Comment by vilhelmgray** [comment]
I do have one suggestion. There exists some ambiguity on which vitamins are actually the "B" vitamins, so I recommend including the particular molecular function in parentheses next to the respective name: Vitamin B1 (Thiamine), Vitamin B2 (Riboflavin), Vitamin B3 (Niacin), Vitamin B5 (Pantothenic acid), Vitamin B6 (Pyridoxine), Vitamin B12 (Cobalamin).

**Comment by EmilJunker** [comment]
> I recommend including the particular molecular function in parentheses next to the respective name

Great idea, I've implemented that now. I was a bit worried the names might become too long that way, but I took care of that.
