### ISSUE TITLE
Choose homescreen to launch app into

### ISSUE THREAD

**Issue by thgoebel** [davidhealey/waistline#341]
### What
Allow the user to specify which screen the app should first display upon launch. Statistics, Diary, Food or Settings?
Pre-v3 Waistline had such a setting, where did it go? 😢

### Why

Launching into the settings screen forces the user to do 2 extra clicks in 99% of cases.

### Alternatives

1. Always launch the app into the last used screen. But even better: allow the users to choose a screen, and in the list of "Statistics, Diary, ..., Settings" add an entry "Last Used".
2. Always open the app in the settings screen (like now), but with the navigation drawer open. This eliminates the extra click to open the drawer, allowing the user to directly choose a destination.

Version 3.1.6

**Comment by EmilJunker** [comment]
This change is now implemented in https://github.com/EmilJunker/waistline/commit/72ce0ff38d9da3f3c833b45695c21989fcc4b89a.

If this is all right, it can be merged via pull request #335.
