### ISSUE TITLE
Stastics for Weight development

### ISSUE THREAD

**Issue by lobneroO** [davidhealey/waistline#344]
I have updated to lineage 18.1 (android 11) yesterday and that triggered a waistline upgrade. The "new" version doesn't offer "weight" in the statistics anymore, which was the main reason I used the app. Can we get that back? 

Edit: sorry about not marking this a feature request, I cannot find the button to do so.

**Comment by davidhealey** [comment]
It does, but you need to enable it in your goal settings.

**Comment by lobneroO** [comment]
Oh, I see. Thank you. I didn't expect it there.
