### ISSUE TITLE
Set macro goals as percent of total?

### ISSUE THREAD

**Issue by ergodicbreak** [davidhealey/waistline#346]
Hello, just started using the app yesterday and it's quite good, thanks very much for working on it! 

Has anyone ever requested setting macro goals as a percent of total calories? Or maybe it's possible somehow? It's quite common to set macro goals like "25%/60%/15%" for fat/carb/protein for example, and it would make things a little more user friendly I think when setting goals. 

I admit the UI could be tricky to get right so perhaps to simplify things there could be a checkbox on the Goals screen which says "Show macro targets as percent of calories", and then fat/carb/protein would automatically be set at 1/3 of calories which the user could adjust. If the user adjusts only one macro the other two split the remainder.

**Comment by davidhealey** [comment]
Related https://github.com/davidhealey/waistline/issues/245

**Comment by ergodicbreak** [comment]
Yes, thank you! +1'ing that issue and closing this one.
