### ISSUE TITLE
Anchor the calorie meter to the screen in the diary instead of scrolling it away as you enter food

### ISSUE THREAD

**Issue by mrhebisan** [davidhealey/waistline#368]
In the older version of the app and in other apps I have used, the daily calorie count stays visible in the diary no matter how many food items were entered.  Can this be restored as an option?

It now scrolls away since it is now at the top of the scrollable view instead of being anchored. This is a degradation in function from my perspective.

 Keeping constant eyes on that calorie goal is very helpful while editing later day meals, or preplanning a whole day in advance.

  If I pre-enter the food before I eat it I have to constantly scroll up and down the screen to make sure I'm not overeating with every new entry.

**Comment by davidhealey** [comment]
Yes I think this is a good idea it annoys me too. I want to make some other changes to the calorie display anyway. Waistline's number 1 purpose is to be a calorie counter so I want to give the calorie consumption priority in the diary display. I don't like the current setup and I have a few plans for improvement.

**Comment by EmilJunker** [comment]
I've experimented a bit and came up with a layout where the date switcher stays fixed at the top and the daily energy/nutrient counts stay fixed at the bottom. The content in between is scrollable.

![Screenshot 2021-10-04 143147](https://user-images.githubusercontent.com/19289477/135852451-60f4dcba-671a-4a83-bf7d-ccdf29150294.png)

If it's alright I can create a pull request so this can be included in the next release already.
