### ISSUE TITLE
Calories are not calculated based on serving size

### ISSUE THREAD

**Issue by cyko69** [davidhealey/waistline#38]
When adding food from OFF the calories are not based on the serving size instead the calories per 100g getting added.

**Comment by davidhealey** [comment]
Could you send me a few screenshots for different products that have this issue please?

Sometimes people enter a serving size but put in the nutritional information for the 100g so Waistline is setup to try to get the best match but this isn't always correct.

**Comment by cyko69** [comment]
Here are two Foods that both have calories per 100g in the description but sifferent serving sizes

Am 10. August 2018 14:42:30 MESZ schrieb David Healey <notifications@github.com>:
>Could you send me a few screenshots for different products that have
>this issue please?
>
>Sometimes people enter a serving size but put in the nutritional
>information for the 100g so Waistline is setup to try to get the best
>match but this isn't always correct.

**Comment by davidhealey** [comment]
Thank you. As I thought it seems that whoever added this food put in a serving size but added the data for 100g so Waistline is getting the correct serving size but the data for that serving size doesn't exist in the database.

I'll think of a way to improve this in Waistline so if the data is missing it automatically calculates it from the 100g.

Here's the data in OFF

![screenshot from 2018-08-10 14-42-14](https://user-images.githubusercontent.com/14021202/43961040-d0ba2180-9cab-11e8-904e-94eb7c37a873.png)

**Comment by cyko69** [comment]
That would be great!

**Comment by phpmoli** [comment]
Dear @davidhealey ,

Thanks for the app, i started using it today, after using Lifesum for a full month and realizing, i am spending hours of typing in nutritional info to someone elses closed database and correcting other users mistakes by submitting many reports and not getting any response whatsoever, not one, so i got fed up with that.

This bug also affects me, and it is a must to fix to be able to properly use it as a calorie counter app.

Thank you for your work.

**Comment by davidhealey** [comment]
Hi, it's not actually a bug, it's just not implemented as well as it could be :p I will fix this for the next release though.

**Comment by davidhealey** [comment]
Ok I think I've found a better way to do this, although it may still have problems if people haven't added data correctly. So if a serving size is given or the product was uploaded with the per_serving option enabled then the data will be pulled down with the assumption that the data is per serving. If no serving is found then it will default to per 100g and as a final fallback if there is no per 100g data the app will just look at the product quantity value and corresponding nutriment data. This will be in the next update.
