### ISSUE TITLE
[Feature] Custom Pages To Personalize Tracking

### ISSUE THREAD

**Issue by seniorm0ment** [davidhealey/waistline#384]
I personally am interested in tracking workouts and water intake.
I see in closed issues you have mentioned that you personally have no interest, and while completely understandable, other people do have interest in these.

While I see you made it possible to add negstive values for workouts, it would be very nice to be able to create a custom page (like Diary has it's own page, Food and Meals has it's own page, and the user could create a custom Workout page or a Water intake page). This can also be used to seperate nutrition from the diary if say the user wishes to track vitamin intake separately from the Food they intake l, they can make a page for Vitamins. So it is very versatile.

Basically it'd be a page to store custom positive/negative values, and any custom fields the user chooses.
The option for custom fields could be introduced to allow the user to just keep progress of how many sets and reps they do of each exercise, or anything else they might want to track. This allows them to see progress over a period of time.

This would allow for A LOT of versatility and not require you the developer to make new pages for everything users may want. Basically give the users the power to make custom pages to fit their needs.

Ideally have it automatically generate graphs based on what they input per page. Custom categories could be made to track individual things (similar to how Protein, Fat, Carbs, etc is tracked with the Diary page).

It would allow the app to be a more complete health and nutrition tracking application, as there really is no other decent libre apps available that do this all in one. Even the nutrition focused ones are heavily lacking or not being developed.

**Comment by EmilJunker** [comment]
You can already add your own fields. This isn't officially documented anywhere, though. Simply navigate to Settings and export to a json file, then open the json file in any text editor and add the fields you want under `settings.nutriments.order`, and then re-import the json file. You should now see them listed in Waistline under Settings > Nutriments and under Goals as well.

This way, you could add a custom field for "water", for example. And you could also add your favorite workouts, I guess.

**Comment by seniorm0ment** [comment]
I feel as if I'm making it more complicated than it is.
It'd just be an empty clone of the page that already exists for food tracking, with empty fields the user can label whatever they wish.

I can understand statistics generation to maybe be a bit much but it would make custom pages a bit nicer if it was possible.

**Comment by seniorm0ment** [comment]
That is all good, however again the json file is not very end user friendly and tedious to constantly make changes to. A way to interface with it to add the custom fields would be ideal. A simple plus button to add a new field, and have the field name be editable.

And the custom category in diary is nice, however being able to have a seperate page isolated from the food diary is ideal. That is what I meant by "pages". 
It could be just another diary page so I can have a custom "Workout Diary" and the "Food Diary".
These would just show up in that hamburger menu when you swipe in. That way it's isolated from the food diary.

**Comment by NonDJ** [comment]
Thank you! I´t doesn´t work because Android 11 don´t show the minus symbol on the display keyboard but it works by entering the minus with the bluetooth keyboard.
