### ISSUE TITLE
[Bug] F-Droid Version Missing Icon

### ISSUE THREAD

**Issue by seniorm0ment** [davidhealey/waistline#385]
The icon for Waistline on F-Droid seems to be missing?

**Comment by EmilJunker** [comment]
It worked! The icon and screenshots are now live:
https://f-droid.org/packages/com.waist.line/

The description still says that Waistline is in beta, though. I think to get rid of this, someone would need to make a pull request to remove the old description from the metadata file in the fdroiddata Gitlab repository:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.waist.line.yml

**Comment by EmilJunker** [comment]
The f-droid listing has been updated again:
https://f-droid.org/packages/com.waist.line/

The "beta" label is gone and new links for translation and donations have been added.

I think this issue can be closed now.

**Comment by davidhealey** [comment]
@EmilJunker Excellent, thank you
