### ISSUE TITLE
Saturated fats

### ISSUE THREAD

**Issue by Sirove** [davidhealey/waistline#39]
Hi there, :)

It would be nice if you could extend the data import from Open Food Facts with saturated fats.

![saturatedfats](https://user-images.githubusercontent.com/24733228/44216080-5b9b9000-a174-11e8-9ac3-9bdabf2cf98e.png)

**Comment by davidhealey** [comment]
This shouldn't be too tricky to add but it's not a priority, I'll add it if I find time

**Comment by Sirove** [comment]
The problem is that it is an essential feature for me... The only thing preventing me from switching to this app is that I would need to scan all my food twice. Right now and right after this feature get's implemented.

**Comment by davidhealey** [comment]
I've added this feature now, it will be available in the next update. Thanks for the suggestion.
