### ISSUE TITLE
Link button should be enabled by default for OFF results

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#394]
This was the original behaviour but I changed it to default to disabled, however in practice I'm always enabling it to make edits before I add the OFF item to my local DB so I think it makes sense to enable it by default.

**Comment by EmilJunker** [comment]
I would prefer the button to be disabled by default. Maybe add a setting so the user can specify what should be the default?

**Comment by davidhealey** [comment]
> I would prefer the button to be disabled by default

Any particular reason?

**Comment by EmilJunker** [comment]
> Any particular reason?

Mainly so I can change the portion size and unit without messing up the values. Like changing it from "1 slice" to "30 g", for instance.

**Comment by davidhealey** [comment]
Good reason, I agree that a setting is the way to solve this.

**Comment by davidhealey** [comment]
I've changed my mind about this now. The more I think about it the more I think I do the same as you and change the units and portion sizes of OFF items :)
