### ISSUE TITLE
Show calories of selected items in foodlist

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#395]
When checking multiple items in the foodlist it would be nice to see the total number of calories for those items in the top bar.

**Comment by davidhealey** [comment]
I've added this now for foods - 11542787c4a4a5c57a59ea487803c383606704fc

Just needs to be added for meals and recipes, probably next weekend.

**Comment by EmilJunker** [comment]
No need to make this so complicated ;) It can simply reuse the nutrition values that have already been computed for the list items to calculate the energy sum. This way it also works for meals and recipes. See #403.

**Comment by davidhealey** [comment]
Excellent, thank you
