### ISSUE TITLE
Unable to Scan Barcodes

### ISSUE THREAD

**Issue by zinonweke** [davidhealey/waistline#4]
#### Expected behavior

I expected that the barcode scanner will easily recognize barcodes, scan and capture them

#### Actual behavior

I tried to capture different barcodes of food lists, and the scanner couldn't scan and capture.

#### How to reproduce

* Launch Waistline 

* Select "food list" 

* Click on the "plus" logo on the top right to add food list

* Enter the food details 

* On the top right, click on the camera icon to capture barcode

* Try scanning any food item barcode. 

**App name/App version:** Waistline/ Version 1.0.1

**Operating system:** Android 7.0

**Device:** Tecno Camon CX 

#### Recording Of The Bug

https://youtu.be/EfmKuxaM0wg

**Comment by davidhealey** [comment]
Hi, thanks for the video. It looks to me like it's not working because your camera is not focused, the image is very blurry, although this could just be the video compression. Does it look as blurry to you as it does in the video? Have you used any other barcode scanner apps with that device?

**Comment by zinonweke** [comment]
Sorry about the false alarm. The problem was from my camera settings.

Thanks for the attention to gave to my issue, and for the application you developed. Please keep up the good work. Thanks once again.
