### ISSUE TITLE
Average weekly weight

### ISSUE THREAD

**Issue by Hobbyist11** [davidhealey/waistline#407]
Greetings, I would just like to ask if it is possible to see the weekly weight with decimals? Since it seems to round it off to whole numbers?

Thank you

**Comment by EmilJunker** [comment]
Hi, this was changed in version 3.2.0, it now shows up to two decimals for the average.

Unfortunately, this version isn't yet available on f-droid. So if you downloaded via f-droid, you'll have to wait a few more days to get this version. Just be patient :)

**Comment by Hobbyist11** [comment]
Thanks a lot for this amazing app! Will continue supporting it and also share it with others!
