### ISSUE TITLE
Omega-6-Fat missing

### ISSUE THREAD

**Issue by PhilippHartung** [davidhealey/waistline#417]
In index.js there is "monounsaturated-fat" and "omega-3-fat" considered.
As per my understanding omega3/6 is a subgroup of monounsaturated fat and a ratio of 5:1 (omega6:omega3) is recommended by the WHO. So also an entry for "omega-6-fat" would be nice within waistline.

**Comment by EmilJunker** [comment]
There are actually three kinds of omega fatty acids: omega 3, omega 6 and omega 9.

Here is an OFF listing that specifies all of them:
https://world.openfoodfacts.org/product/3155251205302/tartine-doux-primevere

And here is the corresponding API link:
https://world.openfoodfacts.org/api/v0/products/3155251205302

Waistline already supports omega 3. It shouldn't be difficult to add support for omega 6 and 9 as well.
