### ISSUE TITLE
Editing food item's Vitamin B2 values changes their Vitamin K values

### ISSUE THREAD

**Issue by glacambre** [davidhealey/waistline#427]
Waistline version: 3.2.1, downloaded from F-Droid

I tried to edit the B2 value of a food item downloaded from OpenFoodFacts (barcode 3560070590582). Its "portion" value originally was 25, but I changed it to 100 for easier editing.

Then, I set its "Vitamin K" value to 7. Then, I set its "Vitamin B2" value to 0.03. This resulted in the "Vitamin K" value being changed to 70. Changing "Vitamin K" from 70 back to 7 resulted in "Vitamin B2" being set to 0.

While this bug was 100% reproducible in the food item editing screen (= setting "Vitamin B2" to 0.03 deterministically changed "Vitamin K" to 70), I couldn't manage to reproduce this bug when I deleted the food item and created a new one by downloading it from OpenFoodFact again.

**Comment by davidhealey** [comment]
This isn't a bug. You had the link button activated.

**Comment by glacambre** [comment]
I guess there is something I don't understand then.

I created a new food item with a "portion" value of 100 and a unit of "g". I then edited that item to set its "Vitamin K" value to 7. No matter what state the link button is in (either activated or deactivated), changing the value of "Vitamin B2" does not change the value of "Vitamin K" for me.

Is there a user guide somewhere that I could read in order to better understand how Waitsline works?

**Comment by davidhealey** [comment]
If the values were at 0 the first time you edited them then changing them will have no effect until those values have been saved.

Create an item, give it a name, serving, unit, calories, B2, and VitK value.
Save the item.
Open the item to edit again, make sure the link button is enabled.
Change the serving, calories, or vitamin value and click out of the box you're editing (or click save) and the other values should update.

**Comment by glacambre** [comment]
Okay. I'm almost certain that I set the Vitamin K and Vitamin B2 values at the same time (= both were empty before I tried to set them), but you know your application better tham me, so I must be misremembering what I did.

Thanks a lot for answering my questions and sorry for the noise :).
