### ISSUE TITLE
Log food size

### ISSUE THREAD

**Issue by serioususer** [davidhealey/waistline#429]
I can add food to the app and enter the nutrition values easily but i cant see how to change the serving sizes in the daily logs. If i change the serving size the nutrition value in the food section gets changed.

Is it possible to add a button to enter the serving size for each meal without changing the portion size in the food section?

**Comment by davidhealey** [comment]
I don't quite understand. If you change the number or size of servings then the nutritional values must also change. You can't turn one egg into two eggs and keep the same nutritional data. Could you explain in more detail what you're wanting to do so I can better understand?

**Comment by serioususer** [comment]
Ah i see. I did not see that the nutrition values change aswell - my bad.
Everything works fine!

There are some products with wrong nutrition values but they need to be change in the open food facts app.

Thanks for the quick answer!
