### ISSUE TITLE
Open Food Facts imports kilojoules instead of kilocalories

### ISSUE THREAD

**Issue by Sirove** [davidhealey/waistline#44]
It seems like Waistline imports kilojoules instead of kilocalories. Is this intended?

**Comment by davidhealey** [comment]
It should be the opposite, which version are you using?

**Comment by Sirove** [comment]
Version 2.2.0 from the Google Play Store.

As far as I can see all other data is being imported correctly from Open Food Facts.

**Comment by davidhealey** [comment]
aha well something has gone wrong. I will check it out this evening.

**Comment by davidhealey** [comment]
I've fixed this now. I'll try and update play store later today or tomorrow. There may still be some edge cases where it uses kilojules instead of kcal, if you find any please let me know the barcode so I can test.

**Comment by davidhealey** [comment]
I've rolled out the new version now with the bug fixes, should reach your device shortly
