### ISSUE TITLE
Ability to show remaining calories for day

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#442]
On the bottom of the diary, there's the label "Calories \n 1500 / 2000". Tapping on this label should alternate between showing spent calories and remaining calories. A possible format for displaying remaining calories is "Calories \n 2000 &minus; 500". EDIT: Surpassing the daily goal (like "2500 / 2000") would become "Calories \n 2000 + 500".

Note that a real typographical minus sign instead of a short hyphen is more fitting. Visually, this is identical to the plus sign without the vertical bar. HTML entity: `&minus;`. Unicode: U+2212.

The new behavior would be analogous to that of audio players like VLC for Android that toggle between time elapsed and time remaining when tapping the respective label.

**Comment by davidhealey** [comment]
I already have this feature planned, it was there in previous versions but somehow I missed it with the rewrite.
