### ISSUE TITLE
Out-of-place overlay

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#444]
To reproduce:

- Be in diary with existing entries.
- Tap on entry to edit it.
- Directly long-press on contents of "Portion Size" textbox (do not tap).
- Press back button to hide keyboard.
- Press back button to leave editing view.
- Now, there's a wide overlay over the diary that says (translated) "Copy Share Select All" and that doesn't want to go away. Even if you tap "Copy" or "Share" and the overlay gets hidden, it'll be there again after switching to another app and back to Waistline.

**Comment by EmilJunker** [comment]
Duplicate #419

**Comment by h-h-h-h** [comment]
Who would've thought.
