### ISSUE TITLE
Support for not using diary categories

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#451]
I'm talking about the categories defined under "Settings > Diary > Categories". I have only defined one category for a long time (and I'm hesitant to try what happens if I delete this one). I gave it a generic name in Waisline v2, because it probably didn't work without a category back then. I just don't need these category concepts like "Lunch", because things are not that defined for me.

But, starting with the settings page (a switch there would be good), the app should support not working with categories at all. This would also imply a different rendering of the diary -- one without sections or so. And in the diary entry editor, it saves vertical space and makes everything less cluttered to hide the "Category" line.

BTW: If I'm going to the food list via main menu and add a food to the diary, I'm getting asked "Which meal is this?", where I *have* to tap on my single category name (not even the back button works). That doesn't make sense.

**Comment by davidhealey** [comment]
Unless there is a massive demand for this, removing the categories isn't going to happen.

As for the second point with having to select a category from the food list. I think that if there is only one category it should be selected by default and the popup shouldn't be displayed in this case.

**Comment by h-h-h-h** [comment]
> As for the second point with having to select a category from the food list. I think that if there is only one category it should be selected by default and the popup shouldn't be displayed in this case.

If there's only one category, couldn't you please also hide the "Category" line in the food editor?

---

What happens if I remove all text from the category-1 textbox in my settings? And does renaming the category confuse the app in any way at any time?

**Comment by davidhealey** [comment]
> If there's only one category, couldn't you please also hide the "Category" line in the food editor?

But what about people who want the category? I'd have to add an additional option. Maybe we could set it up so if you clear all your category names it will not show a category in the diary, although I don't know how tricky this will be to implement given that the structure is currently based on the categories.

> What happens if I remove all text from the category-1 textbox in my settings? 

Try it and see, but make a backup first. 

> And does renaming the category confuse the app in any way at any time?

You can rename the categories at any time (you have to restart the app for it to take effect though). The diary itself just pulls the names from a list, internally it uses indexes.

**Comment by h-h-h-h** [comment]
> But what about people who want the category?

I'm not sure what you mean. We're talking about an app instance in whose settings just one category is defined. When a diary entry is edited, the "Category" line shows the *one* predictable category name, and when tapping on it, a list overlay with a single option appears. When would anybody gain value out of this? This is an opportunity for decluttering. (To be clear: The line should only be hidden, if there's just one category.)

> I'd have to add an additional option.

Should it not be straightforward to determine if the day of a diary entry only has one category -- perhaps because there could be cases of past entries, where a user may have had more than one category -- a setting to generally hide the category line may be the way to go, instead of trying to be context-sensitive.

> Maybe we could set it up so if you clear all your category names it will not show a category in the diary, although I don't know how tricky this will be to implement given that the structure is currently based on the categories.

This sounds like my original request (second paragraph). Having a switch on top of the settings page that disables all category name textboxes just would be a clearer way, that also provides transparency about this possibility, to state "I don't want to work with categories." You wouldn't even need an additional internal flag. Just, whenever visiting the settings page, set the switch according to whether all textboxes are empty; and when switching categories off, clear all textboxes (but make them bounce back to their previous contents for the lifetime of the settings page).

I don't know how the app behaves, if you define the categories, e.g., as `[ "foo", "", "bar" ]`. It shouldn't be accepted, because empty category names should only be allowed at the end of the list. (Perhaps only ever enable the next empty textbox after the last one with content and disable the follow-up ones?) And when that's the case and *all* category names are empty, and empty name for the *first* category could -- as a special case -- be accepted as the actual category name -- a default name that leads to category sections not being displayed in the diary.
