### ISSUE TITLE
Values not linked when creating new food

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#453]
When manually creating a new food and having entered all 100-g values, you can't directly gross up to the net package weight. Also, the "link" toggle button at the top is missing. You have to save, edit again and then enter the package weight. This isn't the case when scanning a food (then, you need to enable linking, though, which should be enabled by default).

**Comment by davidhealey** [comment]
Link button is only for existing foods (including those pulled down from a database via barcode scanning).

**Comment by h-h-h-h** [comment]
This is not so practical for manual food creation. Is it supposed to stay that way?

**Comment by davidhealey** [comment]
It's by design. Can't remember the exact reasons but I presume that the code that does the calculating of the values needs some existing data from the database in order to be able to do its thing. Or there could be some totally different reason for it.
