### ISSUE TITLE
"Next" keyboard button to go from "Notes" to "Calories"

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#454]
When defining a new food and going through the textboxes in order with the "Next" keyboard button, you're stuck at "Notes" and can't go over to "Calories".

Or am I misjudging this, does it have to do with "Notes" being a multiline textbox and it'll become a non-issue when https://github.com/davidhealey/waistline/issues/443#issuecomment-1016420461 is done?

**Comment by davidhealey** [comment]
I don't have a "Next" button on my keyboard so I don't know...

**Comment by h-h-h-h** [comment]
It just has to do with "Notes" being a multiline textbox. I missed a patch version. With v3.2.1, the setting to hide notes didn't seem to have worked.
