### ISSUE TITLE
Nutrition value with 3 decimal places invalid

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#455]
When, for the line "Salt (g)", I try to enter the value "0.046", as it's written on the package, it says "Invalid value."

I think values with many decimal places should always be accepted and saved accurately, even if the presentation thereafter is rounded to 2 decimal places.

**Comment by davidhealey** [comment]
I don't see a reason we shouldn't be able to save such values.

What product is that?

**Comment by h-h-h-h** [comment]
[Ferrero Pocket Coffee](https://img.rewe-static.de/5067740/3609140_digital-image.png)
