### ISSUE TITLE
Proper number formatting

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#456]
My app instance uses the German locale. That means decimal separator `,` instead of `.`. And also, while leaving out an initial `0` and starting with the decimal separator has a degree of popularity in English, it's totally uncommon in German and looks very strange. My software number keyboard, though, only has `.`, not `,`, and I find it practical to not bother entering the `0` when the machine understands me anyway, so I'll often enter `.5`, e.g.

In the food editor, nutrition values are correctly displayed with `,` and leading `0`.

On the bottom of the diary, fat, carbs and protein are incorrectly displayed with `.`. Same for the statistic section of the app.

In the diary overview, portion counts incorrectly use `.` (like `×.5`). And the display of a leading `0` incorrectly follows whether you entered it when editing the entry. When editing, "Number of Servings" uses `,`, but incorrectly no leading `0` if you didn't enter it in the past.

Separating numbers and units is inconsistent throughout the app. In the diary and the food list, sometimes zero characters (like for `g` and `ml`) and sometimes a space is used (like for `Stück` [= piece(s)]). The right-aligned `kcal` always uses a space. In my view, consistently using a narrow no-break space (U+202F) or a thin space (U+2009), whose merits are the existence of an HTML entity (`&thinsp;`), should be tried.

I also find the uneven spacing surrounding `×` in "400g ×0.5" to be odd. I'd use spaces on both sides.

**Comment by h-h-h-h** [comment]
@EmilJunker:

> When editing, "Number of Servings" uses `,`, but incorrectly no leading `0` if you didn't enter it in the past. [@h-h-h-h]

This problem still persists:

![Screenshot_20220205-182120_Waistline](https://user-images.githubusercontent.com/13482553/152652032-bf53767a-8c3e-4369-ac7b-86da6aecf347.jpg)

**Comment by EmilJunker** [comment]
> This problem still persists in v3.2.3:

I'm aware of that. This can't be so easily fixed. If you enter a value of ".5" or ",5" into the text box, then this is the value that gets stored, and thus it's also the value that is displayed when you open the item for editing. Is that a problem?

**Comment by h-h-h-h** [comment]
This is not the case for the nutriments. When I enter `.5` there and save, it shows as `0,5` when I come back. Why is it different for Number of Servings? It's just odd.

**Comment by EmilJunker** [comment]
Oh, interesting 🤔. I didn't know that. I'll investigate it when I have time.
