### ISSUE TITLE
In diary view, the total calories calculated are higher than actual fats, carbs and proteins amount to

### ISSUE THREAD

**Issue by lolgithublol** [davidhealey/waistline#481]
The app usually counts 50-90kcal more

**Comment by EmilJunker** [comment]
The app will count whichever values you feed into it. If you add an item to the diary that has 20g carbs and 100 kcal energy, then this is what will be displayed (even if 20g of carbs really should only account for around 80 kcal).

**Comment by lolgithublol** [comment]
> The app will count whichever values you feed into it. If you add an item to the diary that has 20g carbs and 100 kcal energy, then this is what will be displayed (even if 20g of carbs really should only account for around 80 kcal).

I see, I'll double check all the food then. Thank you
