### ISSUE TITLE
Multiple suggestions (Body fat measurement)

### ISSUE THREAD

**Issue by Sirove** [davidhealey/waistline#49]
First of all: Thank you for this powerful and clean app! :)

While importing items I got a few things on my mind:

- Could you switch the positions of "brand" with "name" on the food list? I find it more intuitive. Most people write shopping lists like that: "milk" "cheese" "bread". The brand is of secondary importance.

- If I edit the nutrition facts of a food item that is being used in a recipe, the recipe does not update those changes. Not even after a reboot.

- Double tapping to edit an item is in my opinion unintuitive. Probably because of the tapping animation. It does not suggest that there could be another option than checking those items. I'd recommend switching to a single long tap.

**Comment by Sirove** [comment]
- It would also be nice, if there was a way to copy single foods or recipes and create a new item out of this data.

- An option to sort foods and recipes alphabetically.

- When editing a recipe it shows the data of "Calories", "Protein" and "Fat". It seems like "Carbs" is missing. Also, maybe even add "Sugars" and "Saturated Fats"?

- More Statistics: It would be very good to have more detailed facts in numbers. An Overview of the numbers.

I really like your app and see much potential! What do you think about these suggestions?

**Comment by davidhealey** [comment]
Swapping the brand and name I think is a good idea, I'll probably add an option so the user can select a preference for this. 

Yes recipe items are unlinked from the food list, the same as the diary. This is in case a food product changes in the future you don't want it to also change the recipe. Or if you delete a food product you don't want it to be deleted from all your recipes. So the recipe system, like the diary system, assumes the food you have edited in the food list is final before you add it to the recipe/diary.

Currently long tap and hold is set to delete a food item. I could make it pop-up a list of choices when long tapping and holding. I think this is actually a good idea and perhaps double tap could be used to quick add an item to the diary. 

You can swipe the nutritional info on the recipe page to see more data, I haven't added saturated fat to this yet though.

What suggestions do you have for statistics?

**Comment by davidhealey** [comment]
Ok I've now implemented the option to choose if brand or product name comes first and I've added tap + hold options to edit or delete to both the food list items and recipe items. These changes will be in the next update. I'll probably push an update tomorrow because I also fixed an important bug.

**Comment by Sirove** [comment]
Thanks! I'll check it out.

I understand why items are unlinked but could you nevertheless add an option to link food items? Mistakes can happen and especially if a product isn't in the OFF database. It would take a lot of time to correct all entries retrospectively.

About the nutritional info: Swiping, I see. I think it would be nice to instantly see Calories, Fat, Carbs and Protein on the first and Saturated Fats, Sugar and Salt on the second page.

Statistics: I would like to see more clear numbers like "Goal", "Used" and "Remaining". For example: Total calories, fats, carbs, protein, etc. per Week, Month, 3 Months and the correlating days average data.
I like the diagram but it requires user interaction. The clean numbers themselves on one page would optimize the speed of the usability.

**Comment by davidhealey** [comment]
I don't I could make linking food items to the diary and recipes an option easily but I'll see what can be done. I shall look into what adjustments I can make based on your other two suggestions too.

**Comment by davidhealey** [comment]
Other than double tapping there are only two methods I can think of that would be fast and intuitive to get to the edit screen, and those are swiping, and having a separate edit button next to each item. If I implement either of these methods I'd need to also implement them for the diary and recipe screens too to keep the user experience consistent. 

I think TDEE is a better indicator than BMI and I have thought about implementing such a calculator, so it might appear at some point. How do you calculate body fat percentage?

**Comment by Sirove** [comment]
What do you think about disabling the checklist feature as default but making it available via button on the upper right side next to the OFF scanner? This way the single tap default action would be editing the current item.

Yes, I agree. TDEE is a much better indicator but I think we should have both of them. To measure body fat percentage I use a Skinfold Caliper. The available formulas vary. Unfortunately I don't know which are the optimal ones.

**Comment by davidhealey** [comment]
If checkbox is disabled and singe tap edits, how do you add food to the diary?

I don't think I'll include a body fat percentage, it's too niche and isn't really what the app is designed for. What I might add is the ability to record a custom value so that if you want to track another stat you can but I don't have to worry about what the stat is :)

**Comment by Sirove** [comment]
While adding food to the diary/recipes the view should stay the same. I'm only talking about the "Food List" and "Recipes" main menu pages themselves.

Fair enough :)

**Comment by davidhealey** [comment]
Oh I understand now.

**Comment by davidhealey** [comment]
I'm going to retain the current method of editing items (tap and hold) just because it's simpler for me than implementing another method. If someone else wants to take up this request though they are welcome to merge it back into the main fork.

**Comment by davidhealey** [comment]
I'll leave this issue open, if I get some more requests I might add it but really I'm only looking to add things that I'll use and I don't have a need for this so it will be low priority.

**Comment by jubalh** [comment]
I understand. I'm not familiar with Android development but suspect that the change shouldn't take that long to implement for someone who knows the codebase.

Thanks for letting this issue open. Would be great if it gets implemented eventually! :-)

**Comment by davidhealey** [comment]
Body fat tracking is available from the diary page in the next release. Brand placement is now fixed, in the secondary position (I don't plan to re-add the option to move it, but who knows!). Foods are now edited by single tap and selected via single tap on the checkbox.

**Comment by jubalh** [comment]
Thanks

**Comment by davidhealey** [comment]
Oh and foods are linked to the master food list. So if you edit a food the change will be reflected in the diary, recipes, and meals pages.
