### ISSUE TITLE
Can't change goal numbers. 

### ISSUE THREAD

**Issue by flamesking101** [davidhealey/waistline#496]
Can't change or enter goal numbers. I was mainly trying to change the calories, but other goals can't be changed either. Hitting the enter button doesn't execute. I've tried restarting phone, uninstalling, deleting data, reinstalling, and using a different keyboard.

**Comment by davidhealey** [comment]
Confirmed, not working here either

**Comment by BoltCitizen** [comment]
Same here, not working. Urgent bug, cant use it without
