### ISSUE TITLE
Add support for Open Food Facts

### ISSUE THREAD

**Issue by Anth0rx** [davidhealey/waistline#5]
Currently one need to manually add foods an and nutrition facts. An integration with [Open Food Facts](https://world.openfoodfacts.org/) would definitely ease the process and would probably offer further features. @openfoodfacts

**Comment by davidhealey** [comment]
It is already integrated with Open Food Facts. Just use the barcode scanner. Instructions are included in the app :)

**Comment by davidhealey** [comment]
There is no search API for Open Food Facts as far as I can see so I can't add a search function yet.

**Comment by natrius** [comment]
Actually it seems there is https://world.openfoodfacts.org/data
There is also a mailinglist so you get information before they change their (currently) experimental API.
It would be possible to Download a database export too, but i'm not sure if this would be convenient, specially later when the database is growing.

**Comment by davidhealey** [comment]
I only see the barcode api there which is the one I'm using. If I get time at some point I'll look into their official app and see if there is anything for searching. I considered adding the whole DB but it's pretty big and it would be on a per country basis and I couldn't be bothered. Most people don't eat that many different things so once your personal list is populated the list filter is all you really need.

**Comment by Anth0rx** [comment]
Ah, good to know. Thanks :)
