### ISSUE TITLE
Surprise data loss 

### ISSUE THREAD

**Issue by Schroedingberg** [davidhealey/waistline#500]
Just 30 minutes ago, almost all data (diary, nutritional values) were suddenly gone, without any interaction. Too bad that I just discovered the automatic backup option after that, but well, bad luck I guess.

The funny thing is, that my goal data are still there.

If you need any additional information just ask me, I am happy to provide more precise technical data once competently instructed.

**Comment by davidhealey** [comment]
You say the data is lost - are you sure it's lost or is it possible it's still there but not being displayed?

What happens if you try to do an export?

**Comment by Schroedingberg** [comment]
I can only report from my memory, since the initial reaction was panic, so I did not take much care to report the incident properly, but as far as I dan recall:

- I did not see the data anymore in the app, I can not confidently say that at this point the data were actually lost
- I exported this seemingly empty database
- I imported the resulting DB (sidenote: I guess that means that now my data are certainly gone)

**Comment by davidhealey** [comment]
> I exported this seemingly empty database

You did this manually or using the auto-backup?

**Comment by Schroedingberg** [comment]
I did it manually.

**Comment by Schroedingberg** [comment]
It could be this one, which weirdly has one food entry left, but I am not confident that this is the right one
[waistline_export.txt](https://github.com/davidhealey/waistline/files/8171054/waistline_export.txt)
(Changed ending to txt to allow upload)

**Comment by davidhealey** [comment]
That'll be the one but doesn't seem to have any data other than that food entry. Well there's not much I can do to solve the cause of the issue.

**Comment by h-h-h-h** [comment]
See https://github.com/davidhealey/waistline/issues/501#issuecomment-1057120468 to possibly improve the situation for the future.

**Comment by Schroedingberg** [comment]
Yeah, would have surprised me if anything could have been done with that low amount of information. Just thought it might be worth a shot to report this and maybe help find a bug. FYI I keep on using waistline (with auto backup from now on) since it still is an awesome app and makes my life so much easier :)
