### ISSUE TITLE
Auto-backup file doesn't contain backup data, but nonsense!

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#501]
Waistline version: 3.3.0

I've enabled the auto-backup feature for a while now. And I just saw that `/storage/emulated/0/Android/media/com.waist.line/waistline_auto_backup.json` contains nothing but `[object Object]` (used `.toString()` instead of `JSON.stringify()`?). The file has a timestamp with the same minute as Waistline was freshly opened.

When exporting manually via button press, `waistline_export.json` from the same directory is 1 megabyte big, so will probably contain an actual backup and valid JSON.

**Comment by h-h-h-h** [comment]
Maybe, as a general extra safety measure, a backup file shouldn't be overwritten, if the length of the new data is *wildly* smaller than the old file's size? Because, if a feature like auto-backup (when working) comes together with a bug like https://github.com/davidhealey/waistline/issues/500, not having overwritten the backup file with quite obviously decimated data, could've saved you. A percentage difference would probably not be the right thing, but a fixed amount of difference. Even if this means ineffectivity for smaller backup file sizes, the bigger files worthier of protection would benefit.

**Comment by Schroedingberg** [comment]
totally down with @h-h-h-h 's proposition. Really happy to see it already merged <3
