### ISSUE TITLE
Display common German time suffix "Uhr"

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#502]
In the settings, I enabled "Show Timestamps" (which, from my German perspective, should be renamed, since, for the user, this is only about times of day/clock times, not anything more specific like `2021-06-30T18:41:37+02:00`, even if this is the case behind the scenes).

Since there already is much data surrounding the times of day and there are no data descriptors ("Time of Day: 18:41"), the app should make use of established ways of framing data items as uniquely as possible -- just like the value in the line before also has a unit (e.g., 330&nbsp;ml). In US English, there is the use of "AM" and "PM", which `toLocaleTimeString()` will surely already take care of.

In German, while you *can* just present something like "18:41" and be understood, especially for the reasons explained, it would be much more intuitive to show "18:41 Uhr" instead -- a very common time format. `toLocaleTimeString()` doesn't take care of this.

So, I propose to add `diary.timeOfDay = "%s"` (or in `"foods-meals-recipes"`?) to [`locale-en.json`](https://github.com/davidhealey/waistline/blob/master/www/assets/locales/locale-en.json#L131) and use it in [`app.FoodsMealsRecipes.renderItem()`](https://github.com/davidhealey/waistline/blob/master/www/activities/foods-meals-recipes/js/foods-meals-recipes.js#L543). `%s` would be substituted with the result of `toLocaleTimeString()`. German would use the locale string value `%s Uhr` instead of `%s`.

Since phones in languages where more than just `%s` would be used can probably be configured in the system settings to produce a `toLocaleTimeString()` result like "06:41 PM", the code should probably check whether the result ends in something else than a decimal digit (or regex [`\p{Decimal_Number}`/`\p{Nd}`](https://unicodebook.readthedocs.io/unicode.html), which includes [digits used in Arabic](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString) etc.) and, if this is the case, fall back to using the pure result; because, at least in German, "06:41 PM Uhr" is something unheard of.

**Comment by davidhealey** [comment]
What does Uhr mean in English? Is it the same as AM/PM?

**Comment by EmilJunker** [comment]
> What does Uhr mean in English?

It's basically the equivalent of "o'clock".

But I disagree with @h-h-h-h about adding this suffix to the timestamps. I don't think anyone would be confused about the meaning of something like "18:41". It's pretty obvious that this is a time. And most email clients and other apps I know also display times without the "Uhr" suffix. There are also English-speaking countries like the UK where AM/PM isn't used, yet people have no problem recognizing timestamps.

**Comment by davidhealey** [comment]
@EmilJunker 
> I don't think anyone would be confused about the meaning of something like "18:41". It's pretty obvious that this is a time.

Yes I agree, it seems superfluous.

**Comment by h-h-h-h** [comment]
This is not about *ability* to recognize, but rather about guiding the eye and helping it with quicker, easier, more intuitive navigation (think noisiness). We could also leave out "kcal" on the right side of diary entries, because it's always the same, but having it is more intuitive and overall less cryptic.

If there are timestamps in a list of e-mails, having the same type of data in one column, at one big spot of the GUI (not intermingled like in Waistline) and also in conjunction with a date, helps being intuitively guided too. In single-e-mail view, there's often still the date that makes it more distinct.

If a language has to way of making times of day more distinct, bad luck; but it would be possible for German.

**Comment by davidhealey** [comment]
> If a language has to way of making times of day more distinct, bad luck; but it would be possible for German

This seems to be a distinctly German issue :) I think we wait to see if there is more demand for this.

**Comment by davidhealey** [comment]
> but, especially in sum, still make a difference

Oh I definitely agree. I just think there are more urgent issues that should be prioritized.

**Comment by PhoenixIV** [comment]
I like the subtle thought that goes into this. I just tried it and I am with this suggestion. The time is missing an identifier of some sort that identifies it as a time. One can well guess that it must be.

When there is a label like AM or PM it serves two purposes: It makes it very clear that the preceding number is a time, additional to the crucial identification of which half of the day.

A different solution would be to display a clock icon in front.



> We could also leave out "kcal" on the right side of diary entries, because it's always the same, but having it is more intuitive and overall less cryptic.

This.

**Comment by EmilJunker** [comment]
> The time is missing an identifier of some sort that identifies it as a time

The food item names and brands have no identifiers either, yet it's clear what they are from the context ;)
But I understand your point.

> We could also leave out "kcal" on the right side of diary entries, because it's always the same

Well, one could argue that it's possible to change the energy unit to kilojoules... but it would indeed still always be the same unit.

> A different solution would be to display a clock icon in front.

This is a wonderful idea! I think we should try that.
