### ISSUE TITLE
OFF search freezes

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#509]
When I search for an item the spinner just goes forever and the UI is unresponsive until I hit the Android back button.

Anyone else having this issue?

**Comment by EmilJunker** [comment]
OFF search is working fine for me. What happens when you scan a barcode? Does that work?

**Comment by davidhealey** [comment]
Yeah scanning works fine. I'll run a debug and figure out the issue when I have some free time, if it's not affecting anyone else then it's not a big deal.

**Comment by h-h-h-h** [comment]
I can search in OFF via enter button without the spinner going on and on.

**Comment by davidhealey** [comment]
@EmilJunker I found the culprit

```
Uncaught (in promise) SyntaxError: Invalid regular expression: /\P{Letter}/: Invalid escape
    at Object.parseItem (open-food-facts.js:115)
    at data.products.forEach (open-food-facts.js:60)
    at Array.forEach (native)
    at Promise.catch.err (open-food-facts.js:59)
```

**Comment by EmilJunker** [comment]
It looks like your phone doesn't support Unicode property escapes in regular expressions ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes)). I just noticed that this feature was added only in ES2018, so it makes sense that it isn't universally supported yet.

If we put this line in a try-catch block, then maybe we can have it fall back to a simpler regular expression on devices that don't support the Unicode one.

**Comment by EmilJunker** [comment]
I'll just add a function to app.Utils that handles this since we need it in several places:

```js
noLetterRegExp: function() {
  try {
    return new RegExp(/\P{Letter}/, "gu");
  } catch (e) {
    return new RegExp(/[^a-z]/, "gi");
  }
}
```

**Comment by h-h-h-h** [comment]
Or use an IIFE:

```js
nonLettersRegExp: (function() {
  try {
    return new RegExp(/\P{Letter}/, "gu");
  } catch (e) {
    return new RegExp(/[^a-z]/, "gi");
  }
})()
```
