### ISSUE TITLE
Food causes NaN in bottom bar

### ISSUE THREAD

**Issue by h-h-h-h** [davidhealey/waistline#516]
I have a food in my food list that I probably created with Waistline v2 and that only has the nutrition values calories and sugar set. (It has a barcode, in case you want to know.) When I add this food to the diary, the bottom bar values for fat, carbs and protein show "NaN / [number]".

I created items today to further test this. They only had calories and sugar set, one had a barcode, the other one hadn't. The problem didn't occur with these items.

**Comment by davidhealey** [comment]
I'd need to see the item in question in JSON format. Are you able to send over a backup file or are you able to analyse the JSON yourself and send over the object as text?

**Comment by h-h-h-h** [comment]
The food contains the value `null`, while other, surrounding items have `0` in those places.

```json
{
    "barcode": "4008467016318",
    "name": "Thai Style Pfanne. Wildlachs",
    "brand": "Costa",
    "portion": "450",
    "nutrition": {
        "calories": 455,
        "fat": null,
        "saturated-fat": null,
        "fiber": null,
        "salt": null,
        "sodium": 1.26,
        "proteins": null,
        "carbohydrates": null,
        "sugars": 9
    },
    "dateTime": "2022-03-11T20:31:20.710Z",
    "id": 951,
    "unit": "g",
    "type": "food"
}
```

**Comment by EmilJunker** [comment]
You must have imported that item some time ago. It still has the bug where the sodium value (in g) wasn't converted correctly (into mg) during the import. This bug was fixed in version 3.1.8 (released in October 2021).

I just imported the same item using the latest version of Waistline, and as you can see there are no null values (and also the sodium value was imported correctly):

```json
{
  "portion": "450",
  "type": "food",
  "barcode": "4008467016318",
  "unit": "g",
  "image_url": "undefined",
  "nutrition": {
    "fat": 15,
    "carbohydrates": 46,
    "sugars": 9,
    "proteins": 31,
    "salt": 3.15,
    "sodium": 1260
  },
  "name": "Thai Style Pfanne",
  "brand": "Costa",
  "archived": false,
  "dateTime": "2022-03-11T22:39:57.065Z",
  "id": 725
} 
```

What happens when you open the item for editing and then save it (without making any changes). Does that get rid of the null entries?

**Comment by h-h-h-h** [comment]
> What happens when you open the item for editing and then save it (without making any changes). Does that get rid of the null entries?

That transformed the item into the following:

```json
{
    "portion": "450",
    "id": 951,
    "type": "food",
    "dateTime": "2022-03-11T23:09:54.425Z",
    "barcode": "4008467016318",
    "unit": "g",
    "nutrition": {
        "calories": 455,
        "kilojoules": 1903.72,
        "sugars": 9,
        "sodium": 1.26
    },
    "name": "Thai Style Pfanne. Wildlachs",
    "brand": "Costa",
    "archived": false
}
```

Sodium is never displayed to me.

Wouldn't it be best to treat `null` as `0`? I think non-existent nutrition values are also treated as `0`.

**Comment by EmilJunker** [comment]
> Sodium is never displayed to me.

Me neither, but Waistline always imports all available values regardless of the user's nutriment visibility settings.

> Wouldn't it be best to treat `null` as `0`? I think non-existent nutrition values are also treated as `0`.

Yes. I think it already ignores `undefined` values. This is probably just a matter of changing a `!==` into a `!=` or something like that. Typical JavaScript weirdness.

**Comment by h-h-h-h** [comment]
> I think it already ignores `undefined` values.

I don't know what technology the database uses. But *JSON* doesn't know of `undefined`, just `null` or non-existent keys. JavaScript objects with explicit `undefined` values, passed through `JSON.stringify()` give you JSON without the respective keys.

Speaking of `undefined`: The JSON you posted contains the *string* `"undefined"`!
