### ISSUE TITLE
Feature: private synchronization, not 3rd party

### ISSUE THREAD

**Issue by face-t** [davidhealey/waistline#520]
I use syncthing (opensource) to synchronize Joplin (opensource) notes among few devices. It all happens without using 3rd party servers.

Syncthing connects to SD folder  with output files from Joplin and get them synced elsewhere. Any direction. Updated notes appear in more or less, real time.

With backup already built into Waistline and export being on SD, it might  be possible to do it between Android devices, manually.

If done automatically that would replace requirement to have, mentioned elsewhere, commercial cloud service.

Thanks for app. Looks well thought out.

**Comment by davidhealey** [comment]
Can you already Sync the backup folder of Waistline?

**Comment by face-t** [comment]
> Can you already Sync the backup folder of Waistline?

I didn't at the time of writing but I knew I can once I've seen where backup is being stored (android/media/).

Since I did sync folder between 2 androids. Setup  is less than 5min since Syncting was already up.

Unfortunately I had to install Waistline 2.4.1. 
Ver 3 and above doesn't load on my old tablet anymore (I guess framework change)(its Andro 7.2.1 and "latest" custom rom).
I tried to import synced file but I guess it's incompatible with v 3.2.3.
Unless I find update,
![creenahot](https://user-images.githubusercontent.com/2349550/158709068-88e9a12f-2dca-482d-8d4f-53b58424af16.png)
 change will not directly benefit me, but I think it's a good feature where we don't need to share data with data hogs.

**Comment by davidhealey** [comment]
I'm using Android 7.2.1 on my phone with version 3

**Comment by face-t** [comment]
I have upgraded webView, was able to run app, import worked, both devices in sync

**Comment by davidhealey** [comment]
Excellent! So the only thing missing is you'd like the process to be a bit more automatic? I don't see this happening because internally Waistline is using a database and as far as I know we can't sync this across devices (I'm not even sure it's accessible from outside the app).

**Comment by face-t** [comment]
Yeah. The only accessible (noroot) part is on backup db/file. You can see the synced folder path in hidden post.

I have seen ppl talking of sync to 3rd partyclloud. But I think for opensource project its much better to rely on other opensource project, especially so well maintained as Syncthing.

All the best

**Comment by davidhealey** [comment]
Yeah I don't think we'll get better than that so I'm going to close this issue. :)

**Comment by face-t** [comment]
Yeah. The accessible (noroot) part is only backup db/file. You can see the synced folder in hidden post.

I have seen ppl talking of sync to 3rd party. But I think for opensource project its much better to rely on other opensource project, especially so well maintained as Syncthing.

All the best
