### ISSUE TITLE
Use item units (1 package, 2 slices, 1 banana) instead of 100 g by default for USDA items

### ISSUE THREAD

**Issue by user234683** [davidhealey/waistline#524]
When scanning a barcode, or searching for an item, almost all results are displayed with a serving size of 100 g.

This makes for a mild annoyance when scanning a barcode, because I'll need to press the lock button for scaling, enter the calories on the package to scale all the nutrient numbers, then unlock it to change the unit to something sensible such as 1 package or 1 cup. For instance, I scanned a carton of milk, and it gave me 66.667 kcal for a "serving size" of 100 g. The correct numbers are 160 kcal for a serving size of 1 cup (or 240 mL).

Part of this might be a problem with Open Food Facts). It seems to be an issue primarily with US food items added by the user "kiliweb" which is always then edited by "Yuka" (which is an app). These users/app only add 100g and never add the serving size. Not sure if openfoodfacts is aware of this.

However, I know the USDA database has the item units, but waistline does not use them. For instance, searching "Bananas, overripe, raw" will give only the value for 100 g, even though the [USDA page](https://fdc.nal.usda.gov/fdc-app.html#/food-details/1105073/nutrients) for this item has a dropdown that let's you use "1 banana" as a unit. For generic food items, item units are more essential since, without actually weighing the item, there is no label to use to scale the numbers to the correct value.

**Comment by davidhealey** [comment]
Yes I think we are already using the best settings here

**Comment by user234683** [comment]
I just ran the query `curl -X GET "https://api.nal.usda.gov/fdc/v1/food/1105073?format=full&api_key=[my api key]" -H  "accept: application/json"` and in the response it has this key (foodPortions):
```
    "foodPortions": [
        {
            "id": 267488,
            "dataPoints": 50,
            "gramWeight": 110.0,
            "sequenceNumber": 1,
            "amount": 1.0,
            "modifier": "Peeled",
            "minDateAcquired": "12/2/2019",
            "measureUnit": {
                "id": 1119,
                "name": "Banana",
                "abbreviation": "Banana"
            },
            "minYearAcquired": 2019
        }
    ],
```
i.e. 1 Peeled Banana = 110 g. This seems like exactly what's needed and corresponds to the dropdown they have on the website. I wasn't sure about the serving size being used for the nutrients that were returned, but as long as we already know the values for 100 g, we have the conversion factor here, so can't we just use that?

**Comment by EmilJunker** [comment]
Waistline uses the `search` endpoint of the USDA API, i.e. `https://api.nal.usda.gov/fdc/v1/foods/search?query=<QUERY>&pageSize=15&api_key=<API_KEY>` and I'm not sure if that also returns portion sizes in such a standardized format.

**Comment by user234683** [comment]
We could at least make a second request when clicking on the food item or adding it to the diary

**Comment by EmilJunker** [comment]
I think this should be part of the re-download feature added in #402. The dialog should let you choose between downloading the values per 100g or per portion.

**Comment by user234683** [comment]
It wouldn't hurt to have that option in the re-download feature, however, it should still automatically use the item units by default when pulling from USDA, given that it already defaults to using item units when pulling from OFF.

**Comment by EmilJunker** [comment]
As I already pointed out, the USDA search API doesn't seem to provide standardized information about portion sizes. So as it stands, we only get this information when we fetch a single item from the API. That's why I'm proposing to make this part of the re-download feature.

I'll try to find out if there is a way to also get this information during search, but if there isn't then we'll have to accept this limitation for now. Fetching the serving size only when you click on an item would require a lot of internal restructuring, so I'd rather not implement it this way.

**Comment by EmilJunker** [comment]
Good news! I found a way to get the serving size information directly from the `search` endpoint of the USDA API. For example, here is the list of portion sizes (in the search API response they're called `foodMeasures`) for [Banana, raw](https://fdc.nal.usda.gov/fdc-app.html#/food-details/1102653/nutrients):

```json
...
"foodMeasures": [
{
  "disseminationText": "1 cup, mashed",
  "gramWeight": 225,
  "id": 236846,
  "modifier": "10118",
  "rank": 4,
  "measureUnitAbbreviation": "undetermined",
  "measureUnitName": "undetermined",
  "measureUnitId": 9999
},
{
  "disseminationText": "1 cup",
  "gramWeight": 150,
  "id": 239224,
  "modifier": "10205",
  "rank": 3,
  "measureUnitAbbreviation": "undetermined",
  "measureUnitName": "undetermined",
  "measureUnitId": 9999
},
{
  "disseminationText": "1 banana",
  "gramWeight": 126,
  "id": 246458,
  "modifier": "60343",
  "rank": 1,
  "measureUnitAbbreviation": "undetermined",
  "measureUnitName": "undetermined",
  "measureUnitId": 9999
},
{
  "disseminationText": "1 slice",
  "gramWeight": 6,
  "id": 251693,
  "modifier": "61935",
  "rank": 2,
  "measureUnitAbbreviation": "undetermined",
  "measureUnitName": "undetermined",
  "measureUnitId": 9999
},
{
  "disseminationText": "1 linear inch",
  "gramWeight": 15,
  "id": 253913,
  "modifier": "63525",
  "rank": 5,
  "measureUnitAbbreviation": "undetermined",
  "measureUnitName": "undetermined",
  "measureUnitId": 9999
},
{
  "disseminationText": "Quantity not specified",
  "gramWeight": 126,
  "id": 265413,
  "modifier": "90000",
  "rank": 6,
  "measureUnitAbbreviation": "undetermined",
  "measureUnitName": "undetermined",
  "measureUnitId": 9999
}
],
...
```

The only difficulty is to decide which entry from the portion list should be used. But I think as a general strategy it makes sense to pick whichever entry has the same `gramWeight` value as the last one (which is usually called "Quantity not specified") and if no such entry exists then simply fall back to the entry with the largest `gramWeight` value.

However, now comes the bad news. It looks like these `foodMeasures` are only available for items of the type `Survey (FNDDS)` (which, fortunately, make up a very large portion of the entries in the USDA database). But so-called `SR Legacy` entries like [Bananas, raw](https://fdc.nal.usda.gov/fdc-app.html#/food-details/173944/nutrients), `Foundation` type entries such as [Bananas, overripe, raw](https://fdc.nal.usda.gov/fdc-app.html#/food-details/1105073/nutrients) and `Branded` items like [BANANA (Wonder Natural Foods Corp)](https://fdc.nal.usda.gov/fdc-app.html#/food-details/2012128/nutrients) don't have their portion sizes specified in the search API. Their `foodMeasures` list is just empty:

```json
...
"foodMeasures": [],
...
```

But anyway, I think this is still better than nothing. And we don't need to make a second API request this way.

**Comment by davidhealey** [comment]
> But anyway, I think this is still better than nothing. And we don't need to make a second API request this way.

Yeah that looks excellent, good find!
