### ISSUE TITLE
OFF serving sizes with fractions (a / b) are not read correctly

### ISSUE THREAD

**Issue by user234683** [davidhealey/waistline#525]
[This item](https://world.openfoodfacts.org/product/0030000063545/cereal-quaker) has a serving size of "3/4" and a serving unit of "CupCerealAlone". However, in the Waistline app, the serving size is given as "3" (the /4 is not read).

**Comment by EmilJunker** [comment]
Support for decimals (like 0.33 L) was added in https://github.com/davidhealey/waistline/commit/ae2d0b0fa6077224bc45e5ac07aa061539f8f30f which will be part of the next release, but fractions are much more tricky...

**Comment by user234683** [comment]
I feel like you could start with a regular expression check on the `item.serving_size` field. Check if it matches `(\d+)\s*/\s*(\d+)` and if it does, use parseInt( first matching group) / parseInt( second matching group). Might not be pretty in the UI, but at the very least that would simply convert it to decimal so we don't have wrong data in the app like in this case.
