### ISSUE TITLE
Adding Request

### ISSUE THREAD

**Issue by serioususer** [davidhealey/waistline#537]
It would be nice if one could add a additional meal like snack2 or something.

And it would be fantastic if one could see the macors of each meal and not only the sum for all meals.

Greetings

**Comment by EmilJunker** [comment]
> And it would be fantastic if one could see the macors of each meal and not only the sum for all meals

If you tap on the energy total at the bottom of a meal category in the diary, it shows you the nutrition values of that meal.

**Comment by serioususer** [comment]
oh did not know that - thanks :)

what about adding some more meals? :)

**Comment by EmilJunker** [comment]
You can customize the meals list under `Settings > Diary > Categories`. This allows you to define up to seven meals. Note that you need to restart the app for the changes to take effect.

**Comment by serioususer** [comment]
Perfect! Thank you!

Closed.
