### ISSUE TITLE
Request - notes section in diary

### ISSUE THREAD

**Issue by justeepin** [davidhealey/waistline#543]
Besides counting calories, I'm trying to track when I get a migraine after eating. It would be helpful if there was a notes section in the diary tab so people could document any issues after eating to help narrow down any allergy to food or ingredients in certain foods.

**Comment by EmilJunker** [comment]
This may not be exactly what you asked for, but you could use the quick add feature in the diary to take notes.

To do this, tap and hold the plus button in the diary (this opens the quick add dialog) and enter a note into the description field (you can leave the calories field blank).

**Comment by justeepin** [comment]
That could work except there'd be no way to search or see an overview of the notes.

**Comment by davidhealey** [comment]
> no way to search or see an overview of the notes.

You didn't mention searching or an overview before ;)

But I think we're going beyond the scope of a calorie counter.

**Comment by justeepin** [comment]
But for people trying to figure out a possible food allergy, it would be very helpful to have it all in one app.
