### ISSUE TITLE
Add option to show calories remaining rather than calories consumed

### ISSUE THREAD

**Issue by trinity-geology-unstable** [davidhealey/waistline#548]
Most days I find myself calculating the difference between my consumed calories and my goal amount to see if I can fit in that last snack.. This used to be done in a previous version of the app but no longer. Can it be added back in perhaps as an optional toggle?

**Comment by davidhealey** [comment]
Yeah it's on my to do list to redo that entire section and bring back this feature

**Comment by h-h-h-h** [comment]
Duplicate of #442.
