### ISSUE TITLE
Excersize

### ISSUE THREAD

**Issue by hessianerd** [davidhealey/waistline#55]
Would be nice to be able to add excersize / calories burned to the diary.

**Comment by davidhealey** [comment]
It would :) but I never trust those things that tell you how many calories you burn for how much exercise. The calculations must be quite complex, let's just take walking for example. If you're going uphill you will use more energy than on the flat, if you walk briskly you will use more energy, if it's really cold outside you will use more energy, if you're a larger person you will use a different amount of energy to a smaller person, if you're older you will use more than someone who is younger.

I am not qualified to add such a complex feature :p

**Comment by grrrrr** [comment]
@davidhealey you don't have to do anything complex.   It's up to the user to figure out their calories burned, be it from a tracking device or guessing.     So just    `calories in - calories out`.   If someone chooses to lie about calories out all they are cheating is themselves.

But having a better idea of overall calories usable in a day is very useful.  Example at the moment I have Wastline tracking calories in and it showns me a nice daily total  and whether I am over my allotted daily calories but it does not take into account exercies  so now I have to add calories in to calories burned in my head (and keep track if I have multiple exercise sessions)   to figure out if I can have that extra cookie

**Comment by davidhealey** [comment]
Oh I see now what you mean. Ok this sounds like a good addition, but how about if I just make it so you can add negative calories to the diary using the existing quick add feature?

**Comment by grrrrr** [comment]
@davidhealey for me that would be suitable.   I don't have a need to track exercise, it's done elsewhere, so just multiple sets of negative calories would be great

**Comment by davidhealey** [comment]
Actually I just tested and you can already add negative calories via the quick add :) just tap and hold on a diary category (breakfast, lunch, etc.) and enter the number of calories (positive or negative).

**Comment by grrrrr** [comment]
Perfect.  I was not aware of the quick add feature.  I wonder if there's a way to make that more obvious?

**Comment by davidhealey** [comment]
I think it's in the user guide. I could also mention in the quick add popup about the ability to add negative calories.
