### ISSUE TITLE
[Request] Change location of Backups

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [davidhealey/waistline#553]
Hey,

It would be really handy to be able to change the location where the backups are being done. My idea is to make automatic backups to my nextcloud folder!

Thanks,
MiguelNdeCarvalho

**Comment by davidhealey** [comment]
> It would be really handy to be able to change the location where the backups are being done.

It would! If you find a solution let us know, we have been trying for a long time ;)

**Comment by MiguelNdeCarvalho** [comment]
Hey @davidhealey,

I have created the issue because I didn't see any with this subject, I would be very happy to help with the code, but I don't understand anything about the cordova framework.

Thanks,
MiguelNdeCarvalho

**Comment by davidhealey** [comment]
Related:
https://github.com/davidhealey/waistline/issues/506
https://github.com/davidhealey/waistline/issues/252

**Comment by EmilJunker** [comment]
Also related:
#410
#515

@MiguelNdeCarvalho Where is your nextcloud folder located? In my experience, the app can only write to certain shared storage locations.

**Comment by MiguelNdeCarvalho** [comment]
Thanks @davidhealey, @EmilJunker it is located in `/storage/emulated/0/Android/media/com.nextcloud.client`

**Comment by EmilJunker** [comment]
> /storage/emulated/0/Android/media/com.nextcloud.client

This isn't going to work, unfortunately. Waistline cannot write to the media directory of a different app.

**Comment by GabrieleV** [comment]
If you use the android file save ad dialog, nextcloud destination is showed in the storages section.

**Comment by davidhealey** [comment]
> android file save as dialog,

Waistline is a Cordova app, not an Android app.
