### ISSUE TITLE
bug: portion-size resets to 100ml in update

### ISSUE THREAD

**Issue by Tinsus** [davidhealey/waistline#557]
When updating a grocery from openfoodfacts the portion size is set to 100 even though in OFF it is set to some different value (40ml in my case)

Happend with that an other items. Always reset to 100 in portion size:
https://de.openfoodfacts.org/produkt/4004752006309/k%C3%BCstennebel-waldemar-behn

**Comment by EmilJunker** [comment]
Are you referring to the re-download feature in the food editor? It lets you choose between downloading the values per 100g/100ml or per portion. I just tested it with the product linked above, and it worked as expected.

**Comment by Tinsus** [comment]
Ok. Now I understand. I misunderstood it.

By law the food facts in Germany are per 100mL, 100g, 1kg or 1l basis. Sometimes a manufacturer additional include the per portion values for information. So I understood the food fact table itself would be downloaded as per portion or 100mL/100g basis. I always want to read in the app what stands on the packaging, so I choose 100ml and wounder why it also changed the portion size.

In my expectation, the basis of the food facts table can toggle between portion or 100g/mL basis, but the potion size itself needs to stay the potion sizes as it is in the packaging. Now I understand Waistline is not created this way. It's fine, I just needed to know that.
