### ISSUE TITLE
error in translation

### ISSUE THREAD

**Issue by Tinsus** [davidhealey/waistline#558]
In the german food Fach lost within the APP the kabel for alcohol reads "Alkohol (g)" but there is the value from OFF imported from "Alkohol (%)"
Please correct the localisation to percent instead of gramms.

**Comment by EmilJunker** [comment]
This is not a translation error. Waistline uses gramms for the alcohol field. I also can think of at least two good reasons for this:
- It doesn't make sense to set your personal goal in %.
- The USDA database uses gramms too.

But when the portion size it not equal to 100, the percent value obviously needs to be converted. For example, 30% of 200ml is approx. 60g and not 30g. So this is a bug that we need to fix.

**Comment by Tinsus** [comment]
Sorry, may my issue was not detailed enough.

I was talking about the import from OFF, there the values are in %, also on every food packaging the alcohol contains is printed in %. OFF is the default search engine, so that might be a problem only with OFF.

Sure, the goals in % doesn't make any sense, but all food facts on the packaging are in %. So may it could be necessary to split the alcohol fields in one field for a mass measurement and another field for percentages only.
So it could use alcohol in g from the goals and USDA only, but in % in the food facts and from OFF.

The calculation from one to the other value is straight forward and possible by the waistline app itself (using the density of Ethanol at 0.7893 g/cm³ and the portion size).

So if a drink contains 25g alcohol this would be 31.67mL, if served 100mL the drink has 31.67% alcohol,
if a drink contains 16% alcohol and is served with 100mL, it contains 12.63g alcohol.
