### ISSUE TITLE
Enhancement: scanning items to add directly

### ISSUE THREAD

**Issue by Tinsus** [davidhealey/waistline#560]
When I am in the diary and want to add some item I consumed, I need to search for it in the list of known items. I want to add the items by scanning the barcode, but when I scan it, it opens the details page without the option to add it to the diary.
Is it possible to handle a scanned item to add it to the diary if the barcode is known within my list of items, instead of opening the details page for edit?

**Comment by davidhealey** [comment]
That's a good idea
