### ISSUE TITLE
Is goal the best name?

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#566]
I'm just thinking should we be using the term Goal or is there a better term? Using goal makes it sound like it's something to aim for, but in the case of someone trying to lose weight the calorie "Goal" is really an upper limit, and the goal is to eat less than that limit not to reach it.

**Comment by EmilJunker** [comment]
I don't see a problem with the term goal. Even if you want to lose weight, you should still try to land somewhere around your daily goal (on average). Eating too little is not healthy either. And it's also fine if you overshoot your goal on one day, that just means you'll have to eat less on the next day (the auto-adjust feature can handle this for you).

**Comment by davidhealey** [comment]
Ok I'm convinced :)
