### ISSUE TITLE
[Feature Request] quick add calories button

### ISSUE THREAD

**Issue by MichaelKirkEngineer** [davidhealey/waistline#583]
Instead of creating a food/looking up a food, would be nice to have a button to quick add calories for the day.

Might be able to assign me to do it, its been a few years since I did any Android work.

**Comment by davidhealey** [comment]
Hello,

Waistline is written with Cordova, so you need web development skills more than Android.

The feature you're asking for is already there. Tap and hold the + button. I have plans in the future to make this more discoverable.

**Comment by MichaelKirkEngineer** [comment]
Thanks so much. Loving the app, if you have ideas on how to make it more
discoverable, let me know.

Wouldn't mind giving Cordova a shot. Used to do react native, but I suppose
that's still different.


Best Regards
