### ISSUE TITLE
Possible bug: Data values at the bottom of the Diary page

### ISSUE THREAD

**Issue by Rhadlaren** [davidhealey/waistline#586]
Hi all, 
I've noticed in a number of instances the statistics that appear at the lower edge of the screen in the diary page (e.g., the calories, fat, carbs, and proteins numbers) will often transition to seemingly random negative values when transitioning between pages.  The easiest way to reproduce this behavior is to tap the protein value at the bottom right in that screen. The display shifts to show a small pie chart, but then the numbers are negative and do not reflect the day's proper statistics.  This problem can resolve itself by switching back and forth, moving between screens, or restarting the app, but it does appear to be a reoccurring glitch! I thought I would mention it in case others have experienced this issue.  My device is a Galaxy S20+ running Android version 12, kernel 4.19.113-237225773 if that is helpful.
--Bill

**Comment by EmilJunker** [comment]
This isn't a bug. The negative value shows you how much more you need to eat to reach your goal. I added this feature in #567. I'm sorry if this confusion to you. I thought the meaning of the +/- sign would be self-explanatory 😅.

**Comment by Rhadlaren** [comment]
Oh okay -- apologies! :)
