### ISSUE TITLE
Adding sleep disturbance

### ISSUE THREAD

**Issue by rmosavi** [davidhealey/waistline#587]
Hi Sir,
can another say categories of health be added to the software? Or we want to measure  daily sleep quality, can we define it as a food category?

**Comment by EmilJunker** [comment]
@rmosavi To track your sleep quality in Waistline, you could add a custom "Sleep" nutrition field under `Settings > Nutriments > Add Field` (scroll all the way to the bottom of the list). You can then create a custom food item with a "Sleep" value of `1`.

You can now add this item to your diary and use the quantity field to enter the sleep quality (e.g. in percent with values ranging from 0 to 100).

To see your sleep quality over time, go to the Goals editor and enable the `Show in Statistics` option for the Sleep field. You should then see it listed on the Statistics page.
