### ISSUE TITLE
can't load fotos

### ISSUE THREAD

**Issue by imlinstress** [davidhealey/waistline#588]
Everytime i try to add a foto, it says, there is a problem accessing the camera. I granted all permissions available!

**Comment by davidhealey** [comment]
Which version of Waistline are you using? Which version of Android?

**Comment by imlinstress** [comment]
APP Version 3.4.1 running Android 12 (LineageOS).

**Comment by davidhealey** [comment]
Try the latest version 3.4.2, it has some fixes related to taking pictures.

**Comment by imlinstress** [comment]
It works! Very nice App!

**Comment by davidhealey** [comment]
Thanks!
