### ISSUE TITLE
Make footer in diary customizable

### ISSUE THREAD

**Issue by TalusUnheil** [davidhealey/waistline#589]
In the diary there is an overlay-footer showing Calories, Fat, Carbs and Proteins. Since different users have different nutritional goals, this footer should also be customizable. For example, I only need Calories and Proteins, but not Fat and Carbs. **So it would be nice if one could configure which values are displayed in the footer of the diary.**

If one taps on the footer, the display of the values changes.

When one holds the finger down on the footer, the smartphone vibrates briefly - so there seems to have been another way of interacting with the footer planned, but so far nothing more than the vibration is happening.

I have already tried to set single values (e.g. for fat and carbohydrates) for the goals simply empty, but the daily values are still displayed (only the comparison with the goals is omitted).

**Comment by davidhealey** [comment]
@EmilJunker Beat me to it. Btw I just noticed in the latest version that the list of Goals has vanished, any ideas?

**Comment by TalusUnheil** [comment]
> This is already possible. In the Goal editor, the is a `Show in Diary` toggle which you can enable or disable for each nutrient individually.

Thank your very much! I've been in the Goal editor several times and managed to overlook the button. I'm going to the basement now and feel ashamed.
