### ISSUE TITLE
Configure salt/sodium for locale

### ISSUE THREAD

**Issue by Mitlik** [davidhealey/waistline#59]
Could you add an option to select between salt and sodium? I get the feeling that the UK uses salt on labels, while in the US sodium is reported on labels. I see the OFF has both available, but when entering from labels I suspect only one is available. While I could try to remember to multiply the sodium by 2.5 to convert to salt, I suspect that looking up the ratio of sodium in salt by weight is not a burden you desire to place on users.

**Comment by davidhealey** [comment]
Yes salt is usually in grams here. Rather than adding an option to select between salt or sodium I'll probably just add fields for both because it will be a quicker fix.

**Comment by davidhealey** [comment]
I've added this now. I decided to add a setting so you can select to use either salt or sodium, and it's in mg. Will be available in the next update
