### ISSUE TITLE
Bug: "Ghost"-Item not edible

### ISSUE THREAD

**Issue by Tinsus** [davidhealey/waistline#590]
Hi there,

I have the following issue - and no Idea to reproduce.

1. I added a new by scanning a barcode
2. I added another new item by adding scanning a new barcode
3. somehow the first item was not listed to my item list (noticed that later)
4. I added the item to my diary by scanning the barcode of the first item
5. because I was not asked of the portion (opt-in setting active) I rescanned and re-added the item by scanning the barcode
6. the item did not appear in my diary
7. I noticed point 3
8. I closed the app (without hard-closing it using the android options)
9. I opend again and tried to add the first item until it showed my the "new item to add window" (needed several tries)
10. I added the now visible first item in my item list
11. the item appears in the diary
12. BUT: somehow the total in the category is 1070 kcal, the singly item is 214kcal
13. if I remove the only entry the empty category has 856 kcal
14. I can not remove the not visible (but somehow added) non item listed entries in the category for the single day

**Comment by davidhealey** [comment]
What version of Waistline?
What version of Android

> I added a new by scanning a barcode
> I added another new item by adding scanning a new barcode

What did you do between these steps? Did you edit the values after you scanned? Did you hit the save button? etc.

**Comment by Tinsus** [comment]
App: 3.4.1
Android: 12 (Build SQ3A.220605.009.B1 Kernel 5.10.81)

I saved the item after scanning using the tick in the top right, after that I scanned the other item on the same way

**Comment by EmilJunker** [comment]
@Tinsus Could you export your database (via Settings > Import/Export) and upload the json file here so we can better understand what is going on?

**Comment by Tinsus** [comment]
![signal-2022-06-17-014722_001](https://user-images.githubusercontent.com/1723247/174273844-5b7b53a7-a663-47f4-bc69-4a6ca406c8c0.png)
[waistline_export.txt](https://github.com/davidhealey/waistline/files/8926512/waistline_export.txt)

**Comment by EmilJunker** [comment]
It looks like the item was added to the diary five times, but only the last entry has the `"type": "food"` specified. That must be the reason why the other entries are not displayed and can't be removed. I don't know how or why this happened, though.

```json
{
  "dateTime": "2022-06-17T00:00:00.000Z",
  "items": [
    {
      "id": 111,
      "portion": "55",
      "quantity": "1",
      "dateTime": "2022-06-16T23:40:22.192Z",
      "category": 4
    },
    {
      "id": 111,
      "portion": "55",
      "quantity": "1",
      "dateTime": "2022-06-16T23:43:18.002Z",
      "category": 4
    },
    {
      "id": 111,
      "portion": "55",
      "quantity": "1",
      "dateTime": "2022-06-16T23:43:32.532Z",
      "category": 4
    },
    {
      "id": 111,
      "portion": "55",
      "quantity": "1",
      "dateTime": "2022-06-16T23:44:03.793Z",
      "category": 4
    },
    {
      "id": 111,
      "portion": "55",
      "quantity": "1",
      "type": "food",
      "dateTime": "2022-06-17T00:08:03.553Z",
      "category": 4
    }
  ],
  "stats": {},
  "id": 59
}
```

**Comment by davidhealey** [comment]
Yeah seems like a weird edge case. I guess one solution is to either always set a default `type` if it's missing before adding to the DB or to not allow any entries that don't have a type.

**Comment by Tinsus** [comment]
I reproduced the error:
1.
