### ISSUE TITLE
Calorie calculation

### ISSUE THREAD

**Issue by serioususer** [davidhealey/waistline#594]
It is more like a question than an issue.

How do your calc the calories?

As far as i know the kcal are:
1g fat = 9kcal
1g protein = 4kcal
1g carbs = 4kcal

But this does not match with your values.

Could you please explain?

**Comment by davidhealey** [comment]
Unless you've found a feature I'm unaware of Waistline doesn't do any calorie calculations based on nutriments. Any data you see that you didn't enter yourself is either from the Open Food Facts or USDA databases.

**Comment by serioususer** [comment]
You can define goals for your kcal, prot, fat, carbs, and so on...

In the diary section there are the kcal, prot, carbs values for all your meals.

If you count prot, fat and carbs together with the values mentioned above it does not match the kcal.
example:
80g fat * 9 = 700 kcal
80g prot * 4 = 320kcal
80g carbs * 4 = 320kcal
kcal_all = 320 + 320 + 700 = 1320kcal

kcal_all =/= kcal_app

**Comment by EmilJunker** [comment]
> @EmilJunker Is this something you added?

No, it's not. It's exactly as you said in the comment above. Waistline does not calculate the calories. Waistline uses the calories values from the OFF or USDA database.

See also #481.

> If you count prot, fat and carbs together with the values mentioned above it does not match the kcal.

Keep in mind that each gram of fiber does also contribute some energy (about 2 kcal I think).
