### ISSUE TITLE
Preview Images Bug

### ISSUE THREAD

**Issue by serioususer** [davidhealey/waistline#595]
You can enable the preview of all nutritions.

You got the option if the images are shown with and without wlan.

This feature works perfectly fine when your are in wlan.

but if you are not no images are shown.

**Comment by davidhealey** [comment]
Check your settings, this is an option that can be enabled/disabled to save data.

**Comment by serioususer** [comment]
Exactly.
The problem is that it is not showing even when enabled.

**Comment by EmilJunker** [comment]
It's working fine for me. Are you sure you set the right option? There are separate settings for the food list and for the diary.

**Comment by davidhealey** [comment]
Oh I see what it could be @serioususer Do you have data enabled when you turn off the wlan?

**Comment by serioususer** [comment]
yep data is enabled.

**Comment by davidhealey** [comment]
It's working for me with data enabled but not when I turn it off. What settings do you have enabled in foods, meals, recipes?

**Comment by serioususer** [comment]
> It's working fine for me. Are you sure you set the right option? There are separate settings for the food list and for the diary.

preview:
diary is working fine for me. 
nutrition list does not when wlan disabled.

**Comment by davidhealey** [comment]
I don't know what you mean by nutrition list. Are you referring to the list of foods?

**Comment by serioususer** [comment]
> It's working for me with data enabled but not when I turn it off. What settings do you have enabled in foods, meals, recipes?

meals:
alphabetic
show categories off
preview on
preview wlan on
nutrition images on
nutrition images wlan on
notes on

diary:
show clock off
preview off
preview wlan off
rest: on

**Comment by serioususer** [comment]
> I don't know what you mean by nutrition list. Are you referring to the list of foods?

yep, sorry. im talking about nutrition, meals, recepts

**Comment by serioususer** [comment]
the magic word was ONLY...

need to go to bed.

thank you
