### ISSUE TITLE
[Bug] Quick add and foods with negative kcal doesn't cause a recomputation of nutriments set as a % of energy intake

### ISSUE THREAD

**Issue by giovannivelludo** [davidhealey/waistline#596]
For example, let's say I have a calories goal of 2800 per day, and my fat goal is 30% of my energy intake, this results in a goal of 93 g of fat per day.
After adding -368 kcals of exercise the fat goal is still 93 g, but it should be (2800 + 368) * 0.3 / 9 = 105.6 g

Steps to reproduce:
+ set a goal to be a percentage of energy intake, and enable "Show in Diary"
+ create a food with negative calories (representing exercise)
+ add the newly created food to a meal
+ notice that in the diary the value of the goal set in the first step hasn't changed

Setting negative macronutrient values in foods is not allowed, and even if it was it wouldn't be a good idea because your % goals might change over time.

**Comment by EmilJunker** [comment]
The thing is that adding negative calories in the diary does not change the calories goal. If your calories goal was 2800 before, then it is still 2800 after adding the -368 burned calories. Hence, the other goals which are set as percentage of energy don't change either. Why should they?

**Comment by giovannivelludo** [comment]
Because my calorie goal for the day has now become 3168 kcal. MyFitnessPal recomputes macronutrient goals after adding exercise calories.

**Comment by davidhealey** [comment]
The goal shouldn't change. Do you mean the amount consumed?

**Comment by davidhealey** [comment]
I just checked. It seems quick add (positive or negative) is not affecting the display/calculation of the consumed amount of % based nutriments.

**Comment by giovannivelludo** [comment]
What I mean is that if my calorie goal is 2800 kcal and I burn 368 kcal with exercise, my energy intake for the day will have to be 3168 kcal. Since my fat goal was set as 30% of my energy intake, it should be 105.6 g (I don't know how values are rounded in Waistline) instead of 93 g (= 2800 * 0.3 / 9).

**Comment by EmilJunker** [comment]
Indeed, this affects both positive and negative quick add entries. It's a consequence of the fact that the quick add feature is only for calories and not for macro nutrients.

And this does not just affect nutrients set as percentage of energy either. This also happens if you set absolute goals.

I don't really know what a solution for this problem could look like tbh.

**Comment by giovannivelludo** [comment]
I don't think absolute goals should change since they're not dependent on energy intake

**Comment by davidhealey** [comment]
A workaround for now might be to add an `exercise` food item.

**Comment by giovannivelludo** [comment]
That's what I'm doing but it doesn't result in a recomputation of nutrients set as a %
![Screenshot_20220701-163922_Trebuchet](https://user-images.githubusercontent.com/56405609/176916014-4cee3413-3349-4020-b6eb-aa0ff992f184.png)

**Comment by giovannivelludo** [comment]
A solution could be to add foods with negative calories (as positive values) to the calorie goal for the day in which they're added. I don't know if it's doable.

**Comment by EmilJunker** [comment]
> I don't think absolute goals should change since they don't depend on energy intake

It's not about the goal changing. But if you log +200 kcal via the quick add feature, it only increases the comsumed amount for energy by 200, but it does not increase the consumed amounts of fat, carbs, and proteins (even though it is obvious that the 200 kcal must have come from somewhere).

That's why the quick add feature is really only meant for people who just care about tracking calories and not macro nutrients.

> That's what I'm doing but it doesn't result in a recomputation of nutrients set as a %

You need to specify the burned fat, carbs, and proteins as negative values in the item too. This is the workaround we were talking about.

**Comment by davidhealey** [comment]
> This is the workaround we were talking about.

I missed that part too :)

I don't think that is an ideal situation though because it means the user has to do the calculation manually. But as a workaround it's not bad. I think it's important to remember that Waistline is calorie counter and not an exercise tracker, so anything that goes towards tracking exercise is a bonus.

**Comment by giovannivelludo** [comment]
@EmilJunker
> > I don't think absolute goals should change since they don't depend on energy intake
> 
> It's not about the goal changing. But if you log +200 kcal via the quick add feature, it only increases the comsumed amount for energy by 200, but it does not increase the consumed amounts of fat, carbs, and proteins (even though it is obvious that the 200 kcal must have come from somewhere).
I have a goal of at least 120 grams of protein per day and this is regardless of what my energy intake is. If I wanted my goal (in grams) to change depending on energy intake I would have set it as a percentage of energy intake, the feature is already there.

> That's why the quick add feature is really only meant for people who just care about tracking calories and not macro nutrients.
> 
> > That's what I'm doing but it doesn't result in a recomputation of nutrients set as a %
> 
> You need to specify the burned fat, carbs, and proteins as negative values in the item too. This is the workaround we were talking about.

Negative values for macronutrients are not allowed, this would also require manually updating foods representing exercise every time somebodies % goals change.

**Comment by bloatmode** [comment]
@EmilJunker I built the app using the code from the master branch and I can't create new foods, when I click the ✔ on the top right after inserting all the data nothing happens. I'm not sure if this is an issue on my end, if it was introduced in your PR or in one of the previous commits after release 3.4.2. It doesn't happen in version 3.4.2 even when I build it.

**Comment by giovannivelludo** [comment]
@EmilJunker I built the app using the code from the master branch and I can't create new foods, when I click the ✔ on the top right after inserting all the data nothing happens. I'm not sure if this is an issue on my end, if it was introduced in your PR or in one of the previous commits after release 3.4.2. It doesn't happen in version 3.4.2 even when I build it.

**Comment by EmilJunker** [comment]
@giovannivelludo Yeah, I can confirm that it's not possible to create foods in the latest build. This issue must have been introduced by one of my previous commits. I'm glad that you noticed. I'll try to get this fixed quickly, shouldn't be too hard...

**Comment by giovannivelludo** [comment]
It came to my mind that if a user has set some goals as a % of energy intake and others as a fixed number, then it's wrong to compute the value in grams of the % goals as:
(total kcals + exercise kcals) * % goal

Instead it should be:
(total kcals + exercise kcals - kcals from fixed goals) * % goal

It's not important for me and I don't care if it gets fixed, but I though I'd share anyway.

**Comment by EmilJunker** [comment]
I think this depends on how exactly you set your goals. For example, if you have a fixed goal for protein, and want the remaining energy to be split evenly between carbs and fat, would you set your goals for carbs and fat to 50% each? Wouldn't this mean that your total energy intake is above your energy goal if you reach all three macro nutrient goals? I think you probably would rather set the goals to something like 40% each, and in this case the current calculation method would be alright.

**Comment by giovannivelludo** [comment]
Let's say I have a 50% goal for carbs and 50% for fats, a fixed goal of 70 grams of protein and a goal of 2500 kcals. With no exercise, using my second formula we get the following carbs goal in kcals:
(2500 + 0 - (70 * 4)) * 0.5 = 1110 kcal, which corresponds to 277.5 grams of carbs
The fats goal in kcals is the same, corresponding to 123.333... grams of fat.
If we sum calories from each macronutrient we get:
123.333... * 9 + 277.5 * 4 + 70 * 4 = 2500 kcal

If exercise is added, each % goal is still computed correctly because exercise calories are simply added to the total before doing any other computation.

**Comment by EmilJunker** [comment]
I understand what you're saying, but my point was that most users would interpret "goal as percentage of energy intake" to mean that if you set your carbs goal to 50%, then 50% of your energy will come from carbs. There is no mention of first subtracting absolute goals or something like that. So if you set your carbs goal to 50%, then you shouldn't be surprised that the used reference value is for the calculation is 50% of your total energy (plus energy burned in exercises). In fact, this is exactly what I would expect as a user.
