### ISSUE TITLE
Modify Meals Feature to make it usable for large quantities of food

### ISSUE THREAD

**Issue by longestmt** [davidhealey/waistline#599]
This suggestion is coming straight form the way meals work on MFP...

**Current State**
Currently when creating a meal the user can add the ingredients to the meal and save it which is nice because you can see the total calories etc

When the user adds the meal to their diary it adds everything that went into the meal. This is not desirable. If I calculate all the calories that go into a stir fry for my family and I eat only 400g of that stir fry I only want to add the nutritional data for 400g of the meal.

**Future State**

_Adding meals to the diary as a singular entry_
GIVEN the user has created a meal with multiple inputs (e.g. Chicken and broccoli stir fry)
WHEN the user adds the meal to their diary
THEN the amount of that meal should be specified by the user (e.g. 400g )
AND the entry should be added with the label of the meal (e.g. 'Chicken and Broccoli Stir fry -- Meal -- 400g')

_Ensuring added meals have the appropriate calories_
GIVEN the user has added a meal entry to their diary
WHEN the amount of the meal has been specified (e.g. 400g)
THEN the nutritional details for the meal should be derived from the meal total 

For example, if I make a stir fry that is 1000g and 4000 calories and then I add 400g of that stir fry to my diary. Then it should be listed with only 1600 calories and appropriately adjusted nutritional info as well.

Calculation - (Meal diary entry amount/Total meal amount) * Total Meal metric (calories, protein etc.) 

(400g/1000g)4,000 calories = 1600 calories

This would be SOO useful for people that cook big portions and struggle to calculate the nutritional info for smaller portions of the whole.

Reach out with any questions.

**Comment by davidhealey** [comment]
This is what recipes are for.

**Comment by longestmt** [comment]
I literally just realized this and came back to make a comment. Major Homer Simpson "d'oh!" moment.
