### ISSUE TITLE
Inconsistent tagging: "vX.Y.Z" vs. "X.Y.Z"

### ISSUE THREAD

**Issue by relan** [davidhealey/waistline#60]
Hi,

F-Droid maintainer here. The use of the "v" prefix in Git tags has been inconsistent recently:

* 2.3.1
* 2.3.0
* v2.2.3
* 2.2.2
* v2.2.2
* v2.2.1
* 2.2.0

Could you please stick to some tagging scheme (with or without "v")? This will allow F-Droid to update Waistline automatically and always have the latest version.

**Comment by davidhealey** [comment]
No problem :)

**Comment by relan** [comment]
Thanks! Glad we can automate updates. :)
