### ISSUE TITLE
App change values automatically and unwanted.

### ISSUE THREAD

**Issue by hacksenwerk** [davidhealey/waistline#602]
First I love this app, thank you for it! 

Today I added table grapes manually and typed in the vitamins and minerals, but some of the values I already filed in are changing automatically, when I change other values. 

For example I change iron to 0,415 mg it changes phosphor and others. 
So I changed iron to 0 and saved the entry, opened it again and changed iron to 0,415, this time none of the other values changed.

**Comment by davidhealey** [comment]
The link button in the top bar of the food editor is what you are looking for I think.

**Comment by hacksenwerk** [comment]
@davidhealey  A bit late, but thank you very much. ;)
