### ISSUE TITLE
[Feature request] When adding food to meals make it possible to sort the foods by most recently used?

### ISSUE THREAD

**Issue by krysor** [davidhealey/waistline#608]
Currently it's more or less alphabetical. If someone eats some foods often it would make it easier to add them without having to scan or manually search them each time. I wonder what's your take on this.

**Comment by EmilJunker** [comment]
`Settings > Foods, Meals, Recipes > Sort Foods` is what you're looking for :)

**Comment by krysor** [comment]
Amazing. Thank you!
