### ISSUE TITLE
Add weighing section to track progress

### ISSUE THREAD

**Issue by gingerling** [davidhealey/waistline#61]
Hi, app looks great, really clear and tidy. It would be useful to have a place to add current weight to track progress over time with weight lost etc. Thanks!

**Comment by davidhealey** [comment]
Already can do, click the scales button at the top right of the diary screen.

**Comment by gingerling** [comment]
Hi, O.K, can you add a sentence about it to the app user guide section?
Thanks 😊

**Comment by davidhealey** [comment]
That is there already too, in the diary section

> You can record your weight by tapping on the scales icon on the top toolbar.

**Comment by gingerling** [comment]
ok cool, I didn't see it - but awesome app. :)
