### ISSUE TITLE
[Feature Request] Less complicated exports

### ISSUE THREAD

**Issue by Nanen** [davidhealey/waistline#610]
I am trying to export the daily calories and maybe macros to merge and plot with my other data, but find the exported json really complicated for that usecase.

If I understand correctly, I would have to get the diary and the foodList table, replace the foods in the diary with the food in the foodList by id and then multiply the portion and quantity of the diary with the calorie or macro values of the foodList. I assume there's already some code to calculate calories and macros of the day, so a simpler export with date, calories and macros would be really useful.

Thank you for creating such an awesome app!

**Comment by EmilJunker** [comment]
Are you looking for something like this: #494?
I think a csv file that lists the total calories and macros for each day should do it.

**Comment by Nanen** [comment]
Yeah, pretty much. I thought the other issue requested a more complete csv version of the diary, but the way you describe it is exactly what I'm looking for.

Thank you for the quick reply!

**Comment by davidhealey** [comment]
I'll close this issue and we'll track it in the other one.
