### ISSUE TITLE
Add a BMI option in statistics' dropdown list

### ISSUE THREAD

**Issue by morgandavidson** [davidhealey/waistline#614]
[BMI](https://en.wikipedia.org/wiki/Body_mass_index) = $\frac{kg}{m^2} = \frac{lb}{m^2}\times 703$

Where 

- $kg$ is the mass of the user in kilograms
- $m$ is the height of the user in meters
- $lb$ is the mass of the user in pounds

**Comment by davidhealey** [comment]
> Yes. Actually there is a TDEE calculator inside Waistline, but it's currently hidden because I haven't finished implementing it. When I have some free time to do more development work on Waistline it's at the top of my list.

https://github.com/davidhealey/waistline/issues/601
https://github.com/davidhealey/waistline/issues/56
https://github.com/davidhealey/waistline/issues/216
