### ISSUE TITLE
"Follow system theme" feature

### ISSUE THREAD

**Issue by parthvyas7** [davidhealey/waistline#619]
Currently, To change the appearance of the app to dark mode, we have to do it manually, while most apps on the latest do it automatically by following the system theme. It would come as a handy feature.

**Comment by EmilJunker** [comment]
This is already possible. The option to use the system theme was added in version 3.4.4 (or actually in 3.4.3, but I think there were some problems with that release). However, it's possible that you don't see this update yet if you installed Waistline from the Play store.

**Comment by parthvyas7** [comment]
Yeah, I am using version 3.4.2 which is latest available in the playstore

**Comment by parthvyas7** [comment]
When will the latest version of the app will be rolled out on the play store?

**Comment by EmilJunker** [comment]
Version 3.4.4 is now available in the play store, so this issue can be closed.
