### ISSUE TITLE
Only active goals shown

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#626]
I would like only active goals to be shown.

![Screenshot_2022-09-15-17-39-47-52_e8d03466a4604b1244d2695731a8e6b1 (1)](https://user-images.githubusercontent.com/113377431/190448140-9170d4c0-11a6-4b48-b599-43044e68fc4f.jpg)

**Comment by EmilJunker** [comment]
The page in the screenshot is there to allow the user to set goals. Only showing goals that are already set would therefore defeat its purpose. Or what do you mean exactly?

**Comment by EmilJunker** [comment]
I see, that actually sounds like a good idea. Maybe we can split this page into two tabs, one just for "Your Goals" and one for "All Fields".
