### ISSUE TITLE
More compact and space efficient dashboard design

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#628]
In this screenshots it shown MyNetDiary day dashboard and Waistline comparison.

I'd like more info in dashboard, with more compact and space efficient design.

![Screenshot_2022-09-16-07-11-10-53_4dcbe2772a7f697dba9440cb42dee74c (1)](https://user-images.githubusercontent.com/113377431/190562187-4c5e8f66-881b-43a5-9764-adfb38428850.jpg)

![Screenshot_2022-09-16-07-11-45-16_4dcbe2772a7f697dba9440cb42dee74c (1)](https://user-images.githubusercontent.com/113377431/190562194-3ba13372-0adb-4a95-bd03-505f4f692928.jpg)

![Screenshot_2022-09-16-07-17-03-28_e8d03466a4604b1244d2695731a8e6b1 (1)](https://user-images.githubusercontent.com/113377431/190562197-119d596f-e56c-4498-90ba-897b21b5b16c.jpg)

**Comment by davidhealey** [comment]
Waistline doesn't have a dashboard. You're looking at the diary page there. If you click the pie icon in the top right corner you will get something more like a dashboard.
