### ISSUE TITLE
Adding calories to daily budget by sport activities

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#629]
When I do calisthenics or any other physical activity I would like the ability to add calories to the daily budget (for that day only).

**Comment by EmilJunker** [comment]
This is already possible. Press and hold the `+` button in the diary and enter a negative value for the calories.

**Comment by EmilJunker** [comment]
We already do that. This was changed in version 3.4.4.
@davidhealey Have you released version 3.4.4 to the Playstore yet?

**Comment by davidhealey** [comment]
> Have you released version 3.4.4 to the Playstore yet?

Now I have :)
