### ISSUE TITLE
Request: Increase day calorie limit due to sports

### ISSUE THREAD

**Issue by coopy25** [davidhealey/waistline#639]
Hi,

I would like to increase the calorie ceiling for an single day if I did sports. Alternatively I would like to add an item with negative calories.

**Comment by davidhealey** [comment]
Hold the plus button to add negative calories.

**Comment by EmilJunker** [comment]
> Alternatively I would like to add an item with negative calories.

What prevents you from doing that?

**Comment by coopy25** [comment]
Thanks guys. Both works the Problem is, that my Samsung Android phone does not show a minus sign on the numerical keypad. But I created an item with negative calories (and positive "portion size") now that I can easily use in the future.

**Comment by coopy25** [comment]
The Android Samsung keypad which does not have minus key. But I managed 
to create an item using copy and paste.
