### ISSUE TITLE
Keep the last choice set

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#640]
Each time I find myself having to set again the selection of what I want to display in the pie chart.

I therefore request that the app remember the last selection made.

![Screenshot_2022-10-03-16-56-29-40_e8d03466a4604b1244d2695731a8e6b1 (1)](https://user-images.githubusercontent.com/113377431/193610023-76aaf2ef-5cb6-438d-aa86-2f4f8bc8cd8e.jpg)

**Comment by EmilJunker** [comment]
The entries for fat and carbs in the pie chart don't include sat fat and sugar! Before rendering the chart, Waistline subtracts the amount of sat fat from the fat value and the amount of sugar from the carbs value. The slices for fat and sat fat combined show you the total proportion of fat, and the slices for carbs and sugar show you the total proportion of sugar. That's also the reason why the slices forming a pair each have similar colors. 

To be honest, I'm surprised to hear that it's still even possible to hide individual nutriments from the chart. I was under the impression that this capability was disabled long ago 🤔.
