### ISSUE TITLE
what do integrations do?

### ISSUE THREAD

**Issue by idkman2021** [davidhealey/waistline#648]
what do Open Food Facts and UDSA integrations do? I enabled them and I thought it would add premade food into my food list but it seemed to not do anything observable

**Comment by idkman2021** [comment]
okay I didn't realize I had to hit the search button on the virtual keyboard, but still, what did those integrations do? Did they add more food into foods list?

**Comment by EmilJunker** [comment]
Without these integrations you wouldn't see anything when you hit the search button on the keyboard.
