### ISSUE TITLE
Doesn't switch dark/light mode

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#655]
App follows only system default value, not dark or light modes.

Android 12, Waistline 3.5.1

**Comment by EmilJunker** [comment]
Yes, the new version of Framework7 changed some property and class names regarding the dark theme. Did you undo all of them when downgrading?

**Comment by davidhealey** [comment]
@EmilJunker I did not, that would explain this is issue. I just replaced the couple of things that were preventing it running on my phone.

**Comment by EmilJunker** [comment]
@davidhealey It looks like you already took care of most of it. You just need to change `dark` back to `theme-dark` [here](https://github.com/davidhealey/waistline/blob/85a112cedb49c3d010f3c2080203e195c64d568d/www/activities/settings/js/settings.js#L269) and [here](https://github.com/davidhealey/waistline/blob/85a112cedb49c3d010f3c2080203e195c64d568d/www/activities/settings/js/settings.js#L273). That should do it.

**Comment by davidhealey** [comment]
Thanks, I'll get around to this in the next day or two.

**Comment by davidhealey** [comment]
I just pushed a new build. I can't test it because my Android 7 device doesn't have the dark mode setting.

https://github.com/davidhealey/waistline/releases/tag/3.5.2

**Comment by EmilJunker** [comment]
I'll fix this on the weekend along with #656 and a few other small issues.
