### ISSUE TITLE
Waistline 2.3.4: minSdkVersion 16 cannot be smaller than version 19 declared in library [:CordovaLib]

### ISSUE THREAD

**Issue by relan** [davidhealey/waistline#66]
I'm trying to build Waistline 2.3.4 on a Debian 8.11 system with Gradle 4.1. It fails with

```
Execution failed for task ':app:processReleaseManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:CordovaLib] /home/fdroid/fdroiddata/build/com.waist.line/platforms/android/CordovaLib/build/intermediates/manifests/full/release/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)
```

Steps to reproduce:

```
git checkout 2.3.4
cd platforms/android/app
gradle assembleRelease
```

Any clues?

P.S. Waistline 2.3.3 builds just fine on the same system.

**Comment by davidhealey** [comment]
The SDK version required was changed for 2.3.4 (I'm not sure why, I think it was a requirement of one of the plugins that I updated).

**Comment by davidhealey** [comment]
Are you able to build 2.3.3?

**Comment by relan** [comment]
Yes, 2.3.3 builds just fine on the same system.

**Comment by davidhealey** [comment]
Hi,

I'm just looking into this issue now. If you open AndroidManifest.xml file in /platforms/android/app/src/main/ and change this line <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="27" /> to this <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="27" /> Are you able to build?

**Comment by davidhealey** [comment]
Actually I've just made this change and pushed it to the repo, see if you can build the master branch now, if you can I'll push a new release

**Comment by relan** [comment]
Hi,

I'm on vacation now, away from my PC. Will be able to test only in two weeks.

**Comment by davidhealey** [comment]
No problem

**Comment by relan** [comment]
2.3.5 and 2.3.7 were built successfully, so this issue is solved. Thanks!
