### ISSUE TITLE
Weight tracking

### ISSUE THREAD

**Issue by jubalh** [davidhealey/waistline#67]
Under 'Statistics' I can track the Calories consumed.
It would be nice to also track the weight, seeing when I come closer to goals.

**Comment by davidhealey** [comment]
https://github.com/davidhealey/waistline/issues/61

**Comment by jubalh** [comment]
Hehe sorry I didn't see that :-)

How about being able to track lean muscle mass/fat percentage of the weight?

**Comment by jubalh** [comment]
And since I have you here already: where to set my caloric maintenance level?

**Comment by davidhealey** [comment]
You can set your maintenance level on the goals screen. I have no plans to add support for tracking muscle mass or body fat. See https://github.com/davidhealey/waistline/issues/49#issuecomment-416868839

**Comment by jubalh** [comment]
> You can set your maintenance level on the goals screen. 

Right, I set that to 2000 (like the default). 
An online TDEE calculater calculated  2,051 calories per day for me.

When I go to `Statistics` it shows:

> Goal 2000 ; Used 4824065 ; Remaining -48240065

I'm not sure I understand what the last two should indicate. Since the goal is 2000 calories per day to maintain

**Comment by davidhealey** [comment]
That looks weird, can you show me a screenshot please?

**Comment by jubalh** [comment]
![wscreenshot](https://user-images.githubusercontent.com/1658215/45960215-0167d780-c01c-11e8-9481-ea1273de767c.jpg)

**Comment by davidhealey** [comment]
Well that's very strange. Have you added any food to the diary?

**Comment by jubalh** [comment]
yep. today for the first time.

**Comment by jubalh** [comment]
I think I found an openfoodfacts that was wrong. Sorry for that issue.
