### ISSUE TITLE
[Feature Request] A way to add calories burned to that day's calorie goal

### ISSUE THREAD

**Issue by disobeyedtoast** [davidhealey/waistline#674]
I just want to say first off I really appreciate the work you put into your app, and that I truly do appreciate that you haven't abandoned this project. It's very hard to find a good privacy and freedom respecting weight tracking app. One feature that I do feel is missing however is the ability to change your daily goal of calories according to the amount of calories you have burned through exercise. As far as I know, there is currently no way to change your daily goal of calories specifically only for that day (Say Monday 23/1/23 as opposed to the day after or the Monday after that.)  

As far as I understand, i would have to change the daily goal for every day in order to do this currently, which is a major hassle and inelegant. Although a full workout selection and calorie calculator would be wonderful, I realize that is an absolutely massive amount of work. So what I thought may be a good solution is just a simple button on your diary that allows you to input the calories you have burned in that day and add that onto that day's calorie total.

**Comment by davidhealey** [comment]
> So what I thought may be a good solution is just a simple button on your diary that allows you to input the calories you have burned in that day and add that onto that day's calorie total.

You can already do this. Tap and hold the + button for one of the categories in the diary and enter a negative value.

**Comment by disobeyedtoast** [comment]
I apologize, i somehow missed this.
