### ISSUE TITLE
Duplicate entries in Recipe list

### ISSUE THREAD

**Issue by burke3gd** [davidhealey/waistline#676]
The entries towards the end of the Recipe list are shown duplicated. After adding a new recipe all  recipes are shown multiple times. When searching for a duplicated recipe it is shown only once in the results.

Here is a screenshot:

![Screenshot_20230201-175909](https://user-images.githubusercontent.com/5621615/216096967-c9f13226-949e-46c8-b523-35cf561d2d2f.png)

Thanks for all the hard work!

**Comment by burke3gd** [comment]
This is with app version 3.5.2 on Android 12.

**Comment by jncosideout** [comment]
this seems to be happening to Meals too.
1. I opened the 'Foods, Meals, and Recipes' activity and navigated to the Meals list tab 
2. Edit the last meal (LoC2 in this video)
3. List of meals is shown with every item after the 2nd row now triplicated
4. Switching away from the Meals list and back removes the phantom duplicates

#### Notice how the first item in the list (LoC1) becomes the 2nd row after editing the last item (LoC2), yet it is not triplicated, but all items following it are:
https://user-images.githubusercontent.com/25991237/227722238-45e5f960-1b75-44ed-9dac-50399f783686.mp4

**Comment by jncosideout** [comment]
@davidhealey @EmilJunker wondering if you saw my comment above, I have pretty good repro steps and a video which I believe exemplify the underlying cause of this bug (i.e. it affects Recipes as @burke3gd pointed out as well as Meals)

**Comment by davidhealey** [comment]
@jncosideout Yep, saw it thanks.

**Comment by EmilJunker** [comment]
I've been super busy in the past few weeks, so I haven't been able to look into any of the issues opened recently. But I will get back to it as soon as I have some time to spare :)

**Comment by burke3gd** [comment]
jncosideout wrote:
> this seems to be happening to Meals too.

I didn't notice this as I only have couple of meals in my database. This bug seems to trigger after a certain number of entries has been reached. (20 in my case, which is a suspiciously even number...)
