### ISSUE TITLE
Main menu wrong color in dark mode

### ISSUE THREAD

**Issue by burke3gd** [davidhealey/waistline#677]
The main menu is partially white in dark mode. I've tried different settings but to no avail. The app is version 3.5.2 on Android 12.

Here is a screenshot to illustrate this:

![Screenshot_20230201-180719](https://user-images.githubusercontent.com/5621615/216099310-8abc6fec-4b27-4caf-9b4f-888c10f50065.png)

**Comment by davidhealey** [comment]
I think this will be resolved by this PR https://github.com/davidhealey/waistline/pull/672

**Comment by EmilJunker** [comment]
This should already be fixed by PR #663

**Comment by davidhealey** [comment]
Ah ok, so it will be in the next release, probably this weekend.

**Comment by burke3gd** [comment]
This appears to have been fixed in v3.6.0. Thank you!
