### ISSUE TITLE
Quick add usability issue

### ISSUE THREAD

**Issue by grrrrr** [davidhealey/waistline#68]
Could the quick add feature be tweaked in some way?

Currently if you hold one of the meal time heading and a dialog with 100 pops up.  I rarely want to just add 100 calories, it's likely more or to do negative numbers.   The problem is the cursor for that dialog box is placed before the `100`.   This means that I cant just quickly type in the number I want,  I have to move the cursor to after the `100` and then delete.

Maybe this dialog could be modified to either have no default number or have the cursor after the default 100

**Comment by davidhealey** [comment]
Good suggestion, I'll remove the default value.

**Comment by davidhealey** [comment]
This is done now for the next update
