### ISSUE TITLE
Custome order targets

### ISSUE THREAD

**Issue by ghtesting2020** [davidhealey/waistline#680]
Please can you consider adding option for us to be able to reorder the targets for our nutrients, calories etc? This is the section at the bottom of the Diary screen.

First screen
Calories Carbs Fiber

Swipe to second screen
Proteins Sodium Vitamin B12

etc

For someone like me watching my sodium and Potassoum intake is very important but carbs not much. It is hassle to always have to swipe to see most important targets for me.

Thank you regardless. Waistline is helping me stay healthy.

**Comment by EmilJunker** [comment]
@ghtesting2020 You can reorder the nutrients under `Settings > Nutrients`. Press and hold, then drag to rearrange.

This order is applied everywhere: in the diary, in the food editor, on the statistics page, in the goals list. There is currently no way to change only the order in the diary.
