### ISSUE TITLE
Dark mode not working properly

### ISSUE THREAD

**Issue by ghtesting2020** [davidhealey/waistline#681]
I'm having issue with dark mode in version 3.5.2

Appearance app mode:
Use system theme (dark)
App is mostly dark but the upper and lower part of expanded hamburger menu is white
I would say partially works.

Light
Everything is white as expect
Fully works.

Dark
Everything but the upper and lower part of expanded hamburher menu is light.
As in not dark at all/barely works.

I've also not been able to pin down but sometimes when using follow system theme even when worker and owner profile are dark mode sometimes when switching from worker where I use app to owner and back to worker makes the entire app light mode even though it says follow system theme which my profiles are set to dark. A phone restart fixes it.

**Comment by davidhealey** [comment]
Duplicate: https://github.com/davidhealey/waistline/issues/655
Fixed here: https://github.com/davidhealey/waistline/pull/672
