### ISSUE TITLE
All entries under Nutriments in the settings should be editable. 

### ISSUE THREAD

**Issue by hacksenwerk** [davidhealey/waistline#688]
Settings -> Nutriments
At the moment it is only possible to activate or deactivate them and to move them up and down.

**Comment by davidhealey** [comment]
Why should they be editable?

**Comment by hacksenwerk** [comment]
Because I use the chemical names for vitamins and sort them alphabetically (the ones in brackets, but also some missing Vitamin C misses Tocopherol for example).  

Also in the german version of the app, Calcium is called Kalzium, that is correct too, but no one writes it like that.

**Comment by davidhealey** [comment]
> Because I use the chemical names 

Waistline uses the same naming system as Open Food Facts and this isn't something that will be user editable. What you might be able to do is add a custom translation file, not sure though.

> Also in the german version of the app, Calcium is called Kalzium, that is correct too, but no one writes it like that.

The translations are handled by volunteers on Crowdin.

**Comment by hacksenwerk** [comment]
What do you mean? The entries in the Nutrition section are coming with the app, so they must be editable in the code, right? 
Of course I could deactivate the entry "Vitamin C", create a new one and name it "Tocopherol (Vitamin C)", but then I would have to go through all the foods an fill in the values for Tocopherol again... That would be a mess.

**Comment by davidhealey** [comment]
> What do you mean? The entries in the Nutrition section are coming with the app, so they must be editable in the code, right?

Within the code the entries are using the standard OFF names. You can see them here - https://github.com/davidhealey/waistline/blob/master/www/index.js#L35

On the front end the names are translated through the internationalisation system. This uses language files created by Crowdin contributors. There is no method within the code to edit these translation files they are simply used as text replacement based on the user's language settings.

**Comment by hacksenwerk** [comment]
This: [Crowdin](https://en.wikipedia.org/wiki/Crowdin)? 

So no chance for me to change that?

**Comment by davidhealey** [comment]
> This: [Crowdin](https://en.wikipedia.org/wiki/Crowdin)?

Yep

> So no chance for me to change that?

You could replace the German language file with a custom one and recompile Waistline. https://github.com/davidhealey/waistline/blob/master/www/assets/locales/locale-de.json

**Comment by hacksenwerk** [comment]
Ok I never heard of Crowdin. 

I can compile that. 
Can I just fork that file and do a pull request?

**Comment by davidhealey** [comment]
No because that will change it for everyone else.

**Comment by hacksenwerk** [comment]
But the change is correct. 
Along with some other changes, like Coffein instead of Koffein and others...

**Comment by hacksenwerk** [comment]
Also some entries are missing, like Molybdenum and Silicon for example.

**Comment by davidhealey** [comment]
> But the change is correct.

Sorry I thought you meant about changing the names to chemical names.

As far as I'm aware the translations must be done through Crowdin rather than a pull request. This is because any change you make to the files is overwritten by the next change made on Crowdin.

**Comment by hacksenwerk** [comment]
Ok. 

Do you have a link to the specific crowdin page?

**Comment by hacksenwerk** [comment]
And a bit off-topic, but: when I export the database, will it also export my settings, like custom Nutriments, their sort order and all?

**Comment by davidhealey** [comment]
> will it also export my settings, like custom Nutriments, their sort order and all?

I'm not 100% sure, I think most settings get exported.

Here's the Crowdin page - https://crowdin.com/project/waistline (it's listed in the Waistline readme btw).

**Comment by hacksenwerk** [comment]
Ok crowdin is full of cloudfront and stuff, I wont use that. But thanks anyway. 

> I'm not 100% sure, I think most settings get exported.
=) and what means "most"?

**Comment by hacksenwerk** [comment]
> It means I don't know the answer :)

=D ok and who knows the answer?

**Comment by davidhealey** [comment]
Possibly one of the other developers... you could try it and see, then you'll know the answer

**Comment by hacksenwerk** [comment]
Sure but that contains the risk loosing some of my data....

**Comment by davidhealey** [comment]
The backup/export system is robust, you shouldn't lose any data. Just make sure you back up before.

**Comment by hacksenwerk** [comment]
But I mean I need to reset the data in the app to default to check if the following import will bring back all the data...

**Comment by davidhealey** [comment]
Oh I thought you were just interested in the a few settings. Yeah I wouldn't try resetting everything

**Comment by hacksenwerk** [comment]
=(

**Comment by hacksenwerk** [comment]
I guess I make a new issue for that? 
As a feature request?
