### ISSUE TITLE
Add liberapay as a donation option, so people who do not (want to) use Patreon can support you too. 

### ISSUE THREAD

**Issue by hacksenwerk** [davidhealey/waistline#689]
Would be cool!
https://en.liberapay.com/

**Comment by davidhealey** [comment]
There isn't a Waistline Patreon page... 

Back when I first started Waistline and it was just my I thought donations were a nice idea, but since the number of developers contributing has grown and since I'm not actively working on Waistline myself I don't want to encourage donations that go to me.

**Comment by hacksenwerk** [comment]
I ment the patreon link on your github userpage: https://www.patreon.com/davidhealey

It is a very good app so I would like to contribute, but ok so no candy.  =)

**Comment by davidhealey** [comment]
Oh that's my patreon page for my YouTube channel, unrelated to Waistline. 

> It is a very good app so I would like to contribute

You already are ;)
