### ISSUE TITLE
F-droid updates

### ISSUE THREAD

**Issue by grrrrr** [davidhealey/waistline#69]
I am not sure if this is something you have control or influence over David but 2.3.4 is not available on F-Doid still.

https://f-droid.org/wiki/page/com.waist.line#2.3.4

https://f-droid.org/wiki/page/com.waist.line/lastbuild_20304

**Comment by davidhealey** [comment]
I have no control over it. F-Droid builds the releases from source automatically, I'm not sure what the interval is between builds but it seems to be a bit random.

**Comment by relan** [comment]
2.3.4 is not on F-Droid because of #66.

**Comment by davidhealey** [comment]
Oh, any idea how to resolve it?

**Comment by relan** [comment]
Nope. I never had any experience with Cordova.

**Comment by davidhealey** [comment]
hmmm I'll see what I can do

**Comment by relan** [comment]
F-Droid's build recipe was relying on Gradle. Now that build.gradle is gone, it doesn't know how to find and build updates.

**Comment by davidhealey** [comment]
I see, so I need to push the platforms directory, no problemo. Thank you

**Comment by relan** [comment]
It was a very bad idea to push all *.bin, *.lock, *.class and other binary files.

**Comment by davidhealey** [comment]
Tell me more

**Comment by relan** [comment]
Could you amend the last commit and push it with `-f`?

**Comment by relan** [comment]
Whatever is needed to make `gradle assemblyRelease` succeed. I guess it will be OK to remove all `.gradle` and `build` directories.

**Comment by davidhealey** [comment]
Ok thanks. I don't know anything about Android development, I let Cordova handle it, so I appreciate your input very much.

**Comment by davidhealey** [comment]
Ok I think I've done that successfully, seems like those files are no longer in the git repo.

**Comment by relan** [comment]
Thanks! There are still some leftovers (as of 142a974):

```
$ find . -type d -name build
./platforms/android/CordovaLib/build
```

This is _not_ a showstopper for an F-Droid release though. Added 2.4.2 in https://gitlab.com/fdroid/fdroiddata/commit/717d40457fc3f4e062142fe1a66f623c62c13082.

**Comment by davidhealey** [comment]
Thank you, I'll remove those files before the next update
