### ISSUE TITLE
Databackup should backup all the data

### ISSUE THREAD

**Issue by hacksenwerk** [davidhealey/waistline#690]
https://github.com/davidhealey/waistline/issues/688#issuecomment-1431316997

"Backup" means "backup", not "partially backup". 
If it is partially, the app have to communicate that in the settings. 

Foods, all settings, statistics, goals, body stats, should definitely be backuped.

**Comment by davidhealey** [comment]
You can test this. Run the backup, this will produce a .json file. Open it in a text editor (or json viewer) and see if anything is missing.

**Comment by EmilJunker** [comment]
The backup already includes everything: foods, meals, recipes, diary entries, body stats, statistics, settings and goals.
Just look at the content of the json file and you'll see it :)
