### ISSUE TITLE
Featutre request -  Possibilty to set maximum values for goals

### ISSUE THREAD

**Issue by hacksenwerk** [davidhealey/waistline#695]
This would be very helpful for nutriments like monosaccharide,  saturated fatty acids, but also for intolerances like fructose, lactose and so on.

**Comment by hacksenwerk** [comment]
Ok, for example saturated fatty acids:
The recommendation is to have a maximum of 7% to 10% from the sum of daily energy. 
So if you can set the maximum to 7% the app will calculate how many gram of saturated fatty acid is 7% of the daily energy consumption. 
When you under that 7%, the number in the goals at the bottom of the diary is green, when you get over this 7% it will turn to red. 
So the reverse way.

**Comment by davidhealey** [comment]
You can already do this, enable the is minimum goal option for that goal

**Comment by hacksenwerk** [comment]
Huh? 
No. 
I use this as a workarround. 
But the number wont turn red if you are above the minimum.

**Comment by hacksenwerk** [comment]
The best is to not consume any saturated fatty acids, but you shouldn't consume more then 7% - 10% of it compared to the energy turnover.

**Comment by davidhealey** [comment]
Actually I just checked. You don't need to enable the minimum goal setting. What you want is the default behavior. Under the goal is green, above is red.

**Comment by hacksenwerk** [comment]
I tested this and it is like that for saturated fatty acids. 
But not for sugar for example.

**Comment by davidhealey** [comment]
Works here. The code is the same for all nutriments so there should be no difference.

![Screenshot_20230218-133900](https://user-images.githubusercontent.com/14021202/219868896-51b84596-1ddc-4dca-8ff1-12959f6e5b85.png)

**Comment by hacksenwerk** [comment]
Ah my mistake I left the value empty accidentally. 
=)

**Comment by hacksenwerk** [comment]
Oh no I didn't! 

Try this: type in the value but only then activate the percentage button, the app will clear the value field.
Found a bug! Can I keep it?

**Comment by hacksenwerk** [comment]
Deactivating it clears the value too.

**Comment by davidhealey** [comment]
As far as I'm aware (I didn't implement the percentage feature) that is intentional
