### ISSUE TITLE
make use of iocipher

### ISSUE THREAD

**Issue by grrrrr** [davidhealey/waistline#70]
This is a big ask but it would be great to implement iocipher library into Waistline.   While not a direct / noticeable change to users it would be good to have added security and privacy included in android apps

More details on the library here:

https://guardianproject.info/2018/08/17/iocipher-is-the-antidote-to-man-in-the-disk-attack/
https://guardianproject.info/code/iocipher/
https://github.com/guardianproject/IOCipher

**Comment by davidhealey** [comment]
Waistline doesn't use the shared external storage space on your phone so I don't see a security issue here that needs fixing.
