### ISSUE TITLE
Diary export possible, diary import not possible

### ISSUE THREAD

**Issue by hacksenwerk** [davidhealey/waistline#705]
Why does the app then have an export function in the first place?

**Comment by davidhealey** [comment]
Why do you say it's not possible?

**Comment by davidhealey** [comment]
Oh I see the issue. I think it's a labeling problem.

@EmilJunker Perhaps you know more about this?

I use the Backup Database and Import From Database options. I guess the Export Diary is just for the Diary without the rest of the database, what happens if you try to import this as a backup?

**Comment by hacksenwerk** [comment]
The diary file contains only nutrients, dates and ids separated by `, `and `;`. 

When I use `IMPORT FROM BACKUP` and select diary_export.csv I get `Import Failed`.

**Comment by hacksenwerk** [comment]
I edited both and both imports fail.

**Comment by hacksenwerk** [comment]
But it could be, that the diary contains one or too IDs from the foods I removed from the database file... 
It is a mess to do it...
Not good.

**Comment by davidhealey** [comment]
> But it could be, that the diary contains one or too IDs from the foods I removed from the database file...

If you've added these food to the diary then that will definitely be the case. This is why I said if the IDs are referenced anywhere else you would need to remove them.

**Comment by hacksenwerk** [comment]
Yes and it is still a mess, the app should just have a delete button for foods and after that remove the no longer needed ids from the diary automatically, and if that is somehow problematic, just replace them with a placeholder.

**Comment by EmilJunker** [comment]
The diary export file is not meant to be imported. It only serves as a way to get an overview of your diary content readable for both humans and machines. This was a much requested feature, see here #494.
So I think this issue can be closed.

**Comment by hacksenwerk** [comment]
> The diary export file is not meant to be imported. It only serves as a way to get an overview of your diary content readable for both humans and machines. This was a much requested feature, see here #494. So I think this issue can be closed.

That doesn't make any sense, it is not useful for anyone, because it is just full of IDs and not the food listed by day. 

Also this robs users the opportunity to delete old content efficiently. 
I just want to delete some of the content in the diary and not all and start a complete new diary...

**Comment by EmilJunker** [comment]
> it is not useful for anyone, because it is just full of IDs and not the food listed by day

You are confusing the diary export with the database backup. The diary export is a comma separated csv file. The database export is a json file. Only the json file can be imported, provided that it's syntactically correct.
