### ISSUE TITLE
waistline clears all adata except goals and nutriments without any action on the part of the user

### ISSUE THREAD

**Issue by hacksenwerk** [davidhealey/waistline#708]
This noon I noticed that waistline has deleted the whole diary and with it all statistics and also all foods, meals and recipes. 
My automatic database backup is all day at 10 am, and this backup has a size of only 10 KB, while the backup from Sunday is about 69 KB. 
So it deleted itself over night, because on Sunday I made my last entry in the diary at 11 pm. 
Nothing was done with my phone after doing that entry, except turn it into flightmode like every night. 
Worse but it gets weird, because my custom made nutriments and goals were still there... o_0

With the backup from Sunday I restored the database but not the diary, wich is a pain in the ass! 
And so the circle closes, cause I already mentioned in issue [705](https://github.com/davidhealey/waistline/issues/705), that a function for importing the diary backup is missing.

**Comment by davidhealey** [comment]
The automatic backup contains everything, including the diary. Sounds like something fishy has happened on your phone. What make/model is it? What OS?

**Comment by hacksenwerk** [comment]
Ok the diary was imported too, but the Sunday was missing so I was confused at first.

**Comment by hacksenwerk** [comment]
Ok it seems, that the second half of the Saturday diary entry was also missing.... 
That is weird, because the backup from Sunday should contain the whole Saturday dairy entry and not only the half of it...

**Comment by davidhealey** [comment]
> What do you mean with fishy / suspicious, and why do you think that?

Well your data has gone missing. That's not normal.

> Why do you need to know the phone model and OS?

Standard procedure when debugging a weird problem is to find out as much relevant info as possible about the environment on which the issue occurred. It probably won't help to solve the issue today, but if 5 other people report the same issue and they're all using the latest Samsung Foldy phone then we start to see a pattern.

**Comment by hacksenwerk** [comment]
At the moment I can only imagine two scenarios: 
1. It is a bug. 
2. It is a suspicious behaviour and shows that I am under attack. 
If second is the case, than it is highly questionable, why an attacker should delete my food diary, recipes and so on instead of stealing sensitive data? Also how could the attacker delete everything in waistline except the goals and nutriments? 
Do you have any code in your app, that allow attacks?

**Comment by davidhealey** [comment]
Sometimes computers do weird random things. Perhaps there was a bit flip, perhaps the storage on your device is corrupted, maybe something glitched during the saving process.

So far we have nothing to go on to confirm whether it was a bug in Waistline or a general bug on your phone. If it was a bug in Waistline I would have expected more reports of this issue - maybe we'll get more...

We certainly have nothing to indicate some kind of intentional malicious attack targeted at your diet tracking habits - I think that is very unlikely, unless you're a pro athlete or something.

> Do you have any code in your app, that allow attacks?

Well the app is running in Chromium essentially, so I'm sure there are all kinds of possible attack vectors. But nothing specific to Waistline.

Speaking of which, did you update your phone's browser recently? That can cause issues with Cordova based apps such as Waistline.

**Comment by hacksenwerk** [comment]
[Caused by a cosmic ray?](https://www.youtube.com/watch?v=AaZ_RSt0KP8) :) 

I'm not a coder I can only a bit of bash scripting, i don't understand what do you mean with the app is running in chromium. 
Its code contains code from the chromium web browser? 
I don't use chromium as a web browser, I use fennec and that's updated from time to time. 

But corrupted storage sounds familiar to me, all Samsung Galaxy phones I owned had weird storage issues with LineageOS, when I was using a SDCard and even the LineageOS developers can't figured out what causes this... 
But I don't use SDCards in my phone since about a year now. 

But here you go: 
Phone-Model: Samsung Galaxy S5 
OS: LineageOS 18.1 (Android 11)

**Comment by davidhealey** [comment]
> [Caused by a cosmic ray?](https://www.youtube.com/watch?v=AaZ_RSt0KP8) :)

Sure, I doubt the phone has any protection against this.

> I'm not a coder I can only a bit of bash scripting, i don't understand what do you mean with the app is running in chromium. Its code contains code from the chromium web browser? I don't use chromium as a web browser, I use [fennec](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/) and that's updated from time to time.

Waistline is built with [Cordova](https://cordova.apache.org/). It's similar to Electron which you might know of. Basically instead of building an app and compiling it to run on each OS you build a website and it runs inside Chromium. This is what Waistline does. It uses the stock Android browser (as far as I know) so when you update your phone this can trigger issues.

The last time we saw this was a few years ago when Google changed the way Chromium handles databases and it screwed up Waistline for a few users who'd updated. A patch was later issued by Google which solved the problem.

> But corrupted storage sounds familiar to me, all Samsung Galaxy phones I owned had weird storage issues with LineageOS, when I was using a SDCard and even the LineageOS developers can't figured out what causes this... But I don't use SDCards in my phone since about a year now.

It was just a suggestion, we really have no way of knowing what the cause of the issue was. Unless an problem can be recreated on command it's very difficult to debug.

**Comment by davidhealey** [comment]
> Or is it only using "Android System WebView"?

Yeah that's it, it's basically Chromium.

**Comment by DizzyWasTaken** [comment]
Hello. I searched for data deletion problems and found this issue. This just happened to me too. No more entries for food or diary. It's like I just installed it brand new. 

Phone-Model: Xiaomi Mi 9T pro
OS: MIUI Global 12.5.2 stable (Android 11)

The only thing I'm thinking could be related is that my memory is basically full. Xiaomi is known for having a very aggressive RAM memory management. I don't think any sane OS maker would let the phone delete user storage if it's full but that's the only issue that comes to my mind now. Hope there's a way to recover it.

**Comment by davidhealey** [comment]
It's probably web view related.

**Comment by DizzyWasTaken** [comment]
Just updated webview in case it could help. No changes. Does that mean that data is still there but doesn't display? Or that it got actually deleted?

**Comment by davidhealey** [comment]
The data should still be there, Waistline has no known bug that auto-wipes the database.

**Comment by davidhealey** [comment]
Do you have a backup json file?

**Comment by DizzyWasTaken** [comment]
Never made a backup. Never thought this could happen. I made one after the fact and it only contains the test food item.

**Comment by DizzyWasTaken** [comment]
It was turned off. Can't remember if I did it when I installed the app but I got no other json backups.

**Comment by davidhealey** [comment]
Then you might be out of luck, it seems somehow your data was wiped

**Comment by DizzyWasTaken** [comment]
That's unfortunate. Could there be anything that logged the event?

**Comment by davidhealey** [comment]
I don't think so.

@EmilJunker Any suggestions?

**Comment by EmilJunker** [comment]
I'm afraid the data is gone and can't be recovered. This is probably a bug in the WebView.
Maybe we should enable the auto backup by default to mitigate this problem.

**Comment by DizzyWasTaken** [comment]
I installed the app on a new device. This is the displayed data info in the settings

Old install:
```
App size:  19,78 MB
User data: 26,49 MB
```

New install:
```
App:  12,88 MB
Data: 628 KB
```

Old one still displays only the new food item I added earlier. Does this mean data is still present on my device and the app can't reach it for some reason? Can it be recovered in that case?

**Comment by davidhealey** [comment]
It might still be there (I would be surprised if it has magically been deleted). But the fact that it can't see it is strange and I have no idea why that would be.

There might be some kind of database extractor/viewer you can get for Android webview but I don't know.

**Comment by DizzyWasTaken** [comment]
Little update: tried recovering my data a few times with adb backup or with a file explorer but it proves to be impossible to access on a non-rooted device.
