### ISSUE TITLE
Add text note field to meals

### ISSUE THREAD

**Issue by yfede** [davidhealey/waistline#715]
In a similar fashion to the Notes field that can be enabled for Foods, I think it would be useful to have a similar text field for notes associated to each meal (or a cumulative field for the day, if one for each meal is too much)

It would be very useful for tracking e.g. whether after a meal one felt still hungry or too full, for example. 
Or also for tracking averse reaction to certain food (as it was asked in https://github.com/davidhealey/waistline/issues/302 )

I think it would also be helpful to those fighting against certain eating disorders, to keep track of what worked or not for example, or other general notes regarding wellbeing that's tangential to eating

**Comment by EmilJunker** [comment]
You can use the quick add feature to enter short notes in the diary. Press and hold the `+` button below a meal group and enter a note into the description field (you can leave the calories field empty).
I admit it's not a perfect replacement for what you asked, but it's a good workaround for now :)

**Comment by yfede** [comment]
Ah thanks, I had somehow missed the "quick add" feature!
