### ISSUE TITLE
Energy expenditure option

### ISSUE THREAD

**Issue by mathe00** [davidhealey/waistline#722]
Hello, unless I'm mistaken (I've just installed the application) I don't see an option to insert the day's energy expenditure. For example, if I'm doing calorie maintenance at 2200 calories, but I've been doing cardio where I've burned 400 calories, to maintain, I'd have to eat 400 more calories (2600), but I can't specify in the app my energy expenditure such as my steps or my cardio.

So if the feature doesn't exist, I suggest adding it

**Comment by EmilJunker** [comment]
You just have to add an entry with a negative energy value to the diary (for burned energy). This will increase your goal on that day accordingly.

https://github.com/davidhealey/waistline/blob/master/FAQ.md#can-i-use-waistline-to-track-exercises
