### ISSUE TITLE
Adjust servings automatically by weight or volume input.

### ISSUE THREAD

**Issue by Ethanol6** [davidhealey/waistline#726]
When I add foods to my database I use the serving size on the nutrition facts label. When I actually eat the food it is almost never exactly that serving size or even a multiple of that size. Some nutrition facts are calculated on very small quantities and I have to put 8 or 10 servings in the diary to get the proper calculations. I also have to do those calculations manually by converting the weight or volume of the food into servings first. 

Can there be an option to input my "servings" as weight or volume? The app could figure out the number of servings itself. 

For example, I have some salsa that has nutrition based on 30mL servings. If I eat 125mL I should be able to record 125mL as the serving size for that meal and the app automatically adjusts the caloric value by a multiple of 4.167. 

I have found some entries in the OFF database to be different serving sizes than are actually on the products Nutrition Facts label. They have manually converted the serving size and nutrition facts to something that makes sense to them. But it creates a confusing scenario where I have two sources of truth and I can't use the actual products label to calculate serving size. Now add the fact that some foods are correctly input in the OFF database and I am always questioning which food I can use the label for and which ones I can't.

Having a serving input based on weight or volume should eliminate this confusion because the caloric values are always calculated based on what I actually ate and not a "serving" that changes based on whether I used the product label or what someone customized in the OFF database.

**Comment by davidhealey** [comment]
You can already do this. Either once you've added the item to your diary, tap it and edit the amount. Or go to Settings > Diary and enable Prompt for quantity when adding items. Then you will get a pop up for each item you are adding where you can enter the quantity.

**Comment by Ethanol6** [comment]
Oh, so sorry. I didn't realize it was doing that. Cheers!
