### ISSUE TITLE
diary export has problems with german names for macros

### ISSUE THREAD

**Issue by FemmeNoire** [davidhealey/waistline#732]
Hi,

I just noticed that in the diary_eport.csv the names for some macros are not displayed correctly.
Only words with umlauts affected, as well as the unit "µg".

see these two pictures for examples:
![image](https://github.com/davidhealey/waistline/assets/9073536/6a681629-963d-4d55-802a-4d578e8e9e7b)
![image](https://github.com/davidhealey/waistline/assets/9073536/ee8a1cdb-50bd-44b9-acb2-ae726e1043a7)

**Comment by EmilJunker** [comment]
I just checked it. The content of the .csv file is correct. You just need to make sure to open it with UTF-8 encoding. In the screenshot you posted above, it seems to be using ISO/Latin-1 or Windows-1252 encoding which is wrong.

**Comment by FemmeNoire** [comment]
> I just checked it. The content of the .csv file is correct. You just need to make sure to open it with UTF-8 encoding. In the screenshot you posted above, it seems to be using ISO/Latin-1 or Windows-1252 encoding which is wrong.

If I import the .csv in Excel and click data source UTF-8 it seems to work.

Nevertheless it is too complicated in my opinion, because If I download a file the first impulse is to open it. As waistline is an app my phone opens it in Excel.
So no change there to do something different.

Save to phone, then send to onedrive to open it on PC via Excel-Import is not the intuitive thing to to.

**Comment by EmilJunker** [comment]
In that case you need to complain to Excel for not recognizing the file encoding correctly 🤷

Unicode is the standard of choice for text representation and UTF-8 is the most popular Unicode encoding. We are not going to switch to a different way of encoding just because Excel is stupid 😜

**Comment by davidhealey** [comment]
csv files will open in any text editor but if you have excel installed and it's set to the default program for csv files on your system then that's what it will open in by default. If you don't want to use excel for csv just associate the extension with a different program.

**Comment by FemmeNoire** [comment]
I will try and find out if my Android Phone will display me the file correctly sometimes 😄
