### ISSUE TITLE
fdroid version still at 3.6.0

### ISSUE THREAD

**Issue by vyryls** [davidhealey/waistline#736]
Not sure if this is intended or a bug. Is it possible to push the release to fdroid?

**Comment by davidhealey** [comment]
fdroid is meant to pull automatically. I'm not sure why it hasn't.

**Comment by EmilJunker** [comment]
@davidhealey The version number in config.xml is still on 3.6.0. You need to do a git push to increase it to 3.7.0. This should allow f-droid to see it and create the new release. But you'll probably also need to attach a tag since f-droid only looks at tagged commits.

**Comment by davidhealey** [comment]
Ah crap, I updated it but forgot to push it before making the release. I'll fix it now. Thanks!
