### ISSUE TITLE
License information of your project

### ISSUE THREAD

**Issue by oliexdev** [davidhealey/waistline#74]
As I looked into your project I found that your project is licensed under the GPLv3, I am right?
But I couldn't find any hint on GitHub neither the license file. I would suggest that you add this information. For the background that somebody grabs your source code, add some ads and publish it on GooglePlay (which happened to openScale once). Without a clear GPLv3 notice it will be a bit harder to enforce a takedown notice on GooglePlay.

**Comment by davidhealey** [comment]
The license file is in the www folder. The license notice is also stated at the top of every source file as [recommended by the FSF](https://www.gnu.org/licenses/gpl-howto.html). The stuff outside of the www folder is not written by me, it's part of the Cordova framework and each set of files has its own license with it or included in the source files.

There is nothing stopping someone from taking a GPL app and putting ads in it and putting it on the Google play store, that is 100% allowed, as long as they don't make it proprietary.

**Comment by oliexdev** [comment]
Didn't looked into the www folder :)
I suggest to move the LICENSE file to the root folder of your project (which is more common in the open source world) and GitHub can find it and display it.
True somebody can add ads but then they have to publish the changes under the GPLv3 too (which in my case didn't do).

**Comment by davidhealey** [comment]
I've updated the Readme document to explain the licensing. I don't want to move the license to the root because that would imply that all of the files within that folder are covered by the license which isn't the case. Cordova is Apache 2.0 License and the various modules are under other GPL compatible licenses such as MIT.
