### ISSUE TITLE
Subtraction of Exercise Calories

### ISSUE THREAD

**Issue by Shadeclan** [davidhealey/waistline#741]
Would you be able to add a place where exercise calories may be added?  I created a workaround by adding "Exercise" to the Foods where I can input the estimated amount of Calories burned (negative calories).  I might add actual exercises and estimated calories burned for a set time period to make it more convenient.  
Thank you for your great app!

**Comment by davidhealey** [comment]
I have no plans to add this, someone else might though

**Comment by Shadeclan** [comment]
> I have no plans to add this, someone else might though

Well, leave it up.  Someone who's working on the project might give it some thought.

**Comment by Shadeclan** [comment]
Hmmm.  Looks like my workaround isn't completely successful.  It does subtract the calories from the meal subtotal but not from the grand total.

**Comment by EmilJunker** [comment]
@Shadeclan If you add an item with negative calories to the diary it will increase your calories goal on that day by the burned amount. This makes more sense than to subtract it from the consumed amount.

**Comment by Shadeclan** [comment]
> @Shadeclan If you add an item with negative calories to the diary it will increase your calories goal on that day by the burned amount. This makes more sense than to subtract it from the consumed amount.

Aaaah, thank you, I see that is exactly what happened!  So, the workaround did work.

**Comment by Shadeclan** [comment]
> > @Shadeclan If you add an item with negative calories to the diary it will increase your calories goal on that day by the burned amount. This makes more sense than to subtract it from the consumed amount.
> 
> Aaaah, thank you, I see that is exactly what happened! So, the workaround did work.

Oh, and I can add a category called "Exercise" to the diary where I can put exercise results.  I think that's pretty much everything that is needed, I guess you can close this request although you may want to add a default exercise category.

**Comment by EmilJunker** [comment]
I also think this issue can be closed. I don't think we need a default diary section for exercises since not all users will need it, and those who do can simply add it.

@Shadeclan If you want to make things even more organized, you can also add a food category for the exercises under `Settings > Foods, Meals, Recipes > Labels and Categories` and assign it to the different exercises you create. This would allow you to use the filter inside the search box to show only the exercises in the foods list.
