### ISSUE TITLE
[Feature Request] Enable sharing of the database backup

### ISSUE THREAD

**Issue by Ingrimmel** [davidhealey/waistline#744]
With Android 13 and Samsung's One UI 5.1 it seems impossible to access `/Android/data/com.waist.line/files/waistline_export.json`. 

Therefore, it is apparently not possible to copy the database backup from the device and import it again later (I cannot open the path with the importer either). 
To get around the continuing restrictions of android, I think it would be a very nice solution to introduce a "share" button for this. Then you can store the database backup directly in Nextcloud/Dropbox/etc. 

This would not enable an automatic solution as requested in #553 or #515 but should be more reliable from a Android-restriction perspective.

Thanks for the good work!

**Comment by EmilJunker** [comment]
> With Android 13 and Samsung's One UI 5.1 it seems impossible to access `/Android/data/com.waist.line/files/waistline_export.json`.

Try it with this file browser app from the Play Store: https://play.google.com/store/apps/details?id=com.marc.files

With this app I can access the backup files on my Samsung phone running Android 13 and One UI 5.1.

**Comment by Ingrimmel** [comment]
Ffirst - and foremost! - thanks for the tip! 

That works for now. Nevertheless, I would like to leave the discussion about the feature open - at least for the moment. 

It is quite a roundabout way and whether it will work in the long term is also unsure.
