### ISSUE TITLE
[Feature Request] allow to display _any_ nutrient in Diary and Statistics

### ISSUE THREAD

**Issue by RalMay** [davidhealey/waistline#746]
Hi!
Thank you for a very nice program that's pretty near my actual needs.

What I am missing:
You allow many additional and even custom nutrients to be used in Foods, Meals and Recipes but do not allow to display any other than the major 5 (Calories, Fat, Carbs, Protein, Salt) in Diary or Statistics - which makes recording them rather point-/useless.
Please allow users to display the nutrient they have to watch instead of only these 5.

Additional: In Foods/Meals/Recipes you only display kcal in overview (other nutrients only when the user selects an item to see the details), please allow to display 1+ additional values in overview so the user can easily select meals for this parameter. Just think of ppl with kidney problems whose major issue is (AFAIK) salt, not cals.

Thank you very much.

**Comment by davidhealey** [comment]
You can already do this, please check the various options in the Settings page.

**Comment by RalMay** [comment]
I am sorry for obviously being dumb but I simply don't see not what else to enable to achieve this.
![1](https://github.com/davidhealey/waistline/assets/65014385/f5f6b268-f732-41f5-89d5-db5c8ad0fe82)

**Comment by davidhealey** [comment]
Settings >> Goals >> Set Goals

There are tons of settings in Waistline. You need to dig around and explore them.
