### ISSUE TITLE
Bug: app no longer follows system theme

### ISSUE THREAD

**Issue by niporasomo** [davidhealey/waistline#748]
I wanted to quick report a bug I noticed - it looks like the app no longer follows the system light/dark theme even with the setting enabled. I'm on the current version of the app, 3.7.2, and Android 13 on a Pixel 6a. Thanks for all the work you've put into the app!

**Comment by EmilJunker** [comment]
Thank you for the hint. It looks like there was another change in Android SDK 33. Should be an easy fix: https://github.com/timbru31/cordova-plugin-android-dark-mode-support#attention-for-sdk--33--android-13

**Comment by niporasomo** [comment]
Awesome, thanks for letting me know!
