### ISSUE TITLE
Homescreen display issue

### ISSUE THREAD

**Issue by grrrrr** [davidhealey/waistline#75]
Finally 2.3.5 has hit F-Droid so I am able to confirm the following was not just a bug with the older version I had access to.

* LineageOS: 14.1 (Android 7.1.2)
* Waistline 2.3.3 - 2.3.5

**Issue:**
Changing `homescreen` in settings does not work as expected.   It results in a blank version of the chosen screen

**What happens:**
Go to `settings` and change homescreen to diary.   Back out of waistline and reopen it from Android.   The correct screen is selected but the contents are black.  To display the contents you need to click the hamburger in top left of waistline and re-select your chosen homescreen.

This appears to only be if you choose `statistics`,`diary`, `food list`, `recipes` and `goals`.

It does not happen if you select, `settings` or `user guide` as your homescreen.

**What should happen:**
Go to `settings` and change homescreen to diary.   Back out of waistline and reopen it from Android.   The correct screen is displayed correctly.

**Comment by davidhealey** [comment]
I have diary set as my homescreen and don't have this issue, I also don't have it with any of the other pages you mentioned. I'm guessing this is related to the javascript datetime issues that have been causing problems for the last few releases. What timezone are you in? 

One thing I find curious, all of the screens you mention use the datetime object to generate their data, except for the goals screen. So can you show me a screen shot of the blank goals screen?

**Comment by grrrrr** [comment]
Sorry, brain fart.  Goal screen is not an issue.    

Phone is set to GMT+1 automatically set time and time zone.   Manually setting to GMT+1 or GMT+0 same problem

**Comment by davidhealey** [comment]
Try setting the locale of your phone to UK as well. I'm 99% sure this is the date issue and I'm 100% sure I am losing hair due to it :p

**Comment by grrrrr** [comment]
> Try setting the locale of your phone to UK as well. 

Do you mean `Settings -> Languages and Input -> Languages`?   If so it's already set to UK
