### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#751]
Please add direct cryptocurrency addresses within the app. I don't want going around to websites. I don't want support FIAT economy.

TRX, LTC, BTC, XEC, SOL, BCH, ALGO, XTZ, DASH, XMR addresses available for donations.

**Comment by davidhealey** [comment]
This isn't going to happen. I don't really like crypto and I don't need donations. Just enjoy the app :)
