### ISSUE TITLE
100 kCal to food weight (new benchmark)

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#752]
I would like to add a new benchmark to calculate the caloric incidence of food.

Conventional cards tells 100g equals 457 kcal.

Instead I want to know how many grams a food has to weight to reach 100 kcal.

To understand, the constant is no longer 100g, but 100 kcal.

This increases my awareness.

**Comment by davidhealey** [comment]
You can already do this. Click the link button at the top of the food edit screen and then changing the calories will change the grams

**Comment by davidhealey** [comment]
Oh that's a big task! Might be quicker to export the database to json and work with it there.
