### ISSUE TITLE
[feature] Ability to add raw calories to a meal in the diary

### ISSUE THREAD

**Issue by mickelsonmichael** [davidhealey/waistline#753]
## Summary

This is a feature available on apps like [myFitnessPal](https://support.myfitnesspal.com/hc/en-us/articles/360032621971-What-is-Quick-Add-) which allows you to add calories directly without having to specify the name of the food.

This is helpful for those that are not interested in macros and are more interested in CICO calculations. It also makes it easier to quickly add foods.

## Desired Behavior

- User clicks the plus button on the "Diary" page for a meal (or potentially a dedicated button)
- On the following page, a new option for "Quick Add" or "Add Calories" should be clickable
- Clicking the button should either redirect to a new page or a modal should appear
- The modal should have a field for "Calories" and (optionally) a field for "Description" or "Name"
- Clicking a confirmation button should add the item to the user's meal for the day

## Other Considerations

- The editing page could have fields for macros, but (in my opinion) would be better hidden to start, requiring the user to click an "Add Advanced Nutrition" option
- The description/name field could be optional and a default "Unspecified Calories" message could be displayed in the diary

I am interested in contributing this feature myself, but I wanted to iron out some of the details before creating a PR and dedicating time to it. I'd love some feedback and to develop the idea a little more.

Thanks!

**Comment by davidhealey** [comment]
You can already do this. Tap and hold the plus button.

**Comment by mickelsonmichael** [comment]
Oh fantastic! Thank you.

May I suggest then that this feature be made more obvious? There are a few places where the UX could be improved to be more intuitive
