### ISSUE TITLE
Merge two or more food items if they are in the same meal and identical

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#754]
Before

![1000040577](https://github.com/davidhealey/waistline/assets/113377431/2cf2b6e0-7ec8-45fd-8d94-d990fb8d82f7)

After (with merge applied)

![1000040581](https://github.com/davidhealey/waistline/assets/113377431/67a1d5df-2029-4ea9-9926-421af1e11dd4)

**Comment by davidhealey** [comment]
I don't think this is necessary. You can just add the item twice.
