### ISSUE TITLE
Kindly update latest version (3.7.3) to Google playstore (last version: 3.7.0) & F-droid (3.7.2)

### ISSUE THREAD

**Issue by parthvyas7** [davidhealey/waistline#756]
Kindly update latest version (3.7.3) to Google Play store (last version: 3.7.0) & F-droid (last version: 3.7.2) as Theme changes were significant

**Comment by davidhealey** [comment]
Already done. I always update Play at the same time I post a new release (which F-droid picks up). For some reason the 3.7.2 release on Play has been held in a review state and currently 3.7.3 is also in review. It says it should take 7 days to clear review but can take longer...

**Comment by linsui** [comment]
Yes, it's a network glitch. It will retry the build automatically.
