### ISSUE TITLE
Add separator between category and name in the food list

### ISSUE THREAD

**Issue by columndeeply** [davidhealey/waistline#769]
Hi! When you enable "Show Category Labels" in "Foods, Meals, Recipes" the category name gets added to each product name but it doesn't have a separator which makes it looks like it's part of the name.

Here's an example, I've added a "Drinks" category and added "Coca-Cola" and "Coca-Cola Zero" to it. IMO it should show up as "Drinks: Coca-Cola". I know it's not a big problem but it can get confusing when you're scrolling through the food list.

![Waistline](https://github.com/davidhealey/waistline/assets/106948293/ab895ada-af9c-44ae-9c82-0ac913a827de)

Also, I just realized the category list doesn't sort itself alphabetically, it sorts by creation time. Not sure if it's intended to be like that or if it should be sorted...

**Comment by EmilJunker** [comment]
It is recommended to use emojis for the category labels. That looks something like this:
![Screenshot_20231021-075543](https://github.com/davidhealey/waistline/assets/19289477/4aa5caa1-c7b1-4975-a901-9f54898dcc41)

Alternatively, you could wrap the text in brackets. That would look like this:
![Screenshot_20231021-080032](https://github.com/davidhealey/waistline/assets/19289477/23f7e8c7-5897-45f3-9d4e-2a583b2f8fff)

The sort order of the category list can be manually adjusted in settings via press and hold.

**Comment by columndeeply** [comment]
> Alternatively, you could wrap the text in brackets. That would look like this:
Nice, didn't think about that. I'll do it like this, looks much better.

> The sort order of the category list can be manually adjusted in settings via press and hold.
Thanks, I was trying to drag them around but I wasn't holding them long enough it seems.
