### ISSUE TITLE
Unsolicited redesign request

### ISSUE THREAD

**Issue by Geffreyvanderbos** [davidhealey/waistline#77]
Hey David,

love your work. Recently gotten into Open Source because of some big brother app screwing me over. 

I am a designer (4 years in UI now) and would love to tackle some of the UX / UI of the Waistline app. 

How can I best do this? (If you allow me to)

**Comment by davidhealey** [comment]
Hi,

The UI is built with OnsenUI which provides all the UI widgets and the CSS theme. Are you familiar with Onsen? What parts of the GUI do you feel need improvements?

**Comment by Geffreyvanderbos** [comment]
I understood. I am not familiar with Onsen. However I am familiar with HTML, SASS and Javascript.

To no offense to you and your work: the GUI can use both an aesthetic and UX refresh to launch it into 2019.

I will make a proposal – perhaps you like the idea! Consider it a graphical pull-request. :) 

It'll take a few days to brew. (I'll prepare it in the late evenings)

**Comment by davidhealey** [comment]
Let me know what you have in mind and where you think improvements are needed and we'll go from there.

**Comment by Geffreyvanderbos** [comment]
Fair enough.

It's a shame that the app needs such an extensive 'user guide'. I believe an UI should speak for itself and rely on common design patterns. I think it does, mostly. With some visual hints, the app can definitely go without an user guide (at least with a minimal one).

The navigational structure is flat and mostly hidden behind the menu. Despite some screens will be definitely used more than others. Would be beneficial to the user to have have a more hierarchical user flow. 

The contrast and separation between elements are not optimal – this could be easily by a few  typographic solutions.

As a quick show case I've added a screenshot. With that I've tried to keep it as similar to what you've set in your project, and merely building on it. (It's definitely not optimal yet) 
![waistline-home-mockup](https://user-images.githubusercontent.com/38939868/47041678-fa466c00-d178-11e8-9dd8-a934703dc545.png)

**Comment by davidhealey** [comment]
The design is nice. I like the colour scheme. I'd like to stick with the current colour for the header bar (footer in your design) as this matches the colour of the icon and splash screen.

I wanted to add plus buttons to the category headers (like you have done) when I made the app but it's not easy to do with OnsenUI unfortunately, the formatting kept getting ruined, so i gave up, I might try again.

I don't think onsen provides a way to add a floating button with text like you have. Also I don't think that is needed if we have the plus buttons. 

What is the circular button for in the bottom right corner?

Where is the menu button?

I don't see a display for the date in your design.

I like the layout for the nutritional consumption, although I'm not sure I'll be able to implement the little arrow in Onsen. I'd also colour the consumed nutrition green if it's less than the goal and red if it's more.

**Comment by Geffreyvanderbos** [comment]
Very nice. Yes it's a flawed proposal. It was a 20 minute mockup.

The colour scheme I'd try to keep. Of course updating the icon and splash screen would be part of the refresh.

The add food button is there as a main CTA. Something that drives the user to their main goal: tracking their food. One single button to do the thing that solves their 'problem'.

It does not matter if there are more ways to the same function The plus buttons per meal section are shortcuts more than a cta. Harder to click, harder to reach, but available when the user seems fit. 

Denoting the status of the macros with colour is a great idea.

Is Onsen really that limiting? (That's too bad, really)

**Comment by davidhealey** [comment]
There are probably ways to hack onsen and of course it can be bypassed but it tries to keep to Google's material design standards with things like the floating buttons. It doesn't have to be a plus button though, it can contain an icon or text. 

Here's a list of everything it offers - https://onsen.io/theme-roller/

**Comment by Mitlik** [comment]
I would love to see the daily consumed of calories *and* macros vs goal in the diary like that. Having the per meal calories would also be great. Some weight lifters like to target certain calories at certain meals, so it'd help with that.

Would the bottom right button be the day selector with left/right swipe being a single day advance/retreat?

**Comment by davidhealey** [comment]
Yes I like that display for the calories and macros, but I'm going to keep them at the bottom of the screen - otherwise it starts looking too much like another well known calorie counting app. Per meal calories is already in Waistline btw.

**Comment by Mitlik** [comment]
In the footer is fine. Maybe thin progress bars so cal + 3 macros can all be displayed simultaneously without eating too much realestate? Or a pie chart to show calorie macro makeup.

You are, of course, correct that the per meal calorie total is already there. Maybe it failed to register when I was glancing because of lack of units or I just looked too quickly.

Another thought on meals... would it be possible to have them expandable/collapsible? So you could just have the headings with the sum or the full list then maybe long press to see all the items from the meal. Long press the header again to collapse. That would make room for the pie chart someone mentioned earlier... 😇

**Comment by davidhealey** [comment]
Collapsible headings is a good idea! I'll see if I can add this easily.
