### ISSUE TITLE
Please add date and time for each weight measurement

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#771]
Sometime I noticed that value comes from "yesterday's" measurement.
So I just want to know how old is that measurement.

![1000095817](https://github.com/davidhealey/waistline/assets/113377431/e8b6c804-3df6-46d8-8798-9e5fedf372fe)

**Comment by davidhealey** [comment]
If there is no value entered for the current day then it will always be populated with the most recent value.

**Comment by davidhealey** [comment]
If you go to the statistics screen, set the stat to Weight, and scroll down to the Timeline section you can all your weights by date
