### ISSUE TITLE
USDA Results are Sparce

### ISSUE THREAD

**Issue by SpookedByRoaches** [davidhealey/waistline#775]
When adding the USDA database search ability, it the same roughly 15 items. I tried to search for bread in the USDA database and it only showed some random USDA entries. See here
![image](https://github.com/davidhealey/waistline/assets/38513225/05d93648-d6cb-43d4-9921-c0046208ef13)

However, when searching the USDA FoodData Central it shows good results
![image](https://github.com/davidhealey/waistline/assets/38513225/0a67e5d8-a4b5-4bc4-9156-b18b9be5d2db)

Is there something wrong in my configuration or something?

This happens on 2 devices.

Device 1: Fairphone 5, Android 13 /e/os 
Device 2: Pixel 6 Pro, Android 14 Graphene OS
Both version 3.7.3

**Comment by davidhealey** [comment]
Looks like a bug to me

**Comment by EmilJunker** [comment]
This only seems to happen when your search term includes the word "USDA". If you just search for the thing you want, it returns more useful results.

**Comment by davidhealey** [comment]
@EmilJunker Aha good catch, I missed that!

**Comment by SpookedByRoaches** [comment]
Ah you're right it returns good results now. I guess I should put some keywords with commas like "Bread, white" or something. Thanks!
