### ISSUE TITLE
Add X number of servings

### ISSUE THREAD

**Issue by savchenko** [davidhealey/waistline#781]
Once food item is added, it's not possible to add, for example, 1.5 servings of it.

An example:

1. I have created "baked beans" food item with serving size 100g and serving unit of 1.
2. I add baked beans in "Diary" section and I can only add in 100g increments by adding more identical items.

It would be good to show user a counter that allows to specify number of items before the food is added. It's commonplace to have odd servings (e.g. 180g).

**Comment by davidhealey** [comment]
Either tap on the item once it's in the diary and edit the servings or enable Settings > Diary > Prompt for quantity when adding items
