### ISSUE TITLE
[Feat] Add dashboard login / logout

### ISSUE THREAD

**Issue by Yushi5058** [davidhealey/waistline#784]
Hey, 
It would be an awesome idea if we implement a login/logout system to save our account and all of the data in it ( food list, recipes etc ) 
Thanks, 
Yushi

**Comment by davidhealey** [comment]
I don't think will ever happen. The whole point of Waistline is your data is managed by you on your device and is never uploaded anywhere. If you want to sync it you can already do this. I can't remember the details but I believe there are two methods. You can import the json file on a new device or you can have the data sent to a web service end point.

**Comment by Yushi5058** [comment]
I was asking about this possibility, save locally. Thanks

**Comment by davidhealey** [comment]
Aha so you mean you can have multiple accounts on a local device?

**Comment by Yushi5058** [comment]
No I wanted to know if its possible to have my data saved so if I change my decice, I still have everything saved

**Comment by davidhealey** [comment]
Oh yeah that's already there. Just enable the backup option, or manually export the data. Settings >> Import/Export
