### ISSUE TITLE
Import file

### ISSUE THREAD

**Issue by Mitlik** [davidhealey/waistline#79]
It took me a bit to realize that the import file had to be named something specific in a specific location. Now that I know it's not a big deal. The guide hints but does not specify filename or location and there's no file picker. I think either option would solve the issue. The latter would be more user intuitive, but you might have to do something to export files to easily identify them as waistline json data.

**Comment by davidhealey** [comment]
Yes I wanted to include a file picker but it's not easy, this will be added at some point though.

**Comment by jkothe** [comment]
What is the specific file name and path?
Android/data/com.waist.line/files/waistline_export.json does not work :(

**Comment by davidhealey** [comment]
Android/data/com.waist.line/files/waistline_export.json should be correct. What version of Android and Waistline are you using?

**Comment by jkothe** [comment]
Waistline Version 2.3.7 from F-Droid
Android 8.1.0 LineageOS 15.1 without Google Apps
Also tested with an BQ M10 Tablet with Android 6.0 with Google Apps.
When I tab on Import data nothing happens.

**Comment by davidhealey** [comment]
Someone reported a bug with this, you have to double or triple tap the import button to get it work. I'll fix this soon.

**Comment by jkothe** [comment]
Thanks - double tap works.

**Comment by davidhealey** [comment]
The double/triple tap issue is fixed. I've not been able to implement a file browser, I know how it can be done but it's a huge pain for little gain. What I've done instead is added a default 'Waistline' folder in the home directory.
