### ISSUE TITLE
Optional access to my fitness pal database

### ISSUE THREAD

**Issue by kalchen6666** [davidhealey/waistline#790]
Hi, 

Maybe it would be possible to give users the option to access the myfitnesspal database via the API? 

I thought something like that could be accessible in the options: https://github.com/realPrimoh/grab-myfitnesspal

Like if you already have a myfitnesspal account and would like to use the database but without the ads.

And then you could automatically see it when you search for food. 

Or maybe it would be possible to just scrape all foods, but I could imagine that this would be too large to be integrated in the app

I am a huge fan of the app!

**Comment by davidhealey** [comment]
I don't like the idea of Waistline being used to circumvent another developer's systems. I also want to encourage the growth and adoption of Open Food Facts over proprietary alternatives. 

@EmilJunker What do you think?

**Comment by EmilJunker** [comment]
I also don't like the idea of integrating another app's food database. The current combination of OFF and USDA databases in Waistline is perfectly sufficient - and already complicated enough to handle and maintain 😅
