### ISSUE TITLE
Feature reauest: quick add

### ISSUE THREAD

**Issue by JohnnyBeGood625** [davidhealey/waistline#791]
Hello,

Thank you for creating and maintaining the app.

There seems to be one function missing: a simple quick entry of calories/protein/fats/carbs to the journal.

The reason is that there are many ocasions where we know nutritional values for a meal and want to enter them in the journal but currently only food items with a barcode or within the OpenFoodFacts database can be added.

Adding a "quick add" function would allow for entering values for one-time, non-scannable items.

Thank you

**Comment by davidhealey** [comment]
Quick add is there, tap and hold the plus button. It's only for calories though.
