### ISSUE TITLE
[ENHANCEMENT] Search Functionnality Improvment

### ISSUE THREAD

**Issue by Yushi5058** [davidhealey/waistline#794]
Hello,
I searched in the issues but I don't know if someone already mentionned it. I'd like an improvment for the search functionnality of foods. When for example I'm searching for eggs, I get all foods made with eggs except eggs themselves. Or for example, if I search for chicken breast, fruits and veggies. I have the same result, everything but what I really search for.
Thanks for the awesome work done on this app,
Yushi

**Comment by davidhealey** [comment]
By default Waistline only pulls from the Open Food Facts database. This is limited to items that have a barcode, so things like fruit and veggies, or other generic items won't be included. 

For that you can use the USDA database. This can be enabled in Waistline's settings, you need to get a free API key from USDA enter it into Waistline to allow you to connect to that database - this is a reason it isn't enabled by default.

**Comment by Yushi5058** [comment]
the USDA api can be used for other countries, because as the same suggests it is for USA residents. Correct me if I'm wrong, thanks

**Comment by davidhealey** [comment]
Anyone can use it. I'm in the UK.

**Comment by Yushi5058** [comment]
Okay thanks
