### ISSUE TITLE
Animation toggle doesn't work

### ISSUE THREAD

**Issue by thom-cameron** [davidhealey/waistline#797]
The Appearance > Disable UI Animations switch doesn't have any effect. Having animations turned off system-wide also doesn't disable animations in the app.

**Comment by EmilJunker** [comment]
It's working on my phone. When I turn on the Disable UI Animations option and restart the app, things like switching between pages or loading charts on the statistics page happen instantly and without animations.

**Comment by thom-cameron** [comment]
Weird. It's not a big deal and if it's unique to my phone it's probably not worth fixing anyway. Thanks!
