### ISSUE TITLE
Goal calories displayed

### ISSUE THREAD

**Issue by Mitlik** [davidhealey/waistline#80]
I changed my goals to cycle calories and the calories at the bottom of the diary don't update correctly unless I go reload the goals. Example: I alternate between 1500 and 1700 kcal. If I load goals on a Monday with 1500 kcal the diary page displays 1500. When I load Tuesday, previously set to 1700 kcal, the diary still shows 1500 as goal.

Admittedly, I've only confirmed this on 2.3.4 so far. I'll try newer versions and update.

**Comment by davidhealey** [comment]
I don't quite understand, could you make a video demonstrating?

**Comment by Mitlik** [comment]
Here's a gif running 2.3.7

![gif_20181028_071610](https://user-images.githubusercontent.com/777110/47616362-c5e08300-da89-11e8-86c7-68c6e47a5d3a.gif)

**Comment by Mitlik** [comment]
Update on this. If the day changes (appears to be the UTC day) without forcing the calories to the correct value, it will save at the incorrect value.

**Comment by davidhealey** [comment]
I'll have to investigate this further but it sounds like another Javascript timestamp related bug

**Comment by corngood** [comment]
I just had something similar happen.  I have my goal set to 2500 for all days, but tonight around midnight local time the goal for today (well, yesterday) changed to 2000.  I'll take a look at the code and my DB to see if I can figure out what went wrong.  I have the recent timezone fixes, so it sounds like the same bug persists, but now at local midnight.

**Comment by corngood** [comment]
This is interesting.  All of the correct goals are strings, and the incorrect ones are numbers:

```
$ adb shell cat /sdcard/Android/data/com.waist.line/files/waistline_export.json | jq '.log[].goals.calories'
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
2000
2000
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
"2500"
```

**Comment by davidhealey** [comment]
Maybe a parse int will solve the issue

**Comment by davidhealey** [comment]
hmm this is an interesting one...

**Comment by davidhealey** [comment]
I haven't been able to recreate this issue. @Mitlik Could you test if it's still present in the latest version?
