### ISSUE TITLE
Crowdsourced food database

### ISSUE THREAD

**Issue by candroid-man** [davidhealey/waistline#808]
I have added 11 items today and none of them have had accurate information. Of course Wasitline is not to blame for this, it's the database that it uses for nutrient label information. I petition that we come together and start our own database that people can contribute to so everyone can benefit.

The database would be built into the app, and if any changes are made when adding an item after scanning a barcode, Wasitline could prompt the user if they'd like to send your edited version to the online database. Or you could have this feature opt-in in the settings.

This feature is in the Carb Manager app (according to someone I know who's used it), and it would be way more convenient for users to quickly get correct nutrition information.

**Comment by candroid-man** [comment]
Alternatively, if users could login to their Open Food Facts account, and enter an API key into Waistline, perhaps we could edit existing entries within the app. This may be a better option tbh

**Comment by EmilJunker** [comment]
Waistline is not an Open Food Facts editor and probably won't become one. But on the food editor screen, you can tap on the barcode to open the OFF website/app and edit the product information there. Then you can go back to Waistline and press the download button at the top to re-download the latest information from OFF into Waistline.

**Comment by davidhealey** [comment]
I have no plans to add a separate shared database or an OFF editor to Waistline. I prefer to have an app that does one job and does it well - and I'm not sure Waistline has even achieved that yet.
