### ISSUE TITLE
Adding pictures to meals and recipes

### ISSUE THREAD

**Issue by thebigjoe1** [davidhealey/waistline#812]
To help with visual cataloging, I think it would be helpful to have the option to be able to add our own pictures to meals and recipes as well as having the option to automatically utilize the pictures of the various items that make up the meal or recipe. For example, if i have a recipe for rice balls, it could create something like the below. 
![Screenshot_20240423-203835](https://github.com/davidhealey/waistline/assets/26659217/d09524ce-c6bf-4e6b-b3ca-7babb8fdad9e)
These would just be additional options to add and not need to be default. Let me know your thoughts. Thanks!

**Comment by candroid-man** [comment]
I agree, it would be a good option to have at least
