### ISSUE TITLE
Set keyboard to standard numeric keyboard when filling nutritious values

### ISSUE THREAD

**Issue by tenzap** [davidhealey/waistline#825]
When filling nutrition values like calories, carbohydrates... the keyboard that is displayed is like a phone numeric keyboard. https://en.wikipedia.org/wiki/Telephone_keypad
```
1 2 3 
4 5 6 
7 8 9
...
```

This is rather disturbing. I would have expected to have a numeric keyboard like on the computer keyboards or calculator keyboards, like this: https://en.wikipedia.org/wiki/Numeric_keypad
```
7 8 9
4 5 6
1 2 3
...
```

Is it possible to change this?

**Comment by EmilJunker** [comment]
I'm afraid it is not possible for Waistline to control this. The key layout you see on your phone depends on the keyboard you (or your phone manufacturer) have installed. There are eight different input modes for form fields, each of them will show a slightly different key layout. You can see all eight modes here and test how each of them is displayed by your phone's keyboard: 
www.inputmodes.com
The nutrition fields in Waistline are of the `numeric` type.
