### ISSUE TITLE
Manually adding barcode when "no results" is displayed after a scan

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#827]
Also I wish adding alcohol in % value in recipe.

![1000111849](https://github.com/davidhealey/waistline/assets/113377431/76ca9f53-c512-4781-8fcb-087238f4b18c)

![1000111845](https://github.com/davidhealey/waistline/assets/113377431/99eb657b-fc83-4fa9-ba25-7bfc36c06350)

**Comment by davidhealey** [comment]
Barcode is only used for open food facts, if the item isn't in the database and you want to add it you can select that option when prompted and the barcode will automatically be entered.

For Alcohol go to Settings > Nutrients, and enable the Alcohol switch.

**Comment by davidhealey** [comment]
Oh apparently alcohol is in g, it should be %.

**Comment by EmilJunker** [comment]
> Oh apparently alcohol is in g, it should be %.

Alcohol is in gram because it makes more sense for tracking. You wouldn't want track to your intake and set your goal for alcohol in percent (what would that even mean?).

In the USDA database, the alhocol values are already listed in gram anyway. When importing items from OFF, Waistline automatically converts the percent value into gram by taking into account the density of ethanol.

**Comment by davidhealey** [comment]
> You wouldn't want track to your intake and set your goal for alcohol in percent (what would that even mean?).

Hmm this makes sense but I think on most drinks the value is only given as a percentage so it makes it hard to enter values. I don't think there is anything we can do though as we can't convert grams to volume without specific information about the alcohol in the individual beverage.

**Comment by EmilJunker** [comment]
@davidhealey I agree with you that the current solution is not ideal, but I honestly can't think of a better one.

When uploading items to OFF, Waistline lets the user enter the alcohol value in %. When downloading from OFF, it converts it to g. 

See also #558 and #563.
