### ISSUE TITLE
change backup destination

### ISSUE THREAD

**Issue by Luke56784** [davidhealey/waistline#828]
Hi

First, I'm using your app with great success! Thank you so much!

Is it possible to change the backup folder?
Default is somewhere in Android/data/

Problem is that I can not access this folder to back it up somewhere else in case the phone gets lost / breaks.

I'm using a Pixel 7 with Android 14.

https://www.reddit.com/r/Android/comments/173lsrc/android_14_storage_access_framework_no_longer/

even with the internal file manager it no longer works. the folder is not displayed even if i switch on show hidden files.

have a nice day!

**Comment by EmilJunker** [comment]
It is not possible to change the backup location. But you should be able to access the folder with this file browser app from the Play Store:

https://play.google.com/store/apps/details?id=com.marc.files

Or get it via APK mirror if you prefer that:

https://www.apkmirror.com/apk/marc-apps-software/files-20/

**Comment by Luke56784** [comment]
I've already tried that. Unfortunately it doesn't work either.

The folder "Android/data/com.waist.line" is not displayed.

**Comment by EmilJunker** [comment]
That's weird, you're the first person to report problems with this workaround. Maybe it's a special thing with Pixel phones 🤔 

Anyway, as a last resort, you should definitely be able to access that folder when you connect your phone to your computer. Of course, this is not ideal, but we really cannot change the backup location on Android 13 and above.

**Comment by davidhealey** [comment]
> Maybe it's a special thing with Pixel phones

I'm using a Pixel6a

**Comment by Luke56784** [comment]
This afternoon I had already tried to access this folder via WiFi using the "myphoneexplorer" app.

But the Android/Data directory was completely empty.

I'll have to test it again via cable connection.

Is it perhaps possible to store the backup in the cloud?

**Comment by davidhealey** [comment]
> But the Android/Data directory was completely empty.

There's something strange going on, this folder should contain sub folders for several apps - unless you have no other apps on your phone.

**Comment by Luke56784** [comment]
Yes. I can the subfolder through this files app you linked.

But it shows me not all folders. Strange. I took e screenshot for you. The folder should be above or under the com.Whatsapp folder. But it's not there.

![Screenshot_20240523-231351~2.png](https://github.com/davidhealey/waistline/assets/126562710/f72ab4d2-9295-4702-944e-c141860dfb43)

**Comment by davidhealey** [comment]
What's with the weird characters, is that just a glitch of the screenshot or is that what you see?

![image](https://github.com/davidhealey/waistline/assets/14021202/7b9a8ebe-eaa5-438e-9890-d84818e32573)

**Comment by Luke56784** [comment]
I censored this with the "Magic eraser" tool.

**Comment by asdf512** [comment]
FYI, backups output to directory:
/storage/self/primary/Android/data/com.waist.line/files/

Not:
/storage/emulated/0/Android/data/com.waist.line/files/
Which is why it isn't showing in the file browser.

Had to pull using adb to transfer to my pc.
