### ISSUE TITLE
serving descriptors are parsed incorrectly

### ISSUE THREAD

**Issue by corngood** [davidhealey/waistline#83]
![screenshot_20181024-231945](https://user-images.githubusercontent.com/3077118/47472111-b6d8a700-d7e3-11e8-9cc8-98bcf797bb79.png)
![screenshot_20181024-231956](https://user-images.githubusercontent.com/3077118/47472118-c0620f00-d7e3-11e8-86b3-f505c6a1f942.png)

The unit is being parsed as 'gLOAF' in this case.

**Comment by davidhealey** [comment]
I asked in your other post about locale, I suspect this could also be related.

**Comment by corngood** [comment]
My phone is using en-uk.  I'll set myself up to build and run the app in a simulator so I can investigate a bit more.

**Comment by Mitlik** [comment]
Confirmed in en-us.

**Comment by davidhealey** [comment]
I just looked into this more. This isn't a Waistline issue, this is how someone has entered the data into the Open Food Facts database. 
See:
https://world.openfoodfacts.org/product/0050700563220/garlic-bread-traditional-homestyle-parade

If you want to fix it you'll need to do it through the open food facts website.
