### ISSUE TITLE
Adding a photo of the ingredients on new products

### ISSUE THREAD

**Issue by teolemon** [davidhealey/waistline#830]
Hey,

Would it be possible to add an extra button to add a photo of the ingredients on new products ?
Just the photos allows to make the checks on the products more reliable (we can predict the food category more easily and thus cross-check nutrition), and it's really useful for other users.

Pierre

**Comment by EmilJunker** [comment]
There already exists an "Additional Photos" section where users can add pictures of the ingredients and packaging information when uploading a product. Of course, whether people actually make use of this is outside of our control. 

![Screenshot_20240526_130542_Waistline](https://github.com/davidhealey/waistline/assets/19289477/7d1112a7-4bf9-4978-89d8-46de14655936)

**Comment by teolemon** [comment]
Sorry about the noise. I should have double checked. Thanks @EmilJunker
