### ISSUE TITLE
Tracking ingested gas (within beverages)

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#835]
I wish finding a way to track gasses (Coca Cola, Beer, etc.) when drinking any of these beverages (mostly CO²).

**Comment by EmilJunker** [comment]
The OFF and USDA databases don't provide any information about the amount of gas in beverages. But nothing stops you from creating a custom nutrition field under `Settings > Nutrients > Add Field` and populating it with your own values.

**Comment by davidhealey** [comment]
> Problem is how much CO² is within of a 330ml Coca Cola can?
> 
> I have no idea.

Neither do we :)

I don't think this is relevant for Waistline so I'm going to close this one.
