### ISSUE TITLE
Days added to the database out of order

### ISSUE THREAD

**Issue by amgarr** [davidhealey/waistline#837]
I have noticed that some dates are added out of order in the database. Is this because I may have added something on the 17th on the 16th and then went back. Is there any other reason this would happen?

| ID | Date | 
|--------|--------|
| 432 | 06-17-2024 |
| 433 | 06-16-2024 |
| 434 | 06-18-2024 |
| 435 | 06-19-2024 |

**Comment by EmilJunker** [comment]
Is this causing any actual issues for you? The order of days in the database shouldn't affect what you see in the app.

**Comment by amgarr** [comment]
I am using the data sharing feature and it got a bit jumbled. It's not an issue with waistline per se, I just want to know how to avoid it happening in the future.

**Comment by EmilJunker** [comment]
> I may have added something on the 17th on the 16th and then went back

I think your description of how it happened is correct. This must be how it happened.
