### ISSUE TITLE
Enabling adding exercise sessions with estimated burned calories

### ISSUE THREAD

**Issue by prototyperspective** [davidhealey/waistline#842]
Otherwise one has to adjust in the head or tends to go to a larger deficit or surplus than intended. The MyFitnessPal app also has this feature. It would be easy to implement: just some way to add extra calories burned for the day when you did some extra physical activity like exercising that day.

**Comment by davidhealey** [comment]
You can add food items with negative calories and use the categories system to mark them as exercise. You can also long press on the + in the diary to quick add calories.

**Comment by prototyperspective** [comment]
Food items with negative calories? That is only a workaround, and one most would not think of and wouldn't think is possible.

With quick adding calories, I think you mean pressing + then + again, and entering something with negative calories. The problem is you need to give it a name, portion-size and portion unit. And it has the same big problem as above. It's an unexpected workaround of adding negative calories foods, didn't even know it was possible to add negative calorie foods until now.

Please reopen, this isn't a solution...there needs to be a way to quickly add exercise / or quickly a number of negative calories.

**Comment by davidhealey** [comment]
> That is only a workaround

Yes, tracking exercise is not a feature of Waistline so if you want to make it do something it isn't designed to do you will need to use a workaround.

> With quick adding calories, I think you mean pressing + then + again, and entering something with negative calories. The problem is you need to give it a name, portion-size and portion unit.

No, I mean tap and hold (long press) on the + button in the diary.

**Comment by prototyperspective** [comment]
> tracking exercise is not a feature of Waistline

Hence this issue, please reopen. However, this is not about tracking exercise – it is just for tracking calories where calories spent is a major component. If you exclude this component, it's not a proper app for calories tracking.

> No, I mean tap and hold (long press) on the + button in the diary.

Ahhh okay. How should I know about this? Thanks. **If** this was easily found or the user informed about this feature then maaybe the issue is redundant. Could you then please add a way for the user to learn about or be informed about this feature which is basically all that I asked for here? I don't know what the best way for this would be (there could be multiple things) but think it would be adding both something to a searchable FAQ displayed within the app and sometimes displaying tooltip on the + button at some point after use (like the 5th time the app is opened or the first time 4 days in a row have been filled with data and another time after 2 months in case that was bad timing or the user didn't read it the first time). It could display something like "_Press and hold for quick calories addition (e.g. exercise)_".

**Comment by davidhealey** [comment]
> Hence this issue, please reopen.

There are already multiple requests for this



> How should I know about this?

No idea, discoverability needs to be improved definitely.
