### ISSUE TITLE
an item is added to a recipe when the back button is clicked

### ISSUE THREAD

**Issue by corngood** [davidhealey/waistline#85]
2.3.7 from f-droid

Repro steps:

- go to recipes
- click (+) to add recipe
- click (+) to add food item
- select any food item
- click check to add item
- click (+) to add food item
- click back (<-) or system back button

Each time you repeat the last two steps, the food item will be added again to the recipe.  Clicking back shouldn't add anything to the recipe.

**Comment by davidhealey** [comment]
Yep I can repeat this, good find! I'll fix this in the next update.
