### ISSUE TITLE
Recipe from raw products

### ISSUE THREAD

**Issue by Phyks** [davidhealey/waistline#86]
Hi,

First, thanks for this really nice software! I have a bit of a unique use case, I guess, since I eat mostly homemade recipes from raw products. 

I might have missed something but it seems that waistline is only using OpenFoodFacts (which is mainly about products sold in supermarkets) and does not have an extra database for raw products.

Typically, if I type "Pomme" (Apple in French) in the product search box, I get a lot of Apple puree and other products, but cannot find a raw apple.

Not sure if there is an open database out there of raw products and their nutrition facts, but I think this could be a great addition! :)

Thanks!

**Comment by davidhealey** [comment]
Hi,

Yes that is the only downside to OFF. The quickest solution is to add the food item to your local database and not use OFF for those raw ingredients. I just look on Google for the nutritional info and enter it in manually.

Another option is when you're in a supermarket pick up a bag of whatever item you want and scan the barcode. Where I live you can get almost all fresh ingredients in barcoded multi-packs. So I could scan a bag of apples, add them to OFF if they are not there already, and then that would give the best of both worlds.

**Comment by Phyks** [comment]
Thanks for the answer, I'll probably do this then.

It might be worth having an extra database of raw products and their nutritional facts, right into the app, to ease this. I've came across https://ciqual.anses.fr/ (in French, sorry), which you can [download](https://www.data.gouv.fr/fr/datasets/table-de-composition-nutritionnelle-des-aliments-ciqual/) (under an opendata license). It seems rather complete and with a lot of facts :)

**Comment by davidhealey** [comment]
Including that database would be useful. If I find the time to do it I shall, I might also add an option to search Open Food Facts offline which I think some people would find useful.

**Comment by davidhealey** [comment]
Unfortunately the database files are too large to include in Waistline and I don't know how to implement them as optional downloads. Also the language is a problem. Something like this would be good if it included an API like the OFF database so that we can search it remotely without having to download.

**Comment by serpico** [comment]
I don't know how this could be used in waistline but OFF somehow provide ( average ) data for raw product as well.

See for example https://fr.openfoodfacts.org/categorie/oignons-jaunes and https://fr.openfoodfacts.org/categorie/legumes-frais ( I didn't try to display the equivalent in any other language though...)

**Comment by vilhelmgray** [comment]
We should be able to close this now that Waistline supports the USDA database which includes information for common raw foods: https://github.com/davidhealey/waistline/issues/154
