### ISSUE TITLE
Set math relationship between Carbs/Protein/Fats

### ISSUE THREAD

**Issue by serrq** [davidhealey/waistline#863]
For example my ideal relationship is 4:2:1 on calories intake.

Carbs      240 g
Proteins  120 g
Fats           60 g

**Comment by EmilJunker** [comment]
You can set your macro nutrient goals in percent by toggling the "Goal as percentage of energy intake" in the goal editor. 

Your 4:2:1 split would roughly correspond to these goals:
- Carbs: 57%
- Proteins: 29%
- Fat: 14%
