### ISSUE TITLE
Feature request: Food Catagories reordering

### ISSUE THREAD

**Issue by Bikutoso** [davidhealey/waistline#866]
Being able to reorder Food Categories would allow users to move their categories around to fit their needs without having to worry about what order they created them in.

I noticed the problem when redoing the categories into a new system when i made the following categories:
```
Finished
Finished - Pasta
Finished - Pizza
Snacks
...
```
Then realized i forgot to add the `Finished - Soups` category, and if i add it now it's gonna appear at the bottom of the list and not where i want to it to be.
So having the ability to move then around would be appreciated.

**Comment by EmilJunker** [comment]
You can already do that. Under `Settings > Foods, Meals, Recipes > Labels and Categories`, simply press and hold a category and then move it to a different position in the list.

**Comment by Bikutoso** [comment]
I thought i had long pressed it, but that does work
Thanks for the advice and sorry for the inconvenience
