### ISSUE TITLE
Sugars are not imported from USDA FoodCentral search

### ISSUE THREAD

**Issue by Eiernase** [davidhealey/waistline#870]
I use the USDA API and whenever I search for something (e.g. "Bananas"), the entry does not contain a value for sugar, which I have to manually import from the website.
There are some other weird behaviours too, like sometimes all the values are something entirely different from what it says in the entry on their website, but I haven't figured out a pattern in that yet.

**Comment by EmilJunker** [comment]
> I use the USDA API and whenever I search for something (e.g. "Bananas"), the entry does not contain a value for sugar

You are right, I can reproduce this too. Maybe they changed something about their API again because I'm pretty sure this worked correctly in the past 😩

> sometimes all the values are something entirely different from what it says in the entry on their website

Do you have a specific example for that? Could it just be related to the serving size in Waistline being different from the website?

**Comment by EmilJunker** [comment]
It looks like they also changed their URL format, so the in-app links to open the website for a specific item no longer work correctly.

|  | URL |
| - | - |
| Old format | https://fdc.nal.usda.gov/fdc-app.html#/food-details/2709224/nutrients |
| New format | https://fdc.nal.usda.gov/food-details/2709224/nutrients |
