### ISSUE TITLE
Need to target API level 34 for Play store - discussion

### ISSUE THREAD

**Issue by davidhealey** [davidhealey/waistline#876]
I can't upload the latest build to Play store because of this. What are the potential issues of targeting API 34?

![image](https://github.com/user-attachments/assets/92ee5890-4792-4bee-bbe8-4541df861bf7)

**Comment by EmilJunker** [comment]
I don't think there is any potential for issues from raising the targetSdkVersion. As long as the minSdkVersion stays the same, nothing should really change in terms of compatibility.

It's possible that we might need to upgrade to [cordova android 13](https://cordova.apache.org/announcements/2024/05/23/cordova-android-13.0.0.html) to do this, though. But if we're lucky we can stay on version 12 and the build will still work.

**Comment by davidhealey** [comment]
Yeah looking at their compatibility table I think Cordova Android 13 will be necessary, I'll try with 12 first though.

**Comment by samtate** [comment]
I boosted to API v34 and Cordova 13 in my WIP Health Connect PR and it didn't seem to cause any issues from my limited testing of the app at the time.

**Comment by davidhealey** [comment]
Oh yeah I've already done it in fact, I'll close this issue now.
