### ISSUE TITLE
[Feature] Display all goals

### ISSUE THREAD

**Issue by Maximus1996** [davidhealey/waistline#88]
Hello,
First of all thank you very much for this app and the fact that you made it available through F-Droid.
I have just one suggestion that I think would be helpful. In the current state, in the diary, we can only see the calories count and how much remaining to achieve the daily objectif.
Maybe it would be nice to add other counters for other goals when set (Protein, Carbs, Fat etc...) as they can´t be tracked (unless calculated manually). 
It could be added also in the "Goals" tab and not in the diary.
The idea is to track every goal that the user has set and not only calories.
Thank you very much again.

**Comment by davidhealey** [comment]
These are tracked on the stats page but as was recently discussed in another issue I will add something similar to the diary pages too in a future update
