### ISSUE TITLE
Cannot change pics in any items since latest update

### ISSUE THREAD

**Issue by thebigjoe1** [davidhealey/waistline#881]
Possible bug if affecting others...Long pressing a picture of a food item, meal, or recipe no longer provides me with the option to remove picture should I desire to do so. This worked fine in the previous version prior to the latest update. Now my phone will vibrate with a long hold but not provide me with any options.

**Comment by EmilJunker** [comment]
I think this bug is severe enough to warrant another bugfix release now that it's fixed. It also affected the food upload feature, i.e. once you added a product photo, you could not remove or replace it. @davidhealey what do you think?

**Comment by davidhealey** [comment]
@EmilJunker Sure, I'll run off a new build now
