### ISSUE TITLE
Multi Select

### ISSUE THREAD

**Issue by Mitlik** [davidhealey/waistline#92]
Somewhat in the vein of issue #77, it would be nice to multi select diary entries for delete or modify serving size. This would he similar to a lot of file picker interfaces

The desire for delete stems from the date issue being worked elsewhere. The desire for serving modification stems from the current recipe implementation where all base ingredients are dumped into the diary without the chance to modify serving size.

**Comment by davidhealey** [comment]
Multi-select of the diary is a good idea. I'm going to change the recipe system, what we currently have will be called "Meals" and a new recipe system will be implemented that adds the recipe as a single item to the diary.

**Comment by Mitlik** [comment]
That sounds great. Once that's in place and #52 is resolved I suspect this request will be a rarely used feature.
