### ISSUE TITLE
Collapsable meal headings

### ISSUE THREAD

**Issue by Mitlik** [davidhealey/waistline#93]
Breaking out my suggestion from issue #77 to use long press on diary meal headings to collapse/expand.

**Comment by davidhealey** [comment]
Yes, this will be implemented

**Comment by davidhealey** [comment]
Hi,

I've implemented this now in the latest development branch (I haven't pushed it yet). Instead of long press it uses single press on a meal heading to collapse/expand the list. To add a food to a specific category/meal requires a double tap on the heading.
